// Copyright 2006 Nemanja Trifunovic

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/


#ifndef UTF8_FOR_CPP_HELPERS_H
#define UTF8_FOR_CPP_HELPERS_H

#include <string>

namespace utf8
{
    template <typename w>
    std::string narrow(const w& input)
    {
        std::string temp;
        unchecked::utf16to8(input.begin(), input.end(), back_inserter(temp));
        return temp;
    }
    
    template <typename w>
    void narrow(const w& src, std::string& dest)
    {
        unchecked::utf16to8(src.begin(), src.end(), back_inserter(dest));
    }
    
    template <typename n>
    void widen(const n& src, std::wstring& dest)
    {
        unchecked::utf8to16(src.begin(), src.end(), back_inserter(dest));
    }
    

    template <typename c>
    std::wstring widen(const c* inputPtr)
    {
        std::string input(inputPtr);
        std::wstring temp;
        unchecked::utf8to16(input.begin(), input.end(), std::back_inserter(temp));
        return temp;
    }


    template <typename n>
    std::wstring widen(const n& inputRef)
    {
        std::string input(inputRef);
        std::wstring temp;
        unchecked::utf8to16(input.begin(), input.end(), std::back_inserter(temp));
        return temp;
    }

} // namespace utf8 


#endif // header guard

