#include "stdafx.h"
#include "cnst_text.h" 

LPCWSTR LANG_DATA_ENG[2184] = {
	L"Would you like to receive tutorial tips and hints?",
	L"",
	L"+",
	L"-",
	L"Ok",
	L"Cancel",
	L"Yes",
	L"No",
	L"Reset",
	L"n/a",
	L"Close",
	L"Help",
	L"Cast",
	L"Info",
	L"Map size",
	L"Map version",
	L"Author",
	L"Dismiss",
	L"Build",
	L"Board Ship",
	L"Recruit",
	L"Requires:",
	L"Cost:",
	L"Guard:",
	L"Visited",
	L"Not Visited",
	L"Owned by",
	L"None",
	L"Split",
	L"Trade",
	L"Surrender",
	L"Retreat",
	L"Load",
	L"Save",
	L"<...>",
	L"Load a Saved Game:",
	L"Save the Current Game:",
	L"Select a Scenario to Play:",
	L"Victory",
	L"CONGRATULATIONS!",
	L"Defeat",
	L"TRAGIC DEFEAT",
	L"Map Name",
	L"Auto Combat",
	L"Melee:",
	L"Shoot:",
	L"Kingdom Overview",
	L"Puzzle Map",
	L"System Menu",
	L"Daily Income:",
	L"Uncharted Territory",
	L"Unoccupied",
	L"No Tavern",
	L"Select a Destination",
	L"Select a Castle to retreat",
	L"Growth",
	L"Available",
	L"Cost per Troop",
	L"Recruit",
	L"Total cost",
	L"Mana",
	L"Level",
	L"Lvl",
	L"Experience",
	L"Travel Points",
	L"Leave Guards",
	L"Choose units to defend castle with (first line)",
	L"Saved at",
	L"Game Date",
	L"Kingdom Resources",
	L"Available for Trade",
	L"Upgrade creatures",
	L"Through a clearing you see an ancient artifact. Unfortunately, it's guarded by:",
	L"Much to your dismay, the %s is guarded by:",
	L"Do you wish to fight the guards?",
	L"Registration",
	L"Device ID:",
	L"Registration Key:",
	L"Register",
	L"Later",
	L"Registration Succeeded",
	L"Registration Failed",
	L"The Registration Key used to activate Palm Heroes game is invalid.",
	L"Thank You for buying Palm Heroes game!",
	L"Visit our official web site www.palmheroes.com to buy the game.",
	L"Buy Palm Heroes game at www.pocketland.de",
	L"#FCCCAfter purchasing Palm Heroes game at #FFF6Handango#FCCC, you receive a game certificate. In order to complete your registration, you have to activate your copy in the official game site www.palmheroes.com",
	L"Get More Maps",
	L"Sound",
	L"Off",
	L"Key Map",
	L"Key Map Settings",
	L"Game Language",
	L"Press the key you want to assign...",
	L"- N/A -",
	L"Start",
	L"Up",
	L"Down",
	L"Left",
	L"Right",
	L"Button #1",
	L"Button #2",
	L"Button #3",
	L"Button #4",
	L"Button #5",
	L"Button #6",
	L"Record",
	L"Talk",
	L"End",
	L"Back",
	L"Home",
	L"Soft #1",
	L"Soft #2",
	L"Help Mode",
	L"Hand Mode",
	L"Survey Map",
	L"Minimize",
	L"Make Screenshot",
	L"Quicksave",
	L"Show Hero Reminder",
	L"Show Map Grid",
	L"Show combat grid",
	L"Quick Combat",
	L"Show Travel Points",
	L"Smoothed Survey Map",
	L"4x Survey Map Scale",
	L"Left Hand Mode",
	L"Autosave",
	L"Autozoom on hold",
	L"Advanced Combat",
	L"Sound Volume",
	L"Music Volume",
	L"Display Gamma",
	L"Map Scroll",
	L"Hero Speed",
	L"Combat Speed",
	L"Sticky path",
	L"One-handed mode",
	L"Very Slow",
	L"Slow",
	L"Normal",
	L"Fast",
	L"Very Fast",
	L"Jan",
	L"Feb",
	L"Mar",
	L"Apr",
	L"May",
	L"Jun",
	L"Jul",
	L"Aug",
	L"Sep",
	L"Oct",
	L"Nov",
	L"Dec",
	L"Your current game will be lost. Are you sure you want to load another game?",
	L"Your current game will be lost. Are you sure you want to restart scenario?",
	L"Are you sure you want to quit?",
	L"Your current game will be lost. Are you sure you want to exit to main menu?",
	L"The selected slot already used. Overwrite?",
	L"Game saved...",
	L"Unable To Save",
	L"No more space: choose existing slot!",
	L"Screenshot saved...",
	L"Sorry - this feature is not available in the current version.",
	L"You've won!",
	L"has gained level %d",
	L"This is maximum level allowed for this scenario.",
	L"#FFFF%s #S0#FDDD(%s level %d)",
	L"All prerequisites for this building have been met",
	L"Already built",
	L"Are you sure you want to dismiss this army?",
	L"Are you sure you want to dismiss this Hero?",
	L"A group of %s with a desire for greater glory wish to join you. Do you accept?",
	L"The %s, awed by the power of your forces, begin to scatter. Do you wish to pursue and engage them?",
	L"Your hero may learn:",
	L"Your hero has learned:",
	L"Which do you choose?",
	L"Make room for the %s in your army.",
	L"Choose a unit to resurrect:",
	L"%s states:",
	L"I will accept your surrender and grant you and your army safe passage for the price of %d gold.",
	L"You need %d experience points to reach the next level.",
	L"%s Player has been Vanquished!",
	L"There is no room in the garrison for this troop.",
	L"Are you sure you want to end your turn?",
	L"Please inspect our fine wares. If you feel like offering a trade, click on the items you wish to trade.",
	L"I can offer you:",
	L"%s   for   %s",
	L"No ships are available. Try building one next week.",
	L"This ship is occupied and is already sailing off.",
	L"Build New Ship",
	L"Board Ship",
	L"You already have four heroes.",
	L"There are no heroes in this Tavern to recruit. Come back next week.",
	L"That spell will affect no one!",
	L"Choose target: ",
	L"Not enough mana to cast the spell.",
	L"This spell requires %s skill at %s level.",
	L"Does %d points of damage.",
	L"The creatures are willing to join us!",
	L"These weak creatures will surely flee before us.",
	L"I fear these creatures are in the mood for a fight.",
	L"No spell selected",
	L"Your hero is too tired to cast this spell today. Try again tomorrow.",
	L"Required Level %d hero with %s skill.",
	L"Required Level %d hero.",
	L"Required hero with %s skill.",
	L"%s player's turn.",
	L"%s player is under attack!",
	L"You should have known better - you have been attacked!",
	L"Digging for artifacts requires an entire day, try again tomorrow.",
	L"Try searching on clear ground.",
	L"Congratulations! After spending many hours digging here, your hero has uncovered the Conqueror's Crown.",
	L"Nothing here. Where could it be?",
	L"There are seven resources in Palm Heroes used to build and improve castles, purchase troops and recruit Heroes. Gold is the most common and is required for virtually everything. Wood and Ore are used for most buildings. Gems, Mercury, Sulfur and Crystal are rare magical resources used for the most powerful creatures and buildings.",
	L"Experience allows your Heroes to advance levels, increasing their primary and secondary skills.",
	L"Spell Points are required to cast spells. Your Hero's maximum spell point level is 10 times your Knowledge Skill. Certain events and structures may temporarily increase your maximum spell point level.",
	L"Travel Points determine how far your Hero can move each day. The distance is determined by the type of terrain, roads, and the level of your Logistics and Pathfinding skills. Special locations, events and artifacts can also increase the number of Travel Points.",
	L"Attack skill is a bonus added to the base attack skill of any troops your Hero commands, allowing them to inflict more damage in combat.",
	L"Defense skill is a bonus added to the base defense skill of any troops your Hero commands, allowing them to resist more damage in combat.",
	L"Spell power determines the duration or strength of a spell.",
	L"Knowledge determines you Hero's number of Spell Points. Under normal circumstances, a Hero is limited to 10 spell points per level of Knowledge.",
	L"Good luck allows your troops to inflict damage in combat.",
	L"With neutral luck your troops' attacks will be unmodified.",
	L"Bad luck reduces affected troops' damage by half.",
	L"Good morale may result in extra attacks for affected troops.",
	L"Neutral morale eliminates the potential for troops to freeze in combat or be endowed with extra attacks",
	L"Bad morale may cause your troops to freeze in combat.",
	L"Resetting High Scores will delete any accomplishments you have achieved. Are you sure you want to reset the High Scores?",
	L"If you like this game, please consider giving it a short review and a good rating in the Appstore. This will significantly help us improve it and provide you with updates really soon. Rate now?",
	L"The town is occupied by another Hero",
	L"You have reached the Heroes limit",
	L"New Week",
	L"New Month",
	L"Astrologers Proclaim Month of the %s.",
	L"Astrologers Proclaim Month of the PLAGUE!",
	L"Astrologers Proclaim Week of the %s.",
	L"All Dwellings Increase in Population.",
	L"All Populations are Halved.",
	L"%s Population Doubles!",
	L"%s growth +5.",
	L"Squirrel",
	L"Rabbit",
	L"Gopher",
	L"Badger",
	L"Rat",
	L"Eagle",
	L"Weasel",
	L"Raven",
	L"Mongoose",
	L"Dog",
	L"Aardvark",
	L"Lizard",
	L"Tortoise",
	L"Hedgehog",
	L"Condor",
	L"Grasshopper",
	L"Ant",
	L"Mummy",
	L"Spider",
	L"Butterfly",
	L"Bumblebee",
	L"Locust",
	L"Earthworm",
	L"Hornet",
	L"Beetle",
	L"Battlefield Casualties",
	L"Attacker",
	L"Defender",
	L"Combat Log",
	L"High morale enables the %s to attack again.",
	L"Low morale causes the %s to freeze in panic.",
	L"Good luck shines on the %s",
	L"Bad luck descends on the %s",
	L"Round %d",
	L"Attack %s",
	L"Shoot %s",
	L" (%d damage)",
	L" (%d-%d damage)",
	L"The %s do %d damage.",
	L"%d %s perish.",
	L"The %s pause and wait for a better time to act.",
	L"The %s take a defensive stance and gain +%d defense skill.",
	L"The turret does %d damage.",
	L"The moat does %d damage.",
	L"%s destroy half the enemy troops!",
	L"Cast %s.",
	L"Cast %s on %s.",
	L"%s casts %s.",
	L"%s casts %s to %s.",
	L"The %s spell does %d damage.",
	L"The %s resist the spell.",
	L"You have captured an enemy artifact!",
	L"You have captured %d enemy artifacts!",
	L"A Glorious Victory!",
	L"The Enemy has Fled!",
	L"The Enemy has Surrendered!",
	L"For valor in combat, %s receives %d experience.",
	L"Your forces suffer a bitter defeat, and %s abandons your cause.",
	L"Your forces suffer a bitter defeat.",
	L"The cowardly %s flees from battle.",
	L"%s surrenders to the enemy and departs in shame.",
	L"%s wields the Sphere of Negation, an ancient artifact which prevents magic spells from being cast.",
	L"%s wields the Shackles of War. You can not retreat or surrender!",
	L"You don't have enough gold!",
	L"Practicing the dark arts of necromancy, you are able to raise %d of the enemy's dead to return under your service as %s.",
	L"Small",
	L"Medium",
	L"Large",
	L"Extra Large",
	L"S",
	L"M",
	L"L",
	L"XL",
	L"Rank",
	L"Land",
	L"Date",
	L"Days",
	L"Score",
	L"Difficulty Level",
	L"Easy",
	L"Normal",
	L"Hard",
	L"Expert",
	L"Impossible",
	L"Victory condition",
	L"Defeat all enemies",
	L"Defeat hero: %s",
	L"Capture castle: %s",
	L"Survive for %d days",
	L"Get %d of %s",
	L"Get artifact: %s",
	L"Get %d of %s",
	L"Get spell: %s",
	L"Find Conqueror's Crown",
	L"Victory is yours!",
	L"Congratulations! All your enemies have been defeated! Victory is yours!",
	L"Congratulations! The enemy's Hero has been defeated! Victory is yours!",
	L"Congratulations! You have captured the enemy's Castle! Victory is yours!",
	L"Congratulations! You managed to survive for the required period of time! Victory is yours!",
	L"Congratulations! You managed to gather all the required resources! Victory is yours!",
	L"Congratulations! You found the required Artifact! Victory is yours!",
	L"Congratulations! You managed to gather all the units you needed! Victory is yours!",
	L"Congratulations! You managed to learn the required spell! Victory is yours!",
	L"Congratulations! You found the Ultimate Artifact! Victory is yours!",
	L"Lose condition",
	L"Lose all castles and heroes",
	L"Lose hero: %s",
	L"Lose castle: %s",
	L"Sorry, but you have lost...",
	L"All your forces have been defeated, and you are banished from this land!",
	L"Your hero has been defeated, and you are banished from this land!",
	L"Your castle has been captured, and you are banished from this land!",
	L"Somebody else managed to fulfill the wining condition before you! You lost the Game!",
	L"You didn't complete your mission in time. Game is lost!",
	L"Single Player",
	L"New Game",
	L"New Scenario",
	L"New Random Map",
	L"Multiplayer",
	L"Online Game",
	L"Help",
	L"Tutorial",
	L"Load Game",
	L"Save game",
	L"Hall of Fame",
	L"Credits",
	L"Game Settings",
	L"Restart Scenario",
	L"Main Menu",
	L"Quit",
	L"Return to Game",
	L"Hot-Seat",
	L"Download Maps",
	L"Name",
	L"Size",
	L"Author",
	L"Played",
	L"Rating",
	L"Humans",
	L"Name",
	L"Date",
	L"Progress",
	L"Size",
	L"MAPS",
	L"Adventure",
	L"Action",
	L"Hot-Seat",
	L"All Maps",
	L"Back",
	L"Download",
	L"PLAY NOW!",
	L"Updating map list, please wait...",
	L"Map list update failed, try again later.",
	L"Processing your download, please wait...",
	L"Sorry, download failed.",
	L"Sorry, you have no network connection.",
	L"You have successfully downloaded an item!",
	L"The purchases have been disabled in Settings.",
	L"Restore your purchases",
	L"Restoring purchases...",
	L"Free",
	L"Update for free",
	L"HOT NEW",
	L"Price",
	L"Updates",
	L"Number of Towns",
	L"Number of Heroes",
	L"Resources",
	L"Obelisks Found",
	L"Artifacts",
	L"Army Strength",
	L"Income",
	L"Water",
	L"Beach",
	L"Dirt",
	L"Grass",
	L"Swamp",
	L"Lava",
	L"Wasteland",
	L"Desert",
	L"Snow",
	L"Desert",
	L"Pavement",
	L"Barren",
	L"Coast",
	L"Lake",
	L"player",
	L"player",
	L"Red",
	L"Green",
	L"Blue",
	L"Cyan",
	L"Purple",
	L"Yellow",
	L"Orange",
	L"Red",
	L"Green",
	L"Blue",
	L"Cyan",
	L"Purple",
	L"Yellow",
	L"Orange",
	L"Undefined",
	L"Human",
	L"Computer",
	L"Human only",
	L"Computer only",
	L"Human or Computer",
	L"Date",
	L"Month",
	L"Week",
	L"Day",
	L"M",
	L"W",
	L"D",
	L"Attack",
	L"Defense",
	L"Sp. power",
	L"Knowl.",
	L"Shots",
	L"Damage",
	L"Health",
	L"Speed",
	L"Quant.",
	L"Morale",
	L"Luck",
	L"Attack Skill",
	L"Defense Skill",
	L"Spell Power",
	L"Knowledge",
	L"Shots",
	L"Damage",
	L"Health",
	L"Speed",
	L"Quantity",
	L"Morale",
	L"Luck",
	L"Estates",
	L"Leadership",
	L"Luck",
	L"Diplomacy",
	L"Air Magic",
	L"Earth Magic",
	L"Fire Magic",
	L"Water Magic",
	L"Wisdom",
	L"Necromancy",
	L"Mysticism",
	L"Intelligence",
	L"Resistance",
	L"Sorcery",
	L"Learning",
	L"Scouting",
	L"Logistics",
	L"Pathfinding",
	L"Archery",
	L"Ballistics",
	L"Offense",
	L"Armorer",
	L"Hero contributes 250 gold per day to your cause.",
	L"Hero contributes 500 gold per day to your cause.",
	L"Hero contributes 1000 gold per day to your cause.",
	L"Increases your Hero's troops' morale by 1.",
	L"Increases your Hero's troops' morale by 2.",
	L"Increases your Hero's troops' morale by 3.",
	L"Increases your Hero's luck by 1.",
	L"Increases your Hero's luck by 2.",
	L"Increases your Hero's luck by 3.",
	L"Allows you to negotiate with monsters who are weaker than your group and reduces the cost of surrendering by 20%.",
	L"Allows you to negotiate with monsters who are weaker than your group and reduces the cost of surrendering by 40%.",
	L"Allows you to negotiate with monsters who are weaker than your group and reduces the cost of surrendering by 60%.",
	L"Basic Air Magic allows your Hero to cast Air spells at reduced cost.",
	L"Advanced Air Magic allows your Hero to cast Air spells at reduced cost and increased effectiveness.",
	L"Expert Air Magic allows your Hero to cast Air spells at reduced cost and maximum effectiveness.",
	L"Basic Earth Magic allows your Hero to cast Earth spells at reduced cost.",
	L"Advanced Earth Magic allows your Hero to cast Earth spells at reduced cost and increased effectiveness.",
	L"Expert Earth Magic allows your Hero to cast Earth spells at reduced cost and maximum effectiveness.",
	L"Basic Fire Magic allows your Hero to cast Fire spells at reduced cost.",
	L"Advanced Fire Magic allows your Hero to cast Fire spells at reduced cost and increased effectiveness.",
	L"Expert Fire Magic allows your Hero to cast Fire spells at reduced cost and maximum effectiveness.",
	L"Basic Water Magic allows your Hero to cast Water spells at reduced cost.",
	L"Advanced Water Magic allows your Hero to cast Water spells at reduced cost and increased effectiveness.",
	L"Expert Water Magic allows your Hero to cast Water spells at reduced cost and maximum effectiveness.",
	L"Allows your Hero to learn Third level spells.",
	L"Allows your Hero to learn Fourth level spells.",
	L"Allows your Hero to learn Fifth level spells.",
	L"Allows 10% of the creatures killed in combat to be brought back from the dead as Skeletons.",
	L"Allows 20% of the creatures killed in combat to be brought back from the dead as Skeletons.",
	L"Allows 30% of the creatures killed in combat to be brought back from the dead as Skeletons.",
	L"Allows your Hero to regenerate 2 spell points per day.",
	L"Allows your Hero to regenerate 4 spell points per day.",
	L"Allows your Hero to regenerate 6 spell points per day.",
	L"Increases a Hero's normal maximum spell points by 25%.",
	L"Increases a Hero's normal maximum spell points by 50%.",
	L"Doubles a Hero's normal maximum spell points.",
	L"Endows a Hero's troops with 5% magic resistance.",
	L"Endows a Hero's troops with 10% magic resistance.",
	L"Endows a Hero's troops with 20% magic resistance.",
	L"Causes a Hero's spells to inflict an additional 5% damage in combat.",
	L"Causes a Hero's spells to inflict an additional 10% damage in combat.",
	L"Causes a Hero's spells to inflict an additional 15% damage in combat.",
	L"Increases a Hero's earned experience by 5%.",
	L"Increases a Hero's earned experience by 10%.",
	L"Increases a Hero's earned experience by 15%.",
	L"Allows your Hero to see 2 squares further into the shroud.",
	L"Allows your Hero to see 4 squares further into the shroud.",
	L"Allows your Hero to see 6 squares further into the shroud.",
	L"Increases your Hero's movement points over land by 10%.",
	L"Increases your Hero's movement points over land by 20%.",
	L"Increases your Hero's movement points over land by 30%.",
	L"Reduces the movement penalty for rough terrain by 25%.",
	L"Reduces the movement penalty for rough terrain by 50%.",
	L"Reduces the movement penalty for rough terrain by 75%.",
	L"Increases ranged attack damage by 10%.",
	L"Increases ranged attack damage by 25%.",
	L"Increases ranged attack damage by 50%.",
	L"Allows one aimed shot with increased damage.",
	L"Allows two aimed shots with increased damage.",
	L"Allows two aimed shots with maximum damage.",
	L"Increases hand-to-hand attack damage by 10%.",
	L"Increases hand-to-hand attack damage by 20%.",
	L"Increases hand-to-hand attack damage by 30%.",
	L"Reduces all damage inflicted against the Hero's troops by 5%.",
	L"Reduces all damage inflicted against the Hero's troops by 10%.",
	L"Reduces all damage inflicted against the Hero's troops by 15%.",
	L"Basic",
	L"Advanced",
	L"Expert",
	L"Gold",
	L"Ore",
	L"Wood",
	L"Mercury",
	L"Gem",
	L"Crystal",
	L"Sulfur",
	L"Random Resource",
	L"Heap of Gold",
	L"Heap of Ore",
	L"Cord of Wood",
	L"Bottle of Mercury",
	L"Heap of Gems",
	L"Heap of Crystals",
	L"Heap of Sulfur",
	L"Mana Crystal",
	L"Campfire",
	L"Treasure Chest",
	L"Lamp",
	L"Spell Scroll",
	L"Artifact",
	L"Guard",
	L"As you reign in your horse, a guard steps up to you and says, \"Welcome. I have received word of your arrival. Do you wish to pass at this time?\"",
	L"\"No one told me of your coming,\" says the Border Guard. \"I cannot let you pass. Perhaps you should first seek a Keymaster's Tent.\"",
	L"After scouting the area you stumble upon a hidden treasure cache. You may take the gold or distribute it to the peasants for experience.",
	L"You find a spell scroll inscribed with the %s spell.",
	L"Event",
	L"Marker",
	L"Random",
	L"Random (Level 1)",
	L"Random (Level 2)",
	L"Random (Level 3)",
	L"Random (Level 4)",
	L"Random (Level 5)",
	L"Random (Level 6)",
	L"Random",
	L"Random (Level 1)",
	L"Random (Level 2)",
	L"Random (Level 3)",
	L"Random (Level 4)",
	L"Hole",
	L"Crack",
	L"Skeleton",
	L"Flowers",
	L"Mushrooms",
	L"Rock",
	L"Stump",
	L"Log",
	L"Cactus",
	L"Bush",
	L"Trees",
	L"Palm Tree",
	L"Pine Tree",
	L"Oak Tree",
	L"Dead Tree",
	L"Volcano",
	L"Mountain",
	L"Lake",
	L"Wall",
	L"Dirt Road",
	L"Stone Road",
	L"Snow Road",
	L"River",
	L"Lava River",
	L"Harbor",
	L"Portal",
	L"Light Stone",
	L"Wooden Sign",
	L"Watch Tower",
	L"Medusa Temple",
	L"Rogue Wagon",
	L"Desert Tent",
	L"Haunted House",
	L"Stone Well",
	L"Gazebo",
	L"Tree of Knowledge",
	L"Monolith",
	L"Windmill",
	L"Shrine of First Circle",
	L"Shrine of Second Circle",
	L"Shrine of Third Circle",
	L"Stables",
	L"Idol",
	L"Trinity",
	L"Fountain",
	L"Temple",
	L"Sword in the Stone",
	L"Fort",
	L"Forge",
	L"Stonehenge",
	L"Magic Stone",
	L"Prophet Statue",
	L"Arena",
	L"Library",
	L"Obelisk",
	L"Magic Spring",
	L"Garden of Knowledge",
	L"Witch Hut",
	L"Shipwreck",
	L"Ice Cave",
	L"Pyramid",
	L"Temple of Inti",
	L"Ogre's Treasury",
	L"Mage's Treasury",
	L"Hydras' Treasury",
	L"Medusa's Treasury",
	L"Gargoyle's Treasury",
	L"Druids' Treasury",
	L"Mage Citadel",
	L"Monk Abbey",
	L"Mausoleum",
	L"Magic School",
	L"Pegasus Waterfall",
	L"White Wolf Den",
	L"Warg Cave",
	L"Sarcophagus",
	L"Vampire Coffin",
	L"Wolf Den OLD",
	L"Boars Pen OLD",
	L"Swordsman Armory OLD",
	L"Halfling hut OLD",
	L"Dummy",
	L"Keymaster's Tent",
	L"Foundry",
	L"Ogre's Adobe",
	L"Mummy's Sarcophagus",
	L"Elven Homestead",
	L"Druid's Stones",
	L"Griffin's Nest",
	L"Hunter's Cabin",
	L"Volchv's Shrine",
	L"Blacksmith's Forge",
	L"Witch's Lodge",
	L"Mercenary Barracks",
	L"Vityaz's Residence",
	L"Tatar Yurt",
	L"War Academy",
	L" ",
	L"A drink from the well has restored your spell points.",
	L"An old Knight appears on the steps of the gazebo. \"My liege, I will teach you all that I know to aid you in your travels.\"",
	L"Upon your approach, the tree opens its eyes in delight. \"Ahh, an adventurer! Allow me to teach you a little of what I have learned over the ages.\"",
	L"Upon your approach, the monolith begins to shine. You manage to decypher the symbols carved on its surface.",
	L"The keeper of the mill announces: \"Milord, I have been working very hard to provide you with these resources, come back next week for more.\"",
	L"You come across a small shrine attended by a group of novice acolytes. In exchange for your protection, they agree to teach you a simple spell - ",
	L"You come across an ornate shrine attended by a group of rotund friars. In exchange for your protection, they agree to teach you a spell - ",
	L"You come across a lavish shrine attended by a group of high priests. In exchange for your protection, they agree to teach you a sophisticated spell - ",
	L"As you approach the stables, the head groom appears, leading a fine looking war horse. \"This steed will help speed you in your travels. Alas, his endurance will wane with heavy riding, and you must return for a fresh mount week.\"",
	L"You've found an ancient and weathered stone idol. Kissing it is supposed to bring luck or happiness, so you do. The stone is very cold to the touch.",
	L"Here's all I have collected during the week. Use this gold wisely.",
	L"As you drink the sweet water, you gain luck for your next battle.",
	L"A visit and a prayer at the temple raises the morale of your troops.",
	L"You have spent several hours trying to get the sword out of the stone, but it hasn't moved an inch... But don't get upset: your army had a good rest while you were having a good exercise!",
	L"During the hour spent in the fort, the master shows you new defense technique.",
	L"You approach a forge... You walk inside and see a blacksmith at work. He puts the hammer away and says: \"I can repair your armor.\"",
	L"You've found a group of Druids worshipping at one of their strange stone edifices. Silently, they teach you new ways to cast spells.",
	L"You've found a group of pagans worshipping at their strange glowing stone. You join the ritual. Silently, they teach you new ways to cast spells.",
	L"You touch the prophet statue and feel that you become more powerful.",
	L"You enter the arena and face a pack of vicious lions. You handily defeat them, to the wild cheers of the crowd. Impressed by your skill, the aged trainer of gladiators agrees to train you in Attack and Defense skills.",
	L"The caretaker admits you into the Library of Enlightenment. You are able to learn much in the short time you spend here.",
	L"You come upon an obelisk made from a type of stone you have never seen before. Staring at it intensely, the smooth surface suddenly changes to an inscription. The inscription is a piece of a lost ancient map. Quickly you copy down the odd markings and the inscription vanishes as abruptly as it had appeared.",
	L"A drink from the spring fills your blood with magic! You have twice your normal spell points in reserve.",
	L"A monk sitting in the center of a garden invites you to meditate with him. You do and, after a short time, you feel enlightened.",
	L"The caretaker of this Keymaster's Tent seems happy to see you. \"Ah, finally someone worthy,\" he says. \"I shall send word immediately to the Border Guard that you be allowed to pass.\"",
	L" ",
	L"A second drink at the well in one week will not help you.",
	L"An old Knight appears on the steps of the gazebo. \"I am sorry, my liege, I have taught you all I can.\"",
	L"Upon your approach, the tree opens its eyes in delight. \"It is good to see you, my student. I hope my teachings have helped you.\"",
	L"Upon your approach, the monolith light fades out.",
	L"The keeper of the mill announces: \"Milord, I am sorry, there are no resources currently available. Please try again next week.\"",
	L"The head groom approaches you and speaks, \"You already have a fine horse.\"",
	L"You've found an ancient and weathered stone idol. It is supposed to grant luck or happiness to visitors, but since the stars are already shining upon you, it does nothing.",
	L"I have no more gold for you. Come back next week.",
	L"You drink from the enchanted fountain, but nothing happens.",
	L"It doesn't help to pray twice before a battle.",
	L"This sword is stuck in the stone! No use trying to get it out!",
	L"I have already taught you everything I could. I don't want to waste my time on you, so get out!",
	L"You approach a forge... You walk inside and see a blacksmith at work. He examines your shield, and says: \"The shield doesn't need to be repaired. I have done everything I could.\"",
	L"You've found a group of Druids worshipping at one of their strange stone edifices. Silently, the Druids turn you away, indicating they have nothing new to teach you.",
	L"You've found a group of pagans worshipping at their strange glowing stone. Silently, the worshippers turn you away, indicating they have nothing new to teach you.",
	L"You touch the statue, but nothing happens. You reach out your hand and touch it for the second time, and the statue suddenly starts to speak: \"I have given you my magical power, but you still keep annoying me!? Go away!\"",
	L"The Arena guards prevent you from entering. \"You've already beaten our best. Begone from here.\"",
	L"Recognizing you, the caretaker refuses to admit you. \"The Library of Enlightenment,\" he says, \"may be visited but once\".",
	L"You have already been to this obelisk.",
	L"The magic spring only regenerates once a week, and someone has already been here this week.",
	L"You enter the garden, and the monk, recognizing you, says, \"My child, the blessing of knowledge comes but once in a person's lifetime.\"",
	L"The caretaker of this Keymaster's Tent recognizes you as you approach. \"I have already sent word that you be allowed to pass,\" he says. \"Begone.\"",
	L"Unfortunately, you do not have the wisdom to understand the spell and are unable to learn it.",
	L"An ancient witch living in a strange hut welcomes you, teaching you %s for her own inscrutable purposes.",
	L"You approach the strange hut and observe a witch inside studying an ancient tome on %s. As you approach, she turns and speaks. \"You already know that which I would teach you. I can help you no further.\"",
	L"You approach the strange hut and observe a witch inside studying an ancient tome on %s. As you approach, she turns and focuses her one glass eye on you. \"HA!\" she screeches, \"I would not presume to try to teach new tricks to someone so clearly as wise as you.\" You leave, but can't quite shake the feeling that you have just been insulted.",
	L"Would you like to recruit %s?",
	L"%d %s join your army.",
	L"There are no %s here to recruit.",
	L"You have found what was once a %s, but it has been deserted for some time.",
	L"Having defeated the guards, you discover:",
	L"Teleport",
	L"Teleport",
	L"Teleport",
	L"This structure is obviously a travel gate, but it no longer appears to be functioning.",
	L"Choose a creature to upgrade",
	L"Sorry, this creature can't be improved.",
	L"Scout Tower",
	L"Observation Tower",
	L"From the scouting tower, you are able to see distant lands.",
	L"From the observation tower, you are able to see distant lands. All your heroes get a +1 movement point bonus.",
	L"Gold Mine",
	L"Ore Pit",
	L"Wood Sawmill",
	L"Alchemist's Lab",
	L"Gems Mine",
	L"Crystal Mine",
	L"Sulfur Mine",
	L"You gain control of a Gold Mine. It will provide you with 1000 gold per day.",
	L"You gain control of an Ore Pit. It will provide you with two units of ore per day.",
	L"You gain control of a Wood Sawmill. It will provide you with two units of wood per day.",
	L"You gain control of an Alchemist's Lab. It will provide you with one unit of mercury per day.",
	L"You gain control of a Gems Mine . It will provide you with one unit of gems per day.",
	L"You gain control of a Crystal Mine . It will provide you with one unit of crystal per day.",
	L"You gain control of a Sulfur Mine . It will provide you with one unit of sulfur per day.",
	L"City Gate",
	L"Ship",
	L"visited",
	L"not visited",
	L"Knight",
	L"Barbarian",
	L"Wizard",
	L"Warlock",
	L"Sorceress",
	L"Necromancer",
	L"Varangian",
	L"Gerald",
	L"Fineous",
	L"Jacob",
	L"Schultz",
	L"Cantor",
	L"Bez",
	L"Earoon",
	L"Hedric",
	L"Tyrex",
	L"Grottekvarnen",
	L"Yog",
	L"Jaclyn",
	L"Krag",
	L"Baraka",
	L"Hapax",
	L"Krull",
	L"Cronus",
	L"Iona",
	L"Bernhard",
	L"Posid",
	L"Malcolm",
	L"Morgana",
	L"Victor",
	L"Visarus",
	L"Gallatin",
	L"Altus",
	L"Odin",
	L"Kastore",
	L"Alamar",
	L"Eldor",
	L"Fondo",
	L"Marcus",
	L"Jack",
	L"Ferentona",
	L"Gem",
	L"Arven",
	L"Samira",
	L"Myrini",
	L"Rebecca",
	L"Dvergar",
	L"Rait",
	L"Urof",
	L"Tamika",
	L"Shra",
	L"Ruthven",
	L"Ranloo",
	L"Sandru",
	L"Knecht Ruprecht",
	L"Alexey",
	L"Dobrinya",
	L"Ilya",
	L"Lytobor",
	L"Miroslav",
	L"Oleg",
	L"Vladimir",
	L"Yaropolk",
	L"Random",
	L"Citadel",
	L"Stronghold",
	L"Tower",
	L"Dungeon",
	L"Fortress",
	L"Necropolis",
	L"Kremlin",
	L"Small",
	L"Medium",
	L"Large",
	L"Mage Guild",
	L"Shipyard",
	L"Peasants' Hut",
	L"Archers' Tower",
	L"Guardhouse",
	L"Abbey",
	L"Jousting Arena",
	L"Cathedral",
	L"Goblin Barracks",
	L"Orc Tower",
	L"Warg Cave",
	L"Ogre fort",
	L"Troll Bridge",
	L"Cyclops Pyramid",
	L"Magic School",
	L"Wolf Den",
	L"Factory",
	L"Magic Cloud",
	L"Mage Tower",
	L"Cloud Palace",
	L"Centaurs' Cave",
	L"Crypt",
	L"Griffin Tower",
	L"Labyrinth",
	L"Hydra Pond",
	L"Dragon Cave",
	L"Treehouse",
	L"Dwarf Cottage",
	L"Homestead",
	L"Stonehenge",
	L"Unicorn Glade",
	L"Red Tower",
	L"Excavation",
	L"Graveyard",
	L"Mausoleum",
	L"Sarcophagus",
	L"Dark Tomb",
	L"Cursed Tower",
	L"Hunter Cabin",
	L"Forge",
	L"Barracks",
	L"Forest Hut",
	L"Shrine",
	L"Residence",
	L"Mage Guild 1",
	L"Mage Guild 2",
	L"Mage Guild 3",
	L"Mage Guild 4",
	L"Mage Guild 5",
	L"Magic Node",
	L"Tavern",
	L"Marketplace",
	L"Town Hall",
	L"City Hall",
	L"Ore Mine",
	L"Sawmill",
	L"Alchemist's Lab",
	L"Gems Mine",
	L"Crystal Mine",
	L"Sulfur Mine",
	L"Moat",
	L"Main Turret",
	L"Left Turret",
	L"Right Turret",
	L"Shooting Range",
	L"Mess Hall",
	L"Caverns",
	L"Waterfall",
	L"Miners' Guild",
	L"Unearthed Graves",
	L"Scout Tower",
	L"Lodge",
	L"Merchant Shop",
	L"Lookout Tower",
	L"Fortifications",
	L"Hall of Valhalla",
	L"Adobe",
	L"Wall of Knowledge",
	L"Library",
	L"Altar",
	L"Mana Vortex",
	L"Treasury",
	L"Mystic Pond",
	L"Necromancy Amplifier",
	L"Cover of Darkness",
	L"The %s allows you to recruit %s.",
	L"Entering the Mage Guild will allow a visiting hero to learn the spells kept within.",
	L"Restores 1 mana point each day for all friendly heroes.",
	L"The Tavern allows you hire Heroes and increases morale for troops defending the city.",
	L"Within the Marketplace, you can buy and sell resources (exchange rates increase with each Marketplace you own).",
	L"The Town Hall increases your kingdom revenue by 500 gold per day",
	L"The City Hall increases your kingdom revenue by 1500 gold per day",
	L"The Ore Mine provides you with an additional +1 ore each day.",
	L"The Sawmill provides you with an additional +1 wood each day.",
	L"The Alchemist's Lab provides you with an additional +1 mercury each day.",
	L"The Gems Mine provides you with an additional +1 gems each day.",
	L"The Crystal Mine provides you with an additional +1 crystal each day.",
	L"The Sulfur Mine provides you with an additional +1 sulfur each day.",
	L"The Moat slows attacking units. Any unit entering the moat must end its turn there and becomes more vulnerable to attack.",
	L"The Main Turret provides extra firepower during castle combat.",
	L"The Left Turret provides extra firepower during castle combat.",
	L"The Right Turret provides extra firepower during castle combat.",
	L"The %s increases %s production by %d per week.",
	L"The Lodge gives a bonus squad that helps to defend the castle.",
	L"The Merchant Shop improves market exchange rates.",
	L"The Lookout Tower extends the visible distance around your city, and all you heroes receive +5 travel points bonus.",
	L"Fortifications improve the durability of castle walls during a siege.",
	L"The Hall of Valhalla increases the Attack skill of any visiting hero by +1.",
	L"The Wall of Knowledge increases the Knowledge of any visiting hero by +1.",
	L"The Library randomly changes some of the spells in your magic guild at the beginning of each month.",
	L"The Altar increases your kingdom revenue by 1000 gold per day",
	L"The Mana Vortex temporarily doubles spell points for visiting hero.",
	L"The Treasury increases your income by 1000/day.",
	L"The Mystic Pond produces a small random number of resources each week.",
	L"The Necromancy Amplifier increases the Necromancy skill of all heroes you control (with Necromancy skill) by 10%.",
	L"The Cover of Darkness covers your city with a permanent shroud to all other players.",
	L"The pond has not produced anything yet.",
	L"The pond produced %s this week.",
	L"The Hall of Valhalla has increased your Attack skill by +1.",
	L"The Mana Vortex has doubled your spell points.",
	L"The Wall of Knowledge has increased your Knowledge by +1.",
	L"After a short visit to Mage Guild you learned new spells.",
	L"Silver Sword",
	L"Peasant's Sickle",
	L"Knight's Breastplate",
	L"Dragon Shield",
	L"Monk's Ring",
	L"Witch's Brooch of Magic",
	L"Minor Scroll of Knowledge",
	L"Parchment Scroll",
	L"Pendant of Wisdom",
	L"Medal of Honor",
	L"Medal of Distinction",
	L"Lucky Dice",
	L"Clover of Luck",
	L"Silver Bird Of Luck",
	L"Long Bow",
	L"Necromancer's Ring",
	L"Telescope",
	L"Protective Cloak of Air",
	L"Protective Cloak of Earth",
	L"Protective Cloak of Fire",
	L"Protective Cloak of Water",
	L"Jar of Mana",
	L"Power Axe",
	L"Warrior's Helmet",
	L"Caster's Bracelet of Magic",
	L"Scroll of Enlightenment",
	L"Soldier's Helm",
	L"Sage's Ring",
	L"White Pearl Necklace",
	L"Golden Bird of Luck",
	L"Endless Cart of Ore",
	L"Endless Cord of Wood",
	L"Ring of Life",
	L"Pendant of Life",
	L"Elf's Longbow",
	L"Vampire's Cowl",
	L"Traveler's Boots",
	L"Diplomat's Quill",
	L"Cloak of Resistance",
	L"Clock of Swiftness",
	L"Enchanted Sword",
	L"Armor of Might",
	L"Ring of Power",
	L"Tome of Knowledge",
	L"Ancient Broadsword",
	L"Dwarf's Shield",
	L"Paladin's Shield",
	L"Staff of Wizardy",
	L"Major Scroll of Knowledge",
	L"Book of Wisdom",
	L"Eclipse",
	L"Snake Bracelet",
	L"Black Pearl Necklace",
	L"Pendant of Omniscience",
	L"Ring of Perpetuity",
	L"Crossbow",
	L"Necromancer's Sword",
	L"Golden Ring",
	L"Golden Chalice",
	L"Amulet of Wealth",
	L"Endless Vial of Mercury",
	L"Endless Pouch of Gems",
	L"Sulfur Ring",
	L"Crystal Rose",
	L"Nomad Boots",
	L"Long Sword",
	L"Hero's Shield",
	L"Precursor's Helmet",
	L"Wizard's Hat",
	L"Swordbreaker",
	L"Warlock's Necklace",
	L"Sphere of Negation",
	L"Sorcerer's Wand",
	L"Shackles of War",
	L"Conqueror's Crown",
	L"Throwing Axe",
	L"Goblin's Shield",
	L"Caster's Pendant",
	L"Sword of the Cursed",
	L"Sphere of Air",
	L"Sphere of Earth",
	L"Sphere of Fire",
	L"Sphere of Water",
	L"Iron Mace",
	L"Golden Mace",
	L"Golden Sword",
	L"Golden Shield",
	L"Golden Armor",
	L"Golden Skull",
	L"Iron Greaves",
	L"Bone Greaves",
	L"Bastard Sword",
	L"Circlet of air",
	L"Ranger's Hat",
	L"Leather Armor",
	L"Goblin Cap",
	L"Bone Necklace",
	L"Dwarven Helm",
	L"Rider's Helm",
	L"Ogre Shield",
	L"Arrows",
	L"Sun Rod",
	L"Dwarven Hammer",
	L"Winged Helmet",
	L"Bone Mask",
	L"Bone Armor",
	L"King's Shield",
	L"Bloodstone Necklace",
	L"Fast Crossbow",
	L"Swamp Boots",
	L"Ice Amulet",
	L"Increases your Attack skill by 1.",
	L"Increases your Attack skill by 1, increases Peasant's attack by 3.",
	L"Increases your Defense skill by 1, increases Cavalry defence by 2.",
	L"Increases your Defense skill by 1, increases the Dragon's defence by 5.",
	L"Increases your Spell Power by 1, increases Monk's attack by 3.",
	L"Increases your Spell Power by 1.",
	L"Increases your Knowledge by 1.",
	L"Increases your Knowledge by 1.",
	L"Increases your Knowledge by 1.",
	L"Increases your Morale by 1.",
	L"Increases your Morale by 1.",
	L"Increases your Luck by 1.",
	L"Increases your Luck by 1.",
	L"Increases your Luck by 1.",
	L"Increases your Archery skill by 5%.",
	L"Increases your Necromancy skill by 5%.",
	L"Allows your hero to see 1 square further into the shroud.",
	L"Reduces damage by 30% received from Air spells.",
	L"Reduces damage by 30% received from Earth spells.",
	L"Reduces damage by 30% received from Fire spells.",
	L"Reduces damage by 30% received from Water spells.",
	L"Recovers 2 extra spell points per day.",
	L"Increases your Attack skill by 3.",
	L"Increases your Defense skill by 2.",
	L"Increases your Spell Power by 2.",
	L"Increases your Knowledge by 2.",
	L"Increases your Attack and Defense skills by 1.",
	L"Increases your Spell Power and Knowledge by 1.",
	L"Increases your Spell Power and Knowledge by 1.",
	L"Increases your Luck by 2.",
	L"Provides you with an additional +1 Ore per day.",
	L"Provides you with an additional +1 wood per day.",
	L"Increases the health of all your units by 1.",
	L"Increases the health of all your units by 2.",
	L"Increases your Archery skill by 10%, increases Elf's attack by 3.",
	L"Increases your Necromancy skill by 10%, increases Vampire's defence by 1.",
	L"Increases your movement over land by 20 points.",
	L"Reduces the cost of surrendering by 20%.",
	L"Increases your Magic Resistance by 10%.",
	L"Increases the combat speed of all your units by 1.",
	L"Increases your Attack skill by 3.",
	L"Increases your Defense skill by 3.",
	L"Increases your Spell Power by 3.",
	L"Increases your Knowledge by 3.",
	L"Increases your Attack skill by 4.",
	L"Increases your Defense skill by 4.",
	L"Increases your Defense skill by 4, increases Paladin's defence by 2.",
	L"Increases your Spell Power by 4.",
	L"Increases your Knowledge by 4.",
	L"Increases your Knowledge by 4.",
	L"Increases your Attack and Defense skills by 2.",
	L"Increases your Spell Power and Knowledge by 2.",
	L"Increases your Spell Power and Knowledge by 2.",
	L"Increases your Attack skill, Defense skill, Spell Power, and Knowledge by 1.",
	L"Increases the health of all your units by 3.",
	L"Increases your Archery skill by 15%.",
	L"Increases your Necromancy skill by 15%.",
	L"Increases your income by 500 gold per day.",
	L"Increases your income by 750 gold per day.",
	L"Increases your income by 1000 gold per day.",
	L"Provides you with an additional +1 Mercury per day.",
	L"Provides you with an additional +1 Gems per day.",
	L"Provides you with an additional +1 Sulfur per day.",
	L"Provides you with an additional +1 Crystal per day.",
	L"Increases your movement over land by 30 points, increases Nomad's speed by 3.",
	L"Increases your Attack skill by 6.",
	L"Increases your Defense skill by 6.",
	L"Increases your Spell Power by 6.",
	L"Increases your Knowledge by 6.",
	L"Increases your Attack and Defense skills by 3.",
	L"Increases your Spell Power and Knowledge by 3.",
	L"Increases your Attack skill, Defense skill, Spell Power, and Knowledge by 2.",
	L"Neither you nor your opponent may retreat or surrender.",
	L"Prevents all spell casting in combat.",
	L"Each hero type receives their special bonuses...",
	L"Increases your income by 5000 gold per day. Increases your hero's Attack skill, Defense skill, Spell Power, and Knowledge by +4. Increases your hero's movement points over land by +10%. Increases the combat speed of all your units by +2.",
	L"Increases your income by 5000 gold per day. Increases your hero's Attack skill, Defense skill, Spell Power, and Knowledge by +4. Endows a hero's troops with 50% magic resistance. Allows your troops shoot through any obstacle or at any range without penalty.",
	L"Increases your income by 5000 gold per day. Increases your hero's Attack skill and Defense skill +4, Spell Power and Knowledge by +6. Increases effectiveness of resurrect and summon spells by 50%. ",
	L"Increases your income by 5000 gold per day. Increases your hero's Attack skill and Defense skill +4, Spell Power and Knowledge by +6. Regenerates all spell points each day.",
	L"Increases your income by 5000 gold per day. Increases your hero's Attack skill and Defense skill +4, Spell Power and Knowledge by +6. Increases damage from all destructive spells by 50%.",
	L"Increases your income by 5000 gold per day. Increases your hero's Attack skill, Defense skill, Spell Power, and Knowledge by +4. Increases your Necromancy skill by 15%. Resurrects battlefield dead as Vampires.",
	L"Increases your income by 5000 gold per day. Increases your hero's Attack skill, Defense skill, Spell Power, and Knowledge by +4. Increases your hero's movement points over water by +40%. Increases the combat speed of all your units by +2.",
	L"Increases your Attack skill by 2.",
	L"Increases your Defense skill by 4, increases Goblin's defence by 3.",
	L"Increases your Spell Power by 2.",
	L"Covers your hero with a permanent shroud to all other players.",
	L"Increases your Air Magic skills by 50%",
	L"Increases your Earth Magic skills by 50%",
	L"Increases your Fire Magic skills by 50%",
	L"Increases your Water Magic skills by 50%",
	L"Increases your Attack skill by 1.",
	L"Increases your income by 250 gold per day. Increases your Attack skill by 3.",
	L"Increases your income by 250 gold per day. Increases your Attack skill by 3.",
	L"Increases your income by 250 gold per day. Increases your Defence skill by 3.",
	L"Increases your income by 250 gold per day. Increases your Defence skill by 2. Increases your Luck by 1.",
	L"Increases your Spell Power by 1.",
	L"Increases your Defense skill by 2.",
	L"Increases your Defense skill by 1.",
	L"Recovers 5 extra spell points per day.",
	L"Increases your Attack skill by 2.",
	L"Increases your Spell Power by 1.",
	L"Increases your Archery skill by 15%, increases Archer's defence by 3.",
	L"Increases your Defense skill by 1.",
	L"Increases your Defense skill by 1, increases Goblin's defence by 2.",
	L"Increases your Morale and Luck by 1.",
	L"Increases your Defense skill by 2, increases Dwarf's defence by 4.",
	L"Increases your Defense skill by 2.",
	L"Increases your Defense skill by 2, increases Ogre's defence by 4.",
	L"Infinite shots for ranged units.",
	L"Increases your Attack skill by 3, increases Dwarf's attack by 3.",
	L"Increases your Defense skill by 2 and Travel points by 15.",
	L"Increases your Defense skill by 2 and decreases enemy Morale by 2.",
	L"Increases your Defense skill by 3 and decreases enemy Morale by 1.",
	L"Increases your Defense skill by 3 and Morale by 1.",
	L"Increases you Spell Power by 1 and adds 15% damage to your magic spells.",
	L"No distance penalty for ranged attacks.",
	L"Increases your movement over land by 25 points.",
	L"Decreases the speed of enemy troops by 2.",
	L"Few",
	L"Several",
	L"Pack",
	L"Lots",
	L"Horde",
	L"Throng",
	L"Swarm",
	L"Legion",
	L"a Few",
	L"Several",
	L"a Pack of",
	L"Lots of",
	L"a Horde of",
	L"a Throng of",
	L"a Swarm of",
	L"a Legion of",
	L"Peasant",
	L"Peasants",
	L"Peasants",
	L"Archer",
	L"Archers",
	L"Archers",
	L"Pikeman",
	L"Pikemen",
	L"Pikemen",
	L"Monk",
	L"Monks",
	L"Monks",
	L"Cavalry",
	L"Cavalries",
	L"Cavalries",
	L"Paladin",
	L"Paladins",
	L"Paladins",
	L"Goblin",
	L"Goblins",
	L"Goblins",
	L"Orc",
	L"Orcs",
	L"Orcs",
	L"Warg rider",
	L"Warg riders",
	L"Warg riders",
	L"Ogre",
	L"Ogres",
	L"Ogres",
	L"Troll",
	L"Trolls",
	L"Trolls",
	L"Cyclops",
	L"Cyclopes",
	L"Cyclopes",
	L"Young mage",
	L"Young mages",
	L"Young mages",
	L"White wolf",
	L"White wolves",
	L"White wolves",
	L"Living armor",
	L"Living armors",
	L"Living armors",
	L"Pegasus",
	L"Pegasi",
	L"Pegasi",
	L"Mage",
	L"Mages",
	L"Mages",
	L"Thor",
	L"Thors",
	L"Thors",
	L"Centaur",
	L"Centaurs",
	L"Centaurs",
	L"Gargoyle",
	L"Gargoyles",
	L"Gargoyles",
	L"Griffin",
	L"Griffins",
	L"Griffins",
	L"Minotaur",
	L"Minotaurs",
	L"Minotaurs",
	L"Hydra",
	L"Hydras",
	L"Hydras",
	L"Red Dragon",
	L"Red Dragons",
	L"Red Dragons",
	L"Sprite",
	L"Sprites",
	L"Sprites",
	L"Dwarf",
	L"Dwarves",
	L"Dwarves",
	L"Elf",
	L"Elves",
	L"Elves",
	L"Druid",
	L"Druids",
	L"Druids",
	L"Unicorn",
	L"Unicorns",
	L"Unicorns",
	L"Firebird",
	L"Firebirds",
	L"Firebirds",
	L"Skeleton",
	L"Skeletons",
	L"Skeletons",
	L"Zombie",
	L"Zombies",
	L"Zombies",
	L"Lich",
	L"Liches",
	L"Liches",
	L"Vampire",
	L"Vampires",
	L"Vampires",
	L"Black Knight",
	L"Black Knights",
	L"Black Knights",
	L"Plague",
	L"Plagues",
	L"Plagues",
	L"Hunter",
	L"Hunters",
	L"Hunters",
	L"Blacksmith",
	L"Blacksmiths",
	L"Blacksmiths",
	L"Mercenary",
	L"Mercenaries",
	L"Mercenaries",
	L"Witch",
	L"Witches",
	L"Witches",
	L"Magus",
	L"Magi",
	L"Magi",
	L"Vityaz",
	L"Vityazes",
	L"Vityazes",
	L"Militia",
	L"Militia",
	L"Militia",
	L"Citizen",
	L"Citizens",
	L"Citizens",
	L"Crossbowman",
	L"Crossbowmen",
	L"Crossbowmen",
	L"Sharpshooter",
	L"Sharpshooters",
	L"Sharpshooters",
	L"Heavy Pikeman",
	L"Heavy Pikemen",
	L"Heavy Pikemen",
	L"Halberdier",
	L"Halberdiers",
	L"Halberdiers",
	L"Exorcist",
	L"Exorcists",
	L"Exorcists",
	L"Bishop",
	L"Bishops",
	L"Bishops",
	L"Heavy Cavalry",
	L"Heavy Cavalries",
	L"Heavy Cavalries",
	L"Knight",
	L"Knights",
	L"Knights",
	L"Crusader",
	L"Crusaders",
	L"Crusaders",
	L"Holy Warrior",
	L"Holy Warriors",
	L"Holy Warriors",
	L"Contagious Goblin",
	L"Contagious Goblins",
	L"Contagious Goblins",
	L"Goblin Warrior",
	L"Goblin Warriors",
	L"Goblin Warriors",
	L"Orc Chief",
	L"Orc Chiefs",
	L"Orc Chiefs",
	L"Orc Warrior",
	L"Orc Warriors",
	L"Orc Warriors",
	L"Wild Warg",
	L"Wild Wargs",
	L"Wild Wargs",
	L"Warg Warrior",
	L"Warg Warriors",
	L"Warg Warriors",
	L"Ogre Chief",
	L"Ogre Chiefs",
	L"Ogre Chiefs",
	L"Ogre Shaman",
	L"Ogre Shamans",
	L"Ogre Shamans",
	L"Ballista Troll",
	L"Ballista Trolls",
	L"Ballista Trolls",
	L"Troll Shaman",
	L"Troll Shamans",
	L"Troll Shamans",
	L"Ancient Cyclops",
	L"Ancient Cyclopes",
	L"Ancient Cyclopes",
	L"Dire Cyclops",
	L"Dire Cyclopes",
	L"Dire Cyclopes",
	L"Neophyte",
	L"Neophytes",
	L"Neophytes",
	L"Mage Apprentice",
	L"Mage Apprentices",
	L"Mage Apprentices",
	L"Red Wolf",
	L"Red Wolves",
	L"Red Wolves",
	L"Two-Headed Wolf",
	L"Two-Headed Wolves",
	L"Two-Headed Wolves",
	L"Steel Guard",
	L"Steel Guards",
	L"Steel Guards",
	L"War Machine",
	L"War Machines",
	L"War Machines",
	L"Royal Pegasus",
	L"Royal Pegasi",
	L"Royal Pegasi",
	L"Blinding Pegasus",
	L"Blinding Pegasi",
	L"Blinding Pegasi",
	L"Air Mage",
	L"Air Mages",
	L"Air Mages",
	L"Prophet",
	L"Prophets",
	L"Prophets",
	L"Legend",
	L"Legends",
	L"Legends",
	L"Demigod",
	L"Demigods",
	L"Demigods",
	L"Centaur Ranger",
	L"Centaur Rangers",
	L"Centaur Rangers",
	L"Centaur Lord",
	L"Centaur Lords",
	L"Centaur Lords",
	L"Obsidian Gargoyle",
	L"Obsidian Gargoyles",
	L"Obsidian Gargoyles",
	L"Stone Gargoyle",
	L"Stone Gargoyles",
	L"Stone Gargoyles",
	L"Snake Griffin",
	L"Snake Griffins",
	L"Snake Griffins",
	L"Royal Griffin",
	L"Royal Griffins",
	L"Royal Griffins",
	L"Minotaur Reaper",
	L"Minotaur Reapers",
	L"Minotaur Reapers",
	L"Dire Minotaur",
	L"Dire Minotaurs",
	L"Dire Minotaurs",
	L"Poisonous Hydra",
	L"Poisonous Hydras",
	L"Poisonous Hydras",
	L"Ancient Hydra",
	L"Ancient Hydras",
	L"Ancient Hydras",
	L"Fire Dragon",
	L"Fire Dragons",
	L"Fire Dragons",
	L"Black Dragon",
	L"Black Dragons",
	L"Black Dragons",
	L"Elusive Sprite",
	L"Elusive Sprites",
	L"Elusive Sprites",
	L"Poisonous Sprite",
	L"Poisonous Sprites",
	L"Poisonous Sprites",
	L"Axe Hurler",
	L"Axe Hurlers",
	L"Axe Hurlers",
	L"Berzerker",
	L"Berzerkers",
	L"Berzerkers",
	L"Elf Ranger",
	L"Elf Rangers",
	L"Elf Rangers",
	L"Elf Hunter",
	L"Elf Hunters",
	L"Elf Hunters",
	L"Grand Druid",
	L"Grand Druids",
	L"Grand Druids",
	L"Outcast",
	L"Outcasts",
	L"Outcasts",
	L"Royal Unicorn",
	L"Royal Unicorns",
	L"Royal Unicorns",
	L"Ghost Unicorn",
	L"Ghost Unicorns",
	L"Ghost Unicorns",
	L"Phoenix",
	L"Phoenixes",
	L"Phoenixes",
	L"Magic Firebird",
	L"Magic Firebirds",
	L"Magic Firebirds",
	L"Skeleton Archer",
	L"Skeleton Archers",
	L"Skeleton Archers",
	L"Skeleton Warrior",
	L"Skeleton Warriors",
	L"Skeleton Warriors",
	L"Contagious Zombie",
	L"Contagious Zombies",
	L"Contagious Zombies",
	L"Tough Zombie",
	L"Tough Zombies",
	L"Tough Zombies",
	L"Archlich",
	L"Archliches",
	L"Archliches",
	L"Powerful Lich",
	L"Powerful Liches",
	L"Powerful Liches",
	L"Nosferatu",
	L"Nosferatus",
	L"Nosferatus",
	L"Vampire Lord",
	L"Vampire Lords",
	L"Vampire Lords",
	L"Death Knight",
	L"Death Knights",
	L"Death Knights",
	L"Black Grail Knight",
	L"Black Grail Knights",
	L"Black Grail Knights",
	L"Death",
	L"Deaths",
	L"Deaths",
	L"Fear",
	L"Fears",
	L"Fears",
	L"Old Hunter",
	L"Old Hunters",
	L"Old Hunters",
	L"Mature Hunter",
	L"Mature Hunters",
	L"Mature Hunters",
	L"Noble Blacksmith",
	L"Noble Blacksmiths",
	L"Noble Blacksmiths",
	L"Werewolf",
	L"Werewolves",
	L"Werewolves",
	L"Boyarin",
	L"Boyarins",
	L"Boyarins",
	L"Royal Guard",
	L"Royal Guards",
	L"Royal Guards",
	L"Enchanter",
	L"Enchanters",
	L"Enchanters",
	L"Yaga",
	L"Yagas",
	L"Yagas",
	L"Leshiy",
	L"Leshiys",
	L"Leshiys",
	L"Great Volchv",
	L"Great Volchvs",
	L"Great Volchvs",
	L"Bogatyr",
	L"Bogatyrs",
	L"Bogatyrs",
	L"Volot",
	L"Volots",
	L"Volots",
	L"Rogue",
	L"Rogues",
	L"Rogues",
	L"Nomad",
	L"Nomads",
	L"Nomads",
	L"Ghost",
	L"Ghosts",
	L"Ghosts",
	L"Genie",
	L"Genies",
	L"Genies",
	L"Medusa",
	L"Medusas",
	L"Medusas",
	L"Earth Elemental",
	L"Earth Elementals",
	L"Earth Elementals",
	L"Air Elemental",
	L"Air Elementals",
	L"Air Elementals",
	L"Fire Elemental",
	L"Fire Elementals",
	L"Fire Elementals",
	L"Water Elemental",
	L"Water Elementals",
	L"Water Elementals",
	L"Tatar Archer",
	L"Tatar Archers",
	L"Tatar Archers",
	L"Gorynych",
	L"Gorynyches",
	L"Gorynyches",
	L"Moat",
	L"Wall",
	L"Turret",
	L"Bridge",
	L"Catapult",
	L"Gets off two shots in each ranged attack",
	L"Delivers two blows per attack",
	L"Suffers no penalty hand-to-hand",
	L"No enemy retaliation",
	L"Counterstrikes everyone",
	L"Two hex attack",
	L"Attacks all adjacent enemy troops",
	L"Attacks non-undead creatures near target",
	L"Undead creature",
	L"Lifeless creature",
	L"Regenerates hit points each round",
	L"+5% damage per hex traveled to target",
	L"Immune to Air magic",
	L"Immune to Earth magic",
	L"Immune to Fire magic",
	L"Immune to Water magic",
	L"Has a 40% chance to ignore the a spell",
	L"Takes only 25% damage from spells",
	L"Killed units become Ghosts",
	L"10% chance of destroying half of the target",
	L"Resurrects itself",
	L"Decreases enemy morale by 1",
	L"Poison damage for 3 turns",
	L"+100% against any undeads",
	L"When quantity falls below 50%, bloodlust is cast",
	L"Curses any enemy",
	L"20% chance to blind the enemy",
	L"Generates +1 gold/day",
	L"Returns after attack",
	L"Castellatus",
	L"Starkmauer",
	L"Kanan",
	L"Linderhoff",
	L"Whitemoon",
	L"Yaroslavl",
	L"Middleheim",
	L"Brettonia",
	L"Alexandretta",
	L"Whitestone",
	L"Claxton",
	L"Armitage",
	L"Shinnon",
	L"Gateway",
	L"Dunwall",
	L"Kildare",
	L"Kragg",
	L"Jimstadt",
	L"Hartgrim",
	L"Sandflash",
	L"Morganheim",
	L"Cragmoor",
	L"Dragonspire",
	L"Battlement",
	L"Bocc",
	L"Slau",
	L"Tormina",
	L"Dolere",
	L"Rockwarren",
	L"Strongglen",
	L"Kruber",
	L"Rovener",
	L"Tutanberg",
	L"Stronggale",
	L"Corona",
	L"Silverwing",
	L"Facture",
	L"Cloudfire",
	L"Cloudspire",
	L"Equinox",
	L"Athenaeum",
	L"Valtara",
	L"Tirith",
	L"Fallen Star",
	L"Mystos",
	L"Ayer",
	L"Silverspire",
	L"Manufactury",
	L"Veks",
	L"Sorrow Crown",
	L"Chillwater",
	L"Deepshadow",
	L"Darkhold",
	L"Blindroot",
	L"Shadowden",
	L"Scar",
	L"Malev",
	L"Castigare",
	L"Dukered",
	L"Shade",
	L"Evernight",
	L"Darkburrow",
	L"Lost Hold",
	L"Coldshadow",
	L"Starmino",
	L"Grigorov",
	L"Sigman",
	L"Still Water",
	L"Elfwind",
	L"Sebian",
	L"Ceiliedgh",
	L"Gladeroot",
	L"Avalon",
	L"Rainhaven",
	L"Strongglen",
	L"Marishen",
	L"Bath'iere",
	L"Green Falls",
	L"Emerald Moor",
	L"Wild Willow",
	L"Haunt's Wind",
	L"Cessacioun",
	L"Agony",
	L"Victorash",
	L"Terminus",
	L"Blackquarter",
	L"Sandro",
	L"Grave Raven",
	L"Dark Cloud",
	L"Coldsoul",
	L"Coldreign",
	L"Dark Eternal",
	L"Ghostwind",
	L"Blight",
	L"Shady Sands",
	L"Wolfengrott",
	L"Hedinsey",
	L"Saxon",
	L"Knan-kun",
	L"Babylon",
	L"Blackmoon",
	L"Trag",
	L"Trondheim",
	L"Krondor",
	L"Al-qaar",
	L"Blackstone",
	L"Onyx",
	L"Hermit",
	L"Stargate",
	L"Tiger Eye",
	L"Cotulla",
	L"Dalgebra",
	L"Magic Arrow",
	L"Protect (earth)",
	L"Haste",
	L"Shield",
	L"Disrupting Ray",
	L"Lightning Bolt",
	L"Precision",
	L"Air Shield",
	L"Holy Word",
	L"Counterstrike",
	L"Resurrect",
	L"Air Elemental",
	L"Protect (air)",
	L"Slow",
	L"Stone Skin",
	L"Visions",
	L"Earthquake",
	L"Sorrow",
	L"Meteor Shower",
	L"Town Portal",
	L"Implosion",
	L"Earth Elemental",
	L"Bloodlust",
	L"Protect (water)",
	L"Curse",
	L"Blind",
	L"Weakness",
	L"Death Ripple",
	L"Fireball",
	L"Misfortune",
	L"Animate Dead",
	L"Fireblast",
	L"Armageddon",
	L"Fire Elemental",
	L"Bless",
	L"Protect (fire)",
	L"Dispel",
	L"Cure",
	L"Cold Ray",
	L"Fortune",
	L"Mirth",
	L"Cold Ring",
	L"Anti-Magic",
	L"Prayer",
	L"Water Elemental",
	L"Summon Sprites",
	L"Poisoned",
	L"Causes a bolt of magical energy to strike the selected unit (Power*10).",
	L"Causes a bolt of magical energy to strike the selected unit (Power*10).",
	L"Causes a bolt of magical energy to strike the selected unit (Power*12).",
	L"Causes a bolt of magical energy to strike the selected unit (Power*15).",
	L"Protects the selected unit, reducing damage by 30% received from Earth spells.",
	L"Protects the selected unit, reducing damage by 30% received from Earth spells.",
	L"Protects the selected unit, reducing damage by 50% received from Earth spells.",
	L"Protects all friendly units, reducing damage by 50% received from Earth spells.",
	L"Increases the speed of the selected unit by 3.",
	L"Increases the speed of the selected unit by 3.",
	L"Increases the speed of the selected unit by 5.",
	L"Increases the speed of all friendly units by 5.",
	L"Shields a selected unit, reducing the amount of damage by 15% received from hand-to-hand attacks.",
	L"Shields a selected unit, reducing the amount of damage by 15% received from hand-to-hand attacks.",
	L"Shields a selected unit, reducing the amount of damage by 30% received from hand-to-hand attacks.",
	L"Shields all friendly units, reducing the amount of damage by 30% received from hand-to-hand attacks.",
	L"Reduces the selected enemy unit's defense strength by 3. A single enemy may be targeted multiple times by this spell.",
	L"Reduces the selected enemy unit's defense strength by 3. A single enemy may be targeted multiple times by this spell.",
	L"Reduces the selected enemy unit's defense strength by 4. A single enemy may be targeted multiple times by this spell.",
	L"Reduces the selected enemy unit's defense strength by 5. A single enemy may be targeted multiple times by this spell.",
	L"Causes a bolt of lightning to strike the selected unit (Power*25).",
	L"Causes a bolt of lightning to strike the selected unit (Power*25).",
	L"Causes a bolt of lightning to strike the selected unit (Power*27).",
	L"Causes a bolt of lightning to strike the selected unit (Power*30).",
	L"Increases the ranged attack damage inflicted by the selected unit by 3.",
	L"Increases the ranged attack damage inflicted by the selected unit by 3.",
	L"Increases the ranged attack damage inflicted by the selected unit by 5.",
	L"Increases the ranged attack damage inflicted by all friendly units by 5.",
	L"Shields a selected unit, reducing the amount of damage by 25% received from ranged attacks.",
	L"Shields a selected unit, reducing the amount of damage by 25% received from ranged attacks.",
	L"Shields a selected unit, reducing the amount of damage by 50% received from ranged attacks.",
	L"Shields all friendly units, reducing the amount of damage by 50% received from ranged attacks.",
	L"Attempts to destroy any undead creatures on the battlefield (Power*10).",
	L"Attempts to destroy any undead creatures on the battlefield (Power*10).",
	L"Attempts to destroy any undead creatures on the battlefield (Power*12).",
	L"Attempts to destroy any undead creatures on the battlefield (Power*15).",
	L"The selected unit will retaliate against one additional attack each round.",
	L"The selected unit will retaliate against one additional attack each round.",
	L"The selected unit will retaliate against two additional attacks each round.",
	L"The selected unit will retaliate against three additional attacks each round.",
	L"Resurrects units in the selected group by restoring permanently a fixed number of hit points to the target (Power*40).",
	L"Resurrects units in the selected group by restoring permanently a fixed number of hit points to the target (Power*40).",
	L"Resurrects units in the selected group by restoring permanently a fixed number of hit points to the target (Power*45).",
	L"Resurrects units in the selected group by restoring permanently a fixed number of hit points to the target (Power*50).",
	L"Allows you to summon Air Elementals (Power*3). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Air Elementals (Power*3). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Air Elementals (Power*4). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Air Elementals (Power*5). Once cast, no other elemental types may be summoned.",
	L"Protects the selected unit, reducing damage by 30% received from Air spells.",
	L"Protects the selected unit, reducing damage by 30% received from Air spells.",
	L"Protects the selected unit, reducing damage by 50% received from Air spells.",
	L"Protects all friendly units, reducing damage by 50% received from Air spells.",
	L"Reduces the speed of the selected enemy unit by 3.",
	L"Reduces the speed of the selected enemy unit by 3.",
	L"Reduces the speed of the selected enemy unit by 6.",
	L"Reduces the speed of all enemy units by 6.",
	L"Increases the selected unit's defense strength by 3.",
	L"Increases the selected unit's defense strength by 3.",
	L"Increases the selected unit's defense strength by 6.",
	L"Increases the defense strength of all friendly units by 6.",
	L"Gives you exact numbers of wandering monsters and tells you if they would be willing to join your hero. Allows you to view a nearby enemy hero's primary skill statistics, creature type and quantity, as if the hero was part of your kingdom, as well as a nearby town's statistics, garrison creatures and quantity.",
	L"Gives you exact numbers of wandering monsters and tells you if they would be willing to join your hero. Allows you to view a nearby enemy hero's primary skill statistics, creature type and quantity, as if the hero was part of your kingdom, as well as a nearby town's statistics, garrison creatures and quantity.",
	L"Gives you exact numbers of wandering monsters and tells you if they would be willing to join your hero. Allows you to view a nearby enemy hero's primary skill statistics, creature type and quantity, as if the hero was part of your kingdom, as well as a nearby town's statistics, garrison creatures and quantity.",
	L"Gives you exact numbers of wandering monsters and tells you if they would be willing to join your hero. Allows you to view a nearby enemy hero's primary skill statistics, creature type and quantity, as if the hero was part of your kingdom, as well as a nearby town's statistics, garrison creatures and quantity.",
	L"Randomly damages two sections of castle wall in combat.",
	L"Randomly damages two sections of castle wall in combat.",
	L"Randomly damages three sections of castle wall in combat.",
	L"Randomly damages four sections of castle wall in combat.",
	L"Reduces the morale of the selected enemy unit by 1.",
	L"Reduces the morale of the selected enemy unit by 1.",
	L"Reduces the morale of the selected enemy unit by 2.",
	L"Reduces the morale of all enemy units by 2.",
	L"Causes a meteor shower to rain down on the selected target and any adjacent units (Power*25).",
	L"Causes a meteor shower to rain down on the selected target and any adjacent units (Power*25).",
	L"Causes a meteor shower to rain down on the selected target and any adjacent units (Power*27).",
	L"Causes a meteor shower to rain down on the selected target and any adjacent units (Power*30).",
	L"Teleports your hero to the nearest friendly town. The town must be unoccupied.",
	L"Teleports your hero to the nearest friendly town. The town must be unoccupied.",
	L"Teleports your hero to any friendly town. The town must be unoccupied.",
	L"Teleports your hero to any friendly town. The town must be unoccupied.",
	L"Inflicts massive damage to a selected enemy unit (Power*60).",
	L"Inflicts massive damage to a selected enemy unit (Power*60).",
	L"Inflicts massive damage to a selected enemy unit (Power*70).",
	L"Inflicts massive damage to a selected enemy unit (Power*80).",
	L"Allows you to summon Earth Elementals (Power*3). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Earth Elemental (Power*3). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Earth Elemental (Power*4). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Earth Elemental (Power*5). Once cast, no other elemental types may be summoned.",
	L"Increases the hand-to-hand damage inflicted by the selected unit by 3.",
	L"Increases the hand-to-hand damage inflicted by the selected unit by 3.",
	L"Increases the hand-to-hand damage inflicted by the selected unit by 6.",
	L"Increases the hand-to-hand damage inflicted by all friendly units by 6.",
	L"Protects the selected unit, reducing damage by 30% received from Water spells.",
	L"Protects the selected unit, reducing damage by 30% received from Water spells.",
	L"Protects the selected unit, reducing damage by 60% received from Water spells.",
	L"Protects all friendly units, reducing damage by 60% received from Water spells.",
	L"Causes the selected enemy unit to inflict minimum damage in combat.",
	L"Causes the selected enemy unit to inflict minimum damage in combat.",
	L"Causes the selected enemy unit to inflict minimum damage in combat.",
	L"Causes all enemy units to inflict minimum damage in combat.",
	L"Blinds a creature so that it cannot move and causes it to counterattack at half its normal attack strength. Blindness persists until the unit is attacked or dispelled.",
	L"Blinds a creature so that it cannot move and causes it to counterattack at half its normal attack strength. Blindness persists until the unit is attacked or dispelled.",
	L"Blinds a creature so that it cannot move and causes it to counterattack at one-quarter normal attack strength. Blindness persists until the unit is attacked or dispelled.",
	L"Blinds a creature so that it cannot move or counterattack. Blindness persists until the unit is attacked or dispelled.",
	L"Reduces the selected enemy unit's attack strength by 3.",
	L"Reduces the selected enemy unit's attack strength by 3.",
	L"Reduces the selected enemy unit's attack strength by 6.",
	L"Reduces attack strength of all enemy units by 6.",
	L"Sends a ripple of death across the battlefield which damages all non-undead units (Power*5).",
	L"Sends a ripple of death across the battlefield which damages all non-undead units (Power*5).",
	L"Sends a ripple of death across the battlefield which damages all non-undead units (Power*7).",
	L"Sends a ripple of death across the battlefield which damages all non-undead units (Power*10).",
	L"Causes the selected target to burst into flames, inflicting fire damage to the target and any adjacent units (Power*15).",
	L"Causes the selected target to burst into flames, inflicting fire damage to the target and any adjacent units (Power*15).",
	L"Causes the selected target to burst into flames, inflicting fire damage to the target and any adjacent units (Power*17).",
	L"Causes the selected target to burst into flames, inflicting fire damage to the target and any adjacent units (Power*20).",
	L"Reduces the luck of the selected enemy unit by 1.",
	L"Reduces the luck of the selected enemy unit by 1.",
	L"Reduces the luck of the selected enemy unit by 2.",
	L"Reduces the luck of all enemy units by 2.",
	L"Re-animates any destroyed undead in the selected group by restoring a fixed number of hit points to the target (Power*40).",
	L"Re-animates any destroyed undead in the selected group by restoring a fixed number of hit points to the target (Power*40).",
	L"Re-animates any destroyed undead in the selected group by restoring a fixed number of hit points to the target (Power*45).",
	L"Re-animates any destroyed undead in the selected group by restoring a fixed number of hit points to the target (Power*50).",
	L"Causes a huge blast of fire to strike the selected target (Power*15). Don't be near this when it goes off!",
	L"Causes a huge blast of fire to strike the selected target (Power*15). Don't be near this when it goes off!",
	L"Causes a huge blast of fire to strike the selected target (Power*17). Don't be near this when it goes off!",
	L"Causes a huge blast of fire to strike the selected target (Power*20). Don't be near this when it goes off!",
	L"Rains fire down upon the battlefield, damaging all units (Power*40).",
	L"Rains fire down upon the battlefield, damaging all units (Power*40).",
	L"Rains fire down upon the battlefield, damaging all units (Power*45).",
	L"Rains fire down upon the battlefield, damaging all units (Power*50).",
	L"Allows you to summon Fire Elementals (Power*3). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Fire Elementals (Power*3). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Fire Elementals (Power*4). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Fire Elementals (Power*5). Once cast, no other elemental types may be summoned.",
	L"Causes the selected unit to inflict maximum damage in combat.",
	L"Causes the selected unit to inflict maximum damage in combat.",
	L"Causes the selected unit to inflict maximum damage in combat.",
	L"Causes all friendly units to inflict maximum damage in combat.",
	L"Protects the selected unit, reducing damage by 30% received from Fire spells.",
	L"Protects the selected unit, reducing damage by 30% received from Fire spells.",
	L"Protects the selected unit, reducing damage by 50% received from Fire spells.",
	L"Protects all friendly units, reducing damage by 50% received from Fire spells.",
	L"Removes all spell effects from the selected friendly unit.",
	L"Removes all spell effects from the selected friendly unit.",
	L"Removes all spell effects from the selected friendly or hostile unit.",
	L"Removes all spell effects from all units on the battlefield.",
	L"Removes all negative spell effects and heals a small number of hit points on the selected unit (Power*5).",
	L"Removes all negative spell effects and heals a small number of hit points on the selected unit (Power*5).",
	L"Removes all negative spell effects and heals a small number of hit points on the selected unit (Power*7).",
	L"Removes all negative spell effects and heals a small number of hit points on all friendly units (Power*7).",
	L"Drains the body heat from the selected enemy unit (Power*20).",
	L"Drains the body heat from the selected enemy unit (Power*20).",
	L"Drains the body heat from the selected enemy unit (Power*22).",
	L"Drains the body heat from the selected enemy unit (Power*25).",
	L"Increases the selected unit's luck by 1.",
	L"Increases the selected unit's luck by 1.",
	L"Increases the selected unit's luck by 2.",
	L"Increases luck of all friendly units by 2.",
	L"Increases the selected unit's morale by 1.",
	L"Increases the selected unit's morale by 1.",
	L"Increases the selected unit's morale by 2.",
	L"Increases morale of all friendly units by 2.",
	L"Drains the body heat of any units adjacent to the target location, without inflicting damage on the target (Power*10).",
	L"Drains the body heat of any units adjacent to the target location, without inflicting damage on the target (Power*10).",
	L"Drains the body heat of any units adjacent to the target location, without inflicting damage on the target (Power*12).",
	L"Drains the body heat of any units adjacent to the target location, without inflicting damage on the target (Power*15).",
	L"Protects the selected unit from all 1-3 level spells.",
	L"Protects the selected unit from all 1-3 level spells.",
	L"Protects the selected unit from all 1-4 level spells.",
	L"Protects the selected unit from all spells.",
	L"Bestows a bonus to the attack strength, defense strength and speed of the selected unit by 2.",
	L"Bestows a bonus to the attack strength, defense strength and speed of the selected unit by 2.",
	L"Bestows a bonus to the attack strength, defense strength and speed of the selected unit by 4.",
	L"Bestows a bonus to the attack strength, defense strength and speed of all friendly units by 4.",
	L"Allows you to summon Water Elementals (Power*3). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Water Elementals (Power*3). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Water Elementals (Power*4). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Water Elementals (Power*5). Once cast, no other elemental types may be summoned.",
	L"Allows you to summon Sprites (Power*5).",
	L"Allows you to summon Sprites (Power*5).",
	L"Allows you to summon Sprites (Power*7).",
	L"Allows you to summon Sprites (Power*10).",
	L"After a generous tip, the barkeep whispers:",
	L"A wise man once said, \"Don't share your wisdom with anybody.\"",
	L"Save before visiting the witch hut!",
	L"Split your archers when fighting other shooters.",
	L"Find the Grail - it is more powerful than you can imagine.",
	L"Always protect your shooters in combat.",
	L"Sometimes the best way to avoid defeat is by avoiding combat!",
	L"Attack where your enemy is weak.",
	L"It's better to take all the hard battles with the main hero.",
	L"Try to foresee enemy moves.",
	L"When travelling across the desert, seek out an oasis, for it will speed your journey.",
	L"There is safety in numbers, especially if those numbers are in the thousands!",
	L"If you have Elves, and the enemy is strong, but slow - don't stand, move around!",
	L"Fight Fire with Protection from Fire.",
	L"Trolls with Stone Skin are one of the most sturdy units!",
	L"Cast \"precision\" & \"bless\" on your archers.",
	L"Use \"stone skin\" on the units that are attacked by towers.",
	L"Black Dragons are the most powerful creatures of the Dungeon.",
	L"Phoenix are the most powerful creatures of the Fortress.",
	L"Low-level units slow you down.",
	L"Hey, I'm all out of rumors, because people like YOU don't come here enough to share them with me!",
	L"Let your Cavaliers run their enemies through. You will like the results. Farther is better.",
	L"I once saw a Dwarf resist a spell cast upon him.",
	L"On the battlefield, the troop who strikes first, wins most often.",
	L"On the battlefield, speed is life, life is speed.",
	L"I have seen dying Vampires reborn in the blood of fallen enemies.",
	L"It is impossible to retaliate in the face of a Vampire's fearsome assault.",
	L"A Lich's attack shreds the living while leaving the dead unscathed.",
	L"On the battlefield, The Plague strike fear into the hearts of their enemies.",
	L"Golems do not have a mind of their own.",
	L"Don't ever try to cross the moat with a foot unit.",
	L"The Armageddon and dragons is a deadly combination.",
	L"Thors will strike Dragons with more ferocity than any other enemy.",
	L"Many fear the petrifying attack of the Medusa. You should fear more their golden arrows.",
	L"Even against overwhelming odds, the Minotaur revels in the bloodlust of combat.",
	L"Logistics and Scouting are crucial.",
	L"Try not to buy useless armies.",
	L"It is impossible to retaliate in the onslaught of the many headed Hydra.",
	L"Some believe each Necropolis builds a \"Necromancy Amplifier\" to help its heroes raise the dead.",
	L"Heroes visiting the Hall of Valhalla in a Stronghold become better warriors.",
	L"Join",
	L"Create",
	L"Launch!",
	L"Ready",
	L"Profile...",
	L"Failure",
	L"Failed connecting. Please try again later",
	L"Player dropped",
	L"%s player dropped and was replaced with computer player.",
	L"Game dropped",
	L"Host decided to drop the game.",
	L"Unable to log in",
	L"User ID invalid.",
	L"You are participating in a game",
	L"Do you want to resume it?",
	L"Game doesn't exist anymore.",
	L"Game full.",
	L"Unable to join",
	L"Unable to create",
	L"Game you were participating in was terminated.",
	L"Uploading savegame...",
	L"Downloading savegame",
	L"Connecting to server...",
	L"Network unavailable",
	L"Players in lobby",
	L"Human player jumped in",
	L"Unable to launch game, please wait for more players to join.",
	L"%s player (AI) was replaced by human player %s.",
	L"Checking for updates...",
	L"Update available",
	L"Would you like to update now?",
	L"Updating...",
	L"The game will now restart to complete update process",
	L"You are defeated!",
	L"Do you wish to stay in the game as an observer?",
	L"Are you sure you want to permanently kick %s?",
	L"You have been kicked by host.",
	L"Quick load",
	L"Quick save",
	L"End turn (E)",
	L"Confirm hero path (Space)",
	L"Next hero (Tab)",
	L"Enter the game menu (Esc)",
	L"Toggle the minimap (M)",
	L"Open the currently selected hero (Enter)",
	L"Open the currently selected castle (Enter)",
	L"Exit (Esc)",
	L"Cast spell (C)",
	L"Market",
	L"Magic",
	L"Tavern",
	L"Build",
	L"Recruit",
	L"Dismiss",
	L"Dig",
	L"Puzzle",
	L"Cast",
	L"Don't show again",
	L"Use your finger to scroll map and tap to set path for active Hero. Try to explore some now!",
	L"You have tried to set path to an unreachable area possibly blocked by an obstacle. Try another location.",
	L"You have just picked up an object. Objects picked up this way disappear forever.",
	L"You have entered a visitable construction. Many of them give visiting hero some bonuses or extra powers",
	L"You have possesed an ownerable construction. Note your flag on top of it. Many of them give you treasure each new day.",
	L"You have entered a castle screen. You can build new structures, recruit heroes, hire creatures and improve your magic skills here. Use left/right finger swipe to change castle screens, and up swipe to exit castle.",
	L"On the Building screen you can construct new buildings. Tap a building to begin. Red buildings are unavailable for construction at the moment. You may need to find required resources first. You can only constuct one building per castle once a day.",
	L"On the Recruit screen you can hire creatures for your army. Select a creature type on top, then choose a desired amount and click recruit button. There is also a garrison army slots you can fill in with castle defenders. ",
	L"On the Tavern screen you can recruit a hero once per week and buy a ship in case your castle is situated near water.",
	L"On the Mage Guild screen you can view spells available in all your magic guilds. Each castle has unique set of spells of levels 1 to 5. Open new spells by upgrading your Magic Guild.",
	L"On the Marketplace screen you can exchange one resource type to another. Select what to exchange on the left and the desired resource on the right. Please note that exchange rate is more pleasant more Marketplaces you have.",
	L"You have entered a Hero screen. Here you can watch your Hero's progress in various skills, view his Morale and Luck, select what artifacts to wear and view what magic spells you possess. Use your finger to swipe screens left or right or swipe up to exit the screen.",
	L"On Hero Stats screen you can view you Hero's experience, strength, luck and other parameters. Touch an icon to learn more.",
	L"On this screen you can move your Artifacts around, wearing them or putting into the backpack. Only worn artifacts give your Hero bonuses.",
	L"On the Spellbook screen you can view and learn about different spells this Hero can cast. Tap a spell icon to learn more.",
	L"Two Heroes have just met! You can move around armies and artifacts between them. Swipe up to exit this screen.",
	L"On Army screen you can move creatures groups between those two heroes",
	L"On Artifacts screen you can transfers artifacts between Heroes' backpacks",
	L"A battle has just begun! It is turn-based, each creature stack moving and taking actions strictly in order. Tap the battlefield to move, tap enemy creatures to attack. Many of creatures possess special abilities like flying and shooting. You can use magic spells by tapping the Spellbook button. Use the Info button to learn about combatants.",
	L"You have no more energy to move today. Press the flashing End Turn button to proceed to next day.",
	L"On the left side there is a Hero and Castle choose button. Use it to quickly navigate between your Heroes and Castles.",
	L"On your lower left there is a minimap button allowing you to quickly navigate the map.",
	L"Under the hero and castle select button there is an Info button, allowing you to inspect objects on the map. Press it and move your finger around to learn about objects. Press it again to exit Info mode.",
	L"Tap the destination again to start moving",
	L"You have just hired another hero! You can freely switch between them using the Hero/Castle select button on the left side and explore the world independently!",
	L"Quickly double tap a Castle to enter it. You can also double tap a Hero to learn about his skills.",
	L"The Horse button on your right allows you to quickly confirm selected Hero's path or center the screen on the Hero if no path is selected",
	L"You now have a Castle selected. To quickly enter it, press the Castle icon in the upper left corner. To return to your Hero press Select Hero or Castle button on the left side.",
	L"This hero is too tired to move further today. The remaining path is shown in red. That means you can continue your journey after rest. To skip turn press End Turn button in the lower right.",
	L"Use your Heroes to explore the world and to defeat neutral creatures and enemy Heroes. Your Castles are places where you recruit more forces and Heroes, plan your assaults and defences. You can capture more Castles and recruit more Heroes as you play. Your Heroes will gain experience and more powers over time.",
	L"Press Info (I) button and tap any combatant to learn about him. Press the Info button again to exit information mode.",
	L"Defend button skips turn turn for the currently active creature stack and gives it a temporary defence bonus",
	L"Wait button moves currently active creature stack to the end of current turn queue",
	L"Select a spell, than select and confirm target to cast it. Valid targets are highlighted with green.",
	L"Don't show again",
	L"Click and drag anywhere to scroll the map. Click to set movement destination. Try to explore some now!",
	L"You have tried to set path to an unreachable area possibly blocked by an obstacle. Try another location.",
	L"You have just picked up an object. Objects picked up this way disappear forever.",
	L"You have entered a visitable construction. Many of them give visiting hero some bonuses or extra powers.",
	L"You have \u0443\u0442\u0435\u0443\u043A\u0443\u0432 an ownerable construction. Note your flag on top of it. Many of them give you treasure each new day.",
	L"You have entered a castle screen. You can build new structures, recruit heroes, hire creatures and improve your magic skills here (B, T, R, M, S).",
	L"On the Building screen you can construct new buildings. Tap a building to begin. Red buildings are unavailable for construction at the moment. You may need to find required resources first. You can only constuct one building per castle once a day.",
	L"On the Recruit screen you can hire creatures for your army. Select a creature type on top, then choose a desired amount and click recruit button. There is also a garrison army slots you can fill in with castle defenders. ",
	L"On the Tavern screen you can recruit a hero once per week and buy a ship in case your castle is situated near water.",
	L"On the Mage Guild screen you can view spells available in all your magic guilds. Each castle has unique set of spells of levels 1 to 5. Open new spells by upgrading your Magic Guild.",
	L"On the Marketplace screen you can exchange one resource type to another. Select what to exchange on the left and the desired resource on the right. Please note that exchange rate is more pleasant more Marketplaces you have.",
	L"You have entered a Hero screen. Here you can watch your Hero's progress in various skills, view his Morale and Luck, select what artifacts to wear and view what magic spells you possess.",
	L"On the Spellbook screen you can view and learn about different spells this Hero can cast. Tap a spell icon to learn more.",
	L"Two Heroes have just met! You can move around armies and artifacts between them.",
	L"A battle has just begun! It is turn-based, each creature stack moving and taking actions strictly in order. Click on the battlefield to move, click on the enemy creatures to attack. Many of creatures possess special abilities like flying and shooting. You can use magic spells by using the Spellbook button. Use right mouse button to learn about combatants.",
	L"You have no more energy to move today. Press the flashing End Turn button to proceed to next day.",
	L"On the right side there is a Hero and Castle choose button. Use it to quickly navigate between your Heroes and Castles. You can also use the TAB button",
	L"When you move the mouse over any object on the map, you can see its details in the info window on the panel below.",
	L"Click the destination again to start moving",
	L"You have just hired another hero! You can freely switch between them using the Hero/Castle select button on the right side and explore the world independently!",
	L"Quickly double click a Castle to enter it. You can also double click a Hero to learn about his skills.",
	L"The Horse button on your right allows you to quickly confirm selected Hero's path or center the screen on the Hero if no path is selected. You can also use the SPACE key.",
	L"You now have a Castle selected. To quickly enter it, press the Castle icon in the panel below. To return to your Hero press Select Hero or Castle button on the right side (also TAB key).",
	L"This hero is too tired to move further today. The remaining path is shown in red. That means you can continue your journey after rest. To skip turn press End Turn button in the lower right (or press E).",
	L"Use your Heroes to explore the world and to defeat neutral creatures and enemy Heroes. Your Castles are places where you recruit more forces and Heroes, plan your assaults and defences. You can capture more Castles and recruit more Heroes as you play. Your Heroes will gain experience and more powers over time.",
	L"Press the right mouse button button on any creature to learn about it.",
	L"Defend button (D) skips turn turn for the currently active creature stack and gives it a temporary defence bonus",
	L"Wait button (W) moves currently active creature stack to the end of current turn queue",
	L"Select a spell, than select and confirm target to cast it. Valid targets are highlighted with green."};
