#include "stdafx.h"
#include "cnst_text.h" 

LPCWSTR LANG_DATA_GER[2184] = {
	L"Tutorial Anleitung zeigen?",
	L"",
	L"+",
	L"-",
	L"Ok",
	L"Abbruch",
	L"Ja",
	L"Nein",
	L"Neustart",
	L"n/a",
	L"Schliessen",
	L"Hilfe",
	L"Beschw\u00F6ren",
	L"Info",
	L"Kartengr\u00F6\u00DFe",
	L"Kartenversion",
	L"Autor",
	L"Entlassen",
	L"Bauen",
	L"Board Ship",
	L"Rekrutieren",
	L"Ben\u00F6tigt:",
	L"Kosten:",
	L"Wache:",
	L"Bereits Besucht",
	L"Nicht Besucht",
	L"Besitzer",
	L"Niemand",
	L"Teilen",
	L"Handeln",
	L"Kapitulieren",
	L"R\u00FCckzug",
	L"Laden",
	L"Speichern",
	L"<...>",
	L"Lade ein gespeichertes Spiel:",
	L"Speichere das aktuelle Spiel",
	L"W\u00E4hle das Spielszenario:",
	L"Sieg",
	L"WUNDERBAR!",
	L"Niederlage",
	L"TRAGISCHE NIEDERLAGE",
	L"Kartenname",
	L"Autokampf",
	L"Melee:",
	L"Shoot:",
	L"\u00DCberblick K\u00F6nigreich",
	L"Kartenteile",
	L"System Men\u00FC",
	L"T\u00E4gliches Einkommen:",
	L"Unerforschtes Gebiet",
	L"Unbesetzt",
	L"Kein Gasthaus",
	L"Bestimmungsort w\u00E4hlen",
	L"Select a Castle to retreat",
	L"Wachstum",
	L"Verf\u00FCgbar",
	L"Kosten pro Einheit",
	L"Rekrutieren",
	L"Gesamtkosten",
	L"Mana",
	L"Stufe",
	L"Lvl",
	L"Erfahrung",
	L"Reise Punkte",
	L"Wachen zur\u00FCcklassen",
	L"Choose units to defend castle with (first line)",
	L"Speichern unter",
	L"Spiel Datum",
	L"Rohstoffe K\u00F6nigreich",
	L"Verf\u00FCgbar zum Handel",
	L"Upgrade creatures",
	L"Auf einer Lichtung sehen SIe ein antikes Artefakt. Ungl\u00FCcklicherweise wird es bewacht von:",
	L"Best\u00FCrzt stellen Sie fest, das %s ist bewacht von:",
	L"Wollen Sie die Wachen bek\u00E4mpfen?",
	L"Registrierung",
	L"Ger\u00E4te ID:",
	L"Registrierungsschl\u00FCssel",
	L"Registrieren",
	L"Sp\u00E4ter",
	L"Registrierung erfolgreich",
	L"Registrierung fehlgeschlagen",
	L"Der angegebene Registrierungsschl\u00FCssel ist ung\u00FCltig.",
	L"Vielen Dank!",
	L"Besuche unsere offizielle Webseite www.palmheroes.com um das Spiel zu kaufen.",
	L"",
	L"Durch den Erwerb von Pocket Heroes von #FCCCN #FFF6Handango#FCCC bekommen Sie einen Registrierungsschl\u00FCssel. Bitte aktivieren Sie Ihre Kopie von Pocket Heroes unter: www.pocketheroes.org",
	L"Mehr Karten",
	L"Musik",
	L"Aus",
	L"Tasten",
	L"Spezielle Tastaturbelegung",
	L"Spiel Sprache",
	L"Dr\u00FCcken Sie die Taste, die Sie zuordnen wollen ...",
	L"- N/A -",
	L"Start",
	L"Hoch",
	L"Runter",
	L"Links",
	L"Rechts",
	L"Taste #1",
	L"Taste #2",
	L"Taste #3",
	L"Taste #4",
	L"Taste #5",
	L"Taste #6",
	L"Aufzeichnen",
	L"Sprechen",
	L"Ende",
	L"Zur\u00FCck",
	L"Men\u00FC",
	L"Soft #1",
	L"Soft #2",
	L"Hilfe Modus",
	L"Benutzerdefiniert",
	L"\u00DCbersichtskarte",
	L"Minimieren",
	L"Screenshot erstellen",
	L"Quicksave",
	L"Heldenerinnerung",
	L"Raster auf Karte",
	L"Kampfraster anzeigen",
	L"Schneller Kampf",
	L"Bewegungspunkte anzeigen",
	L"\u00DCbersichtskarte gl\u00E4tten",
	L"\u00DCbersichtskarte 4x verkleinen",
	L"Linksh\u00E4nder Modus",
	L"Autospeicher",
	L"Autozoom On Hold",
	L"Expert Kampf",
	L"Sfx Lautst\u00E4rke",
	L"Musik Lautst\u00E4rke",
	L"Gammawertanzeige",
	L"Karte scrollen",
	L"Geschwindigkeit des Helden",
	L"Kampfgeschwindigkeit",
	L"Sticky path",
	L"One-handed mode",
	L"Sehr Langsam",
	L"Langsam",
	L"Normal",
	L"Schnell",
	L"Sehr Schnell",
	L"Jan",
	L"Feb",
	L"M\u00E4r",
	L"Apr",
	L"Mai",
	L"Jun",
	L"Jul",
	L"Aug",
	L"Sep",
	L"Okt",
	L"Nov",
	L"Dez",
	L"Ihr aktuelles Spiel geht verloren. Sind Sie sicher, dass Sie ein anderes Spiel laden m\u00F6chten?",
	L"Ihr aktuelles Spiel geht verloren. Sind Sie sicher, dass Sie ein neues Szenario beginnen m\u00F6chten?",
	L"Sind Sie sicher das Sie das Spiel beenden m\u00F6chten?",
	L"Ihr aktuelles Spiel geht verloren. Sind Sie sicher, dass Sie ins Hauptmen\u00FC wechseln m\u00F6chten?",
	L"Der ausgew\u00E4hlte Speicherplatz ist bereits in Verwendung. M\u00F6chten Sie ihn \u00DCberschreiben?",
	L"Spiel gespeichert...",
	L"Unable To Save",
	L"No more space: choose existing slot!",
	L"Screenshot gespeichert...",
	L"Entschuldigung - Diese Funktion ist in der aktuellen Version nicht verf\u00FCgbar.",
	L"Sie haben gewonnen!",
	L"Hat Stufe %d erreicht",
	L"This is maximum level allowed for this scenario.",
	L"#FFFF%s #S0#FDDD(%s Stufe %d)",
	L"Alle Bedingungen f\u00FCr dieses Geb\u00E4ude sind erf\u00FCllt",
	L"Bereits gebaut",
	L"Sind Sie sicher, dass Sie diese Armee entlassen m\u00F6chten?",
	L"Sind Sie sicher, dass Sie diesen Held entlassen m\u00F6chten?",
	L"Eine Gruppe %s mit dem Bestreben nach gr\u00F6sserem Ruhm m\u00F6chte sich Ihnen anschliessen. Sind Sie einverstanden?",
	L"Von der St\u00E4rke unserer Streitkr\u00E4fte beeindruckt, fliehen die %s. Wollen Sie sie verfolgen und stellen?",
	L"Zusatzfertigkeiten:",
	L"Ihr Held hat erlernt:",
	L"Was w\u00E4hlen Sie?",
	L"Schaffe f\u00FCr die %s Platz in Ihrer Armee.",
	L"Choose a unit to resurrect:",
	L"%s behauptet:",
	L"Ich nehme Ihre Kapitulation an und gew\u00E4hre Ihnen und Ihrer Armee sicheres Geleit f\u00FCr den Preis von %d Gold.",
	L"Sie brauchen %d Erfahrungspunkte, um die n\u00E4chste Stufe zu erreichen.",
	L"%s Spieler wurde besiegt!",
	L"In der Armee ist kein Platz f\u00FCr diese Einheit.",
	L"Sind Sie sicher, dass Sie diese Runde beenden m\u00F6chten?",
	L"Schauen Sie sich unsere feine Ware an. Wenn Sie etwas kaufen m\u00F6chten, w\u00E4hlen die Ware aus.",
	L"Ich biete Ihnen an :",
	L"%s   f\u00FCr   %s",
	L"No ships are available. Try building one next week.",
	L"This ship is occupied and is already sailing off.",
	L"Build New Ship",
	L"Board Ship",
	L"Sie haben bereits vier Helden.",
	L"Es gibt keine Helden in der Taverne zum rekrutieren. Komme n\u00E4chste Woche wieder.",
	L"Dieser Zauber hat keinen Effekt!",
	L"Choose target: ",
	L"Nicht genug Mana, um diesen Zauber zu beschw\u00F6ren.",
	L"Dieser Zauber ben\u00F6tigt %s Erfahrungspunkte auf Stufe %s.",
	L"%d Punkte Schaden",
	L"Diese Kreaturen sind bereit, sich uns anzuschliessen!",
	L"Diese schwachen Kreaturen werden mit Sicherheit fliehen.",
	L"Ich f\u00FCrchte diese Kreaturen sind bereit f\u00FCr einen Kampf.",
	L"Keinen Zauber ausgew\u00E4hlt",
	L"Ihr Held ist zu m\u00FCde, um zu zaubern. Versuche es morgen nochmal.",
	L"Ben\u00F6tigt Held mit Stufe %d und Geschicklichkeit %s.",
	L"Ben\u00F6tigt Held mit Stufe %d.",
	L"Ben\u00F6tigt Held mit %s Geschicklichkeit.",
	L"Spieler %s ist am  Zug.",
	L"Spieler %s wird angegriffen!",
	L"Sie h\u00E4tten es besser wissen sollen - Sie warden angegriffen!",
	L"Das Graben nach Artefakten dauert einen ganzen Tag. Versuche es morgen nochmal.",
	L"Versuche es auf freier Ebene.",
	L"Gl\u00FCckw\u00FCnsch! Nachdem er viele Stunden hier gegraben hatte, hat Ihr Held die Krone des Eroberers gefunden.",
	L"Hier ist nichts. Wo k\u00F6nnte es sein?",
	L"Es gibt sieben verschiedene Ressourcen in Palm Heroes, die ben\u00F6tigt werden, um Burgen zu bauen und zu verbessern, Truppen aufzubauen und Helden zu rekrutieren. Gold ist die wichtigste von ihnen und wird f\u00FCr nahezu alles ben\u00F6tigt. Holz und Erz braucht man f\u00FCr die meisten Geb\u00E4ude. Edelsteine, Quecksilber, Schwefel und Kristalle sind seltene magische Ressourcen, die f\u00FCr die m\u00E4chtigsten Kreaturen und Geb\u00E4ude ben\u00F6tigt werden.",
	L"Erfahrung wird ben\u00F6tigt, um in h\u00F6here Stufen aufzusteigen und so die Fertigkeiten des Helden zu verbessern.",
	L"Mana (Zauberpunkte) wird ben\u00F6tigt, um Zauber zu beschw\u00F6ren. Die maximale Manastufe ist zehnmal so hoch wie die Fertigkeit Wissen. Auftretende Ereignisse und Strukturen k\u00F6nnen die Manastufe zeitweise erh\u00F6hen.",
	L"Bewegungspunkte legen fest, wie weit sich Ihr Held jeden Tag bewegen kann. Die Strecke wird nach der Art des Gel\u00E4ndes, der Stra\u00DFen und der H\u00F6he Ihrer Fertigkeiten in Logistik und Pfadfinden berechnet. Spezielle F\u00E4lle, Ereignisse und Artefakte k\u00F6nnen die Zahl der Bewegungspunkte erh\u00F6hen.",
	L"Die Fertigkeit Angriff ist ein Bonus, der zum Angriffswert jeder Truppe Ihres Helden addiert wird. Sie k\u00F6nnen so mehr Schaden im Kampf verursachen.",
	L"Die Fertigkeit Verteidigung ist ein Bonus, der zu dem Verteidigungswert jeder Truppe Ihres Helden addiert wird. Sie k\u00F6nnen so mehr Schaden im Kampf abwehren. ",
	L"Zauberkraft legt die Dauer oder die St\u00E4rke eines Zaubers fest.",
	L"Die Fertigkeit Wissen legt die Zahl der Manapunkte Ihres Helden fest. Unter normalen Umst\u00E4nden wird ein Held auf 10 Zauberpunkte pro Stufe dieser Fertigkeit begrenzt.",
	L"Viel Gl\u00FCck erlaubt es Ihren Truppen den doppelten Schaden im Kampf zu verursachen.",
	L"Mit neutralem Gl\u00FCck bleiben die Angriffe Ihrer Truppen unbeeinflu\u00DFt.",
	L"Ungl\u00FCck reduziert bei den betreffenden Einheiten den Angriffsschaden um die H\u00E4lfte.",
	L"Hohe Moral kann extra Angriffe bei den betreffenden Einheiten ausl\u00F6sen.",
	L"Bei neutraler Moral wird Ihre Armee nicht vor Angst erstarren. Allerdings wird sie auch keine Extra Angriffe durchf\u00FChren.",
	L"Schlechte Moral kann zur Folge haben, dass Ihre Truppen im Kampf gelegentlich aussetzen m\u00FCssen.",
	L"Das Zur\u00FCcksetzen des Highscores l\u00F6scht alles, was Sie bisher erreicht haben. Sind Sie sicher, dass Sie das machen m\u00F6chten?",
	L"",
	L"",
	L"",
	L"Neue Woche",
	L"Neuer Monat",
	L"Astrologen sagen den Monat der/des %s vorraus.",
	L"Astrologen sagen den Monat der PEST vorraus!",
	L"Astrologen sagen die Woche der/des %s vorraus.",
	L"Alle Geb\u00E4ude haben Bev\u00F6lkerungszuwachs.",
	L"Die Bev\u00F6lkerung wurde halbiert.",
	L"%s Bev\u00F6lkerung verdoppelt!",
	L"%s Wachstum +5.",
	L"Eichh\u00F6rnchens",
	L"Hasen",
	L"Erdh\u00F6rnchens",
	L"Dachses",
	L"Ratten",
	L"Adler",
	L"Wiesels",
	L"Raben",
	L"Mungos",
	L"Hunde",
	L"Erdferkel",
	L"Eisechsen",
	L"Schildkr\u00F6te",
	L"Igel",
	L"Kondore",
	L"Grash\u00FCpfers",
	L"Ameisen",
	L"Mummy",
	L"Spinnen",
	L"Schmetterlings",
	L"Hummeln",
	L"Heuschrecken",
	L"Regenwurms",
	L"Wespen",
	L"K\u00E4fer",
	L"Schlachtfeld Opfer",
	L"Angreifer",
	L"Verteidiger",
	L"Kampfprotokoll",
	L"Hohe Moral erlaubt %s noch einmal anzugreifen.",
	L"Niedrige Moral veranla\u00DFt %s,  vor Panik zu erstarren.",
	L"Viel Gl\u00FCck gl\u00E4nzt auf %s",
	L"Ungl\u00FCck steigt auf %s herab",
	L"Runde %d",
	L"Angriff %s",
	L"Schuss %s",
	L" (%d Schaden)",
	L" (%d-%d Schaden)",
	L"%s haben %d Schaden erzeugt.",
	L"%d %s wurden besiegt.",
	L"%s pausieren und warten auf einen besseren Zeitpunkt um in Aktion zu treten.",
	L"%s nehmen eine defensive Position ein und gewinnen +%d Verteidigungsfertigkeit. ",
	L"Der Gefechtsturm macht %d Schaden.",
	L"Der Burggraben macht %d Schaden.",
	L"%s vernichten die H\u00E4lfte der feindlichem Truppen.",
	L"Beschw\u00F6re %s",
	L"Beschw\u00F6re %s zu %s.",
	L"%s beschw\u00F6rt %s.",
	L"%s beschw\u00F6rt %s zu %s.",
	L"Dieser %s Zauber macht %d Schaden.",
	L"Die %s widerstehen diesem Zauber",
	L"Sie haben ein feindlicher Artefakt erobert!",
	L"Sie haben %d feindliche Artefakte erobert!",
	L"Ein glorreicher Sieg!",
	L"Der Feind ist geflohen!",
	L"Der Feind hat kapituliert",
	L"F\u00FCr Heldenmut im Kampf, erh\u00E4lt %s %d Erfahrungspunkte.",
	L"Ihre Streitkr\u00E4fte erleiden eine bittere Niederlage, %s gibt sein Vorhaben auf.",
	L"Ihre Streitkr\u00E4fte erleiden eine bittere Niederlage,",
	L"Die feigen %s fliehen vor diesem Kampf.",
	L"%s kapituliert vor dem Feind und flieht in Schande.",
	L"%s setzt die Sph\u00E4re der Negation ein. Ein altes Artefakt, dass das Beschw\u00F6ren magischer Zauber verhindert.",
	L"%s beschw\u00F6rt den Fu\u00DFfesseln-des-Kriegers-Zauber. Sie k\u00F6nnen nicht fliehen oder kapitulieren!",
	L"Sie haben nicht genug Gold",
	L"\u00DCbe die dunklen K\u00FCnste der Totenbeschw\u00F6rung aus und Sie sind in der Lage, %d der get\u00F6teten Feinde als Skelette unter Ihrer F\u00FChrung auferstehen zu lassen...",
	L"Klein",
	L"Medium",
	L"Gro\u00DF",
	L"Extra Gro\u00DF",
	L"S",
	L"M",
	L"L",
	L"XL",
	L"Rang",
	L"Land",
	L"Datum",
	L"Tage",
	L"Punkte",
	L"Schwierigkeitsgrad",
	L"Einfach",
	L"Normal",
	L"Schwer",
	L"Experte",
	L"Unm\u00F6glich",
	L"Voraussetzung f\u00FCr Sieg",
	L"Alle Opponente besiegen",
	L"Held %s besiegen",
	L"Schlo\u00DF %s besiegen",
	L"%d Tage \u00FCberleben",
	L"%d %s finden",
	L"Artefakt %s finden",
	L"%d %s rekrutieren",
	L"Zauber %s lernen",
	L"Krone des Eroberers finden",
	L"Sie haben besiegt!",
	L"Sieg! Alle Feinde sind besiegt!",
	L"Sieg! Der feindliche Held ist besiegt!",
	L"Sieg! Der feindliche Schlos\u00DF ist besiegt!",
	L"Sieg! Sie haben die abgefordete Zeit \u00FCberlebt!",
	L"Sieg! Sie haben die abgefordete Minerale gefunden!",
	L"Sieg! Sie haben den Artefakt gefunden!",
	L"Sieg! Sie haben alle agbef\u00F6rdete Monstern rekrutiert!",
	L"Sieg! Sie haben den abgef\u00F6rdeten Zauber gelernt!",
	L"Sieg! Sie haben die Krone des Eroberers gefunden!",
	L"Voraussetzung f\u00FCr Niederlage",
	L"Keine spezielle Voraussetzung",
	L"Den Held %s verlieren",
	L"Den Schlo\u00DF %s verlieren",
	L"Sie haben verloren...",
	L"Alle Ihre Helden und Schlo\u00DFen sind verloren!",
	L"Ihr Held ist verloren!",
	L"Ihr Schlo\u00DF ist verloren!",
	L"Jemand anderer had die Voraussetzung erf\u00FCllt!",
	L"Sie haben die Voraussetzung zur Zeit nicht erf\u00FCllt!",
	L"Ein Spieler",
	L"Neues Spiel Starten",
	L"Neues Spiel",
	L"New Random Map",
	L"Multiplayer",
	L"Online Spiel",
	L"Hilfe",
	L"Anleitung",
	L"Laden",
	L"Speichern",
	L"Ruhmeshalle",
	L"Autoren",
	L"Einstellungen",
	L"Scenario Neu Starten",
	L"Hauptmen\u00FC",
	L"Beenden",
	L"Zur\u00FCck zum Spiel",
	L"Hot-Seat",
	L"Scenarios Laden",
	L"Name",
	L"Gr\u00F6\u00DFe",
	L"Autor",
	L"Gespielt",
	L"Rating",
	L"Humans",
	L"Name",
	L"Datum",
	L"Fortgang",
	L"Gr\u00F6\u00DFe",
	L"MAPS",
	L"Abenteuer",
	L"Aktion",
	L"Hot-Seat",
	L"Alle",
	L"Back",
	L"Download",
	L"ZUM SPIEL!",
	L"Updating map list, please wait...",
	L"Map list update failed, try again later.",
	L"Processing your download, please wait...",
	L"Sorry, download failed.",
	L"Sorry, you have no network connection.",
	L"You have successfully downloaded an item!",
	L"The purchases have been disabled in Settings.",
	L"Restore your purchases",
	L"Restoring purchases...",
	L"Free",
	L"Update for free",
	L"HOT NEW",
	L"Price",
	L"Updates",
	L"Anzahl St\u00E4dte",
	L"Anzahl Helden",
	L"Ressourcen",
	L"gefundene Obelisken",
	L"Artefakte",
	L"Armeest\u00E4rke",
	L"Einkommen",
	L"Wasser",
	L"Strand",
	L"Dreck",
	L"Gras",
	L"Sumpf",
	L"Lava",
	L"\u00D6dland",
	L"W\u00FCste",
	L"Schnee",
	L"W\u00FCste",
	L"Weg",
	L"\u00D6dland",
	L"K\u00FCste",
	L"See",
	L"Spieler",
	L"Spieler",
	L"Rot",
	L"Gr\u00FCn",
	L"Blau",
	L"T\u00FCrkis",
	L"Lila",
	L"Gelb",
	L"Orange",
	L"Rot",
	L"Gr\u00FCn",
	L"Blau",
	L"T\u00FCrkis",
	L"Lila",
	L"Gelb",
	L"Orange",
	L"Undefiniert",
	L"Mensch",
	L"Computer",
	L"Nur Menschen",
	L"Nur Computer",
	L"Mensch oder Computer",
	L"Datum",
	L"Monat",
	L"Woche",
	L"Tag",
	L"M",
	L"W",
	L"T",
	L"Angriff",
	L"Verteidigung",
	L"Zauberkraft",
	L"Wissen",
	L"Sch\u00FCsse",
	L"Schaden",
	L"Gesundheit",
	L"Geschwindigkeit",
	L"Anzahl",
	L"Moral",
	L"Gl\u00FCck",
	L"Angriffslevel",
	L"Verteidigungslevel",
	L"Zauberkraft",
	L"Wissen",
	L"Sch\u00FCsse",
	L"Schaden",
	L"Gesundheit",
	L"Geschwindigkeit",
	L"Anzahl",
	L"Moral",
	L"Gl\u00FCck",
	L"Grundbesitz",
	L"F\u00FChrung",
	L"Gl\u00FCck",
	L"Diplomatie",
	L"Luftmagie",
	L"Erdmagie",
	L"Feuermagie",
	L"Wassermagie",
	L"Wissen",
	L"Totenbeschw\u00F6rung",
	L"Mystik",
	L"Intelligenz",
	L"Resistenz",
	L"Zauberei",
	L"Lernen",
	L"Kundschaften",
	L"Logistik",
	L"Pfadfinden",
	L"Fernkampf",
	L"Ballistik",
	L"Angriff",
	L"R\u00FCstung",
	L"Der Held steuert 250 Gold pro Tag zum Einkommen bei.",
	L"Der Held steuert 500 Gold pro Tag zum Einkommen bei.",
	L"Der Held steuert 1000 Gold pro Tag zum Einkommen bei.",
	L"Steigert die Moral der Truppen des Helden um 1.",
	L"Steigert die Moral der Truppen des Helden um 2.",
	L"Steigert die Moral der Truppen des Helden um 3.",
	L"Steigert das Gl\u00FCck des Helden um 1.",
	L"Steigert das Gl\u00FCck des Helden um 2.",
	L"Steigert das Gl\u00FCck des Helden um 3.",
	L"Erlaubt Ihnen mit Monstern die schw\u00E4cher sind als Ihre Gruppe zu verhandeln und verringert die Kosten der Kapitulation um 20%.",
	L"Erlaubt Ihnen, mit Monstern die schw\u00E4cher sind als Ihre Gruppe zu verhandeln und verringert die Kosten der Kapitulation um 40%.",
	L"Erlaubt Ihnen, mit Monstern die schw\u00E4cher sind als Ihre Gruppe zu verhandeln und verringert die Kosten der Kapitulation um 60%.",
	L"Einfache Luftmagie erlaubt Ihrem Helden Luft-Magie-Zauber mit reduzierten Kosten zu beschw\u00F6ren.",
	L"Fortgeschrittene Luftmagie erlaubt Ihrem Helden Luft-Magie-Zauber mit reduzierten Kosten und erh\u00F6hter Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Experten Luftmagie erlaubt Ihrem Helden Luft-Magie-Zauber mit reduzierten Kosten und maximaler Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Einfache Erdmagie erlaubt Ihrem Helden Erd-Magie-Zauber mit reduzierten Kosten zu beschw\u00F6ren.",
	L"Fortgeschrittene Erdmagie erlaubt Ihrem Helden Erd-Magie-Zauber mit reduzierten Kosten und erh\u00F6hter Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Experten Erdmagie erlaubt Ihrem Helden Erd-Magie-Zauber mit reduzierten Kosten und maximaler Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Einfache Feuermagie erlaubt Ihrem Helden Feuer-Magie-Zauber mit reduzierten Kosten zu beschw\u00F6ren.",
	L"Fortgeschrittene Feuermagie erlaubt Ihrem Helden Feuer-Magie-Zauber mit reduzierten Kosten und erh\u00F6hter Effektivit\u00E4t zu beschw\u00F6ren",
	L"Experten Feuermagie erlaubt Ihrem Helden Feuer-Magie-Zauber mit reduzierten Kosten und maximaler Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Einfache Wassermagie erlaubt Ihrem Helden Wasser-Magie-Zauber mit reduzierten Kosten zu beschw\u00F6ren.",
	L"Fortgeschrittene Wassermagie erlaubt Ihrem Helden Wasser-Magie-Zauber mit reduzierten Kosten und erh\u00F6hter Effektivit\u00E4t zu beschw\u00F6ren",
	L"Experten Wassermagie erlaubt Ihrem Helden Wasser-Magie-Zauber mit reduzierten Kosten und maximaler Effektivit\u00E4t zu beschw\u00F6ren.",
	L"Erlaubt dem Helden Zauber der Sufe 3 zu erlernen.",
	L"Erlaubt dem Helden Zauber der Sufe 4 zu erlernen.",
	L"Erlaubt dem Helden Zauber der Sufe 5 zu erlernen.",
	L"Erlaubt 10% der im Kampf get\u00F6teten Kreaturen als Skelette von den Toten zu erwecken.",
	L"Erlaubt 20% der im Kampf get\u00F6teten Kreaturen als Skelette von den Toten zu erwecken.",
	L"Erlaubt 30% der im Kampf get\u00F6teten Kreaturen als Skelette von den Toten zu erwecken.",
	L"Erlaubt dem Helden 2 Zauberpunkte pro Tag zu regenerieren.",
	L"Erlaubt dem Helden 4 Zauberpunkte pro Tag zu regenerieren.",
	L"Erlaubt dem Helden 6 Zauberpunkte pro Tag zu regenerieren.",
	L"Steigert das Maximum der normalen Zauberpunkte des Helden um 25%.",
	L"Steigert das Maximum der normalen Zauberpunkte des Helden um 50%.",
	L"Verdoppelt das Maximum der normalen Zauberpunkte des Helden.",
	L"Stattet die Truppen eines Heldes mit 5% magischem Widerstand aus.",
	L"Stattet die Truppen eines Heldes mit 10% magischem Widerstand aus.",
	L"Stattet die Truppen eines Heldes mit 20% magischem Widerstand aus.",
	L"Verursacht bei einem Zauber einen zus\u00E4tzlichen Schaden von 5%.",
	L"Verursacht bei einem Zauber einen zus\u00E4tzlichen Schaden von 10%.",
	L"Verursacht bei einem Zauber einen zus\u00E4tzlichen Schaden von 15%.",
	L"Steigert die vom Helden gesammelte Erfahrung um 5%.",
	L"Steigert die vom Helden gesammelte Erfahrung um 10%.",
	L"Steigert die vom Helden gesammelte Erfahrung um 15%.",
	L"Die Sicht Ihres Helden erweitert sich um 2 Felder.",
	L"Die Sicht Ihres Helden erweitert sich um 4 Felder.",
	L"Die Sicht Ihres Helden erweitert sich um 6 Felder.",
	L"Steigert die Bewegungspunkte des Helden um 10%.",
	L"Steigert die Bewegungspunkte des Helden um 20%.",
	L"Steigert die Bewegungspunkte des Helden um 30%.",
	L"Verringert die Bewegungsstrafe f\u00FCr unwegsames Gel\u00E4nde um 25%.",
	L"Verringert die Bewegungsstrafe f\u00FCr unwegsames Gel\u00E4nde um 50%.",
	L"Verringert die Bewegungsstrafe f\u00FCr unwegsames Gel\u00E4nde um 75%.",
	L"Steigert den durch einen Fernangriff erzielten Schaden  um 10%.",
	L"Steigert den durch einen Fernangriff erzielten Schaden  um 25%.",
	L"Steigert den durch einen Fernangriff erzielten Schaden  um 50%.",
	L"Erlaubt einen gezielten Schuss mit erh\u00F6htem Schaden.",
	L"Erlaubt zwei gezielte Sch\u00FCsse mit erh\u00F6htem Schaden.",
	L"Erlaubt zwei gezielte Sch\u00FCsse mit maximalem Schaden.",
	L"Steigert den Nahkampf-Angriffsschaden um 10%.",
	L"Steigert den Nahkampf-Angriffsschaden um 20%.",
	L"Steigert den Nahkampf-Angriffsschaden um 30%.",
	L"Reduziert den Schaden, der den Truppen Ihres Helden zugef\u00FCgt wird um 5%.",
	L"Reduziert den Schaden, der den Truppen Ihres Helden zugef\u00FCgt wird um 10%.",
	L"Reduziert den Schaden, der den Truppen Ihres Helden zugef\u00FCgt wird um 15%.",
	L"Einfach",
	L"Fortgeschritten",
	L"Experte",
	L"Gold",
	L"Erz",
	L"Holz",
	L"Quecksilber",
	L"Edelsteine",
	L"Kristalle",
	L"Schwefel",
	L"Zuf\u00E4lliger Rohstoff",
	L"Goldhaufen",
	L"Erzhaufen",
	L"B\u00FCndel Holz",
	L"Flasche Quecksilber",
	L"Edelsteinhaufen",
	L"Kristallhaufen",
	L"Schwefelhaufen",
	L"Manakristall",
	L"Lagerfeuer",
	L"Schatzkiste",
	L"Lampe",
	L"Zauberrolle",
	L"Artefakt",
	L"Wache",
	L"Hoch auf Ihrem Ross, siehst du wie eine Wache zu Ihnen tritt und sagt: \"Willkommen. Ich habe von Ihrer Ankunft geh\u00F6rt. M\u00F6chtest du passieren?\"",
	L"\"Niemand hat mir von Ihrem Kommen berichtet\", sagt der Grenzposten. \"Ich kann Sie nicht passieren lassen. Vielleicht solltest du zuerst das Zelt des Schl\u00FCsselmeisters aufsuchen\".",
	L"Nachdem Du den Bereich ausgekundschaftet hast, stolperst Du \u00FCber einen versteckten Schatz. Du kannst das Gold nehmen oder es f\u00FCr Erfahrungspunkte unter den Bauern verteilen.",
	L"Du findest eine Spruchrolle, die mit dem %s Zauber beschrieben ist.",
	L"Ereignis",
	L"Marker",
	L"Zuf\u00E4llig",
	L"Zuf\u00E4llig (Level 1)",
	L"Zuf\u00E4llig (Level 2)",
	L"Zuf\u00E4llig (Level 3)",
	L"Zuf\u00E4llig (Level 4)",
	L"Zuf\u00E4llig (Level 5)",
	L"Zuf\u00E4llig (Level 6)",
	L"\u0421\u043B\u0443\u0447\u0430\u0439\u043D\u044B\u0439",
	L"Zuf\u00E4llig (Level 1)",
	L"Zuf\u00E4llig (Level 2)",
	L"Zuf\u00E4llig (Level 3)",
	L"Zuf\u00E4llig (Level 4)",
	L"Loch",
	L"Spalt",
	L"Skelett",
	L"Blumen",
	L"Pilz",
	L"Fels",
	L"Baumstumpf",
	L"Holzscheit",
	L"Kaktur",
	L"Busch",
	L"B\u00E4ume",
	L"Palme",
	L"Kiefer",
	L"Eiche",
	L"Toter Baum",
	L"Vulkan",
	L"Berg",
	L"See",
	L"Wall",
	L"Schlammige Stra\u00DFe",
	L"Steinige Stra\u00DFe",
	L"Verschneite Stra\u00DFe",
	L"Fluss",
	L"Lavafluss",
	L"Harbor",
	L"Portal",
	L"Lichtstein",
	L"Holzschild",
	L"Aussichtsturm",
	L"Medusatempel",
	L"Diebeswagen",
	L"W\u00FCstenzelt",
	L"Geisterhaus",
	L"Steinbrunnen",
	L"Gartenlaube",
	L"Baum des Wissens",
	L"Monolyt",
	L"Windm\u00FChle",
	L"Schrein des ersten Kreises",
	L"Schrein des zweiten Kreises",
	L"Schrein des dritten Kreises",
	L"Stallungen",
	L"G\u00F6tzenbild",
	L"Dreieinigkeit",
	L"Springbrunnen",
	L"Tempel",
	L"Schwert im Stein",
	L"Fort",
	L"Schmiede",
	L"Steinkreis",
	L"Magischer Stein",
	L"Prophetenstatue",
	L"Arena",
	L"Bibliothek",
	L"Obelisk",
	L"Magischer Brunnen",
	L"Garten des Wissens",
	L"Hexenh\u00FCtte",
	L"Schiffswrack",
	L"Eish\u00F6hle",
	L"Pyramide",
	L"Tempel der Inti",
	L"Schatz der Oger",
	L"Schatz der Magier",
	L"Schatz der Hydra",
	L"Schatz der Medusa",
	L"Schatz der Gargoyles",
	L"Schatz der Druiden",
	L"Magische Zitadelle",
	L"Kloster",
	L"Mausoleum",
	L"Magische Schule",
	L"Pegasus Wasserfall",
	L"Wei\u00DFe Wolfsh\u00F6hle",
	L"Wolfsh\u00F6hle",
	L"Sarg",
	L"Vampirsarg",
	L"Wolfsh\u00F6hle alt",
	L"Wildscheinh\u00F6hle alt",
	L"Schwertk\u00E4mpfer Arsenal alt",
	L"Halblingsh\u00FCtte alt",
	L"Platzhalter",
	L"Zelt des Schl\u00FCsselmeisters",
	L"Gie\u00DFerei",
	L"Lehmh\u00FCtte des Ogers",
	L"Mumiensarg",
	L"Elfenhaus",
	L"Druidenstein",
	L"Greifennest",
	L"Jagdhaus",
	L"Schrein",
	L"Kleine Schmiede",
	L"Waldhut",
	L"Kasarne",
	L"Residenz",
	L"Tatar Yurt",
	L"War Academy",
	L" ",
	L"Ein Schluck aus der Quelle hat Ihre Zauberpunkte erneuert.",
	L"Ein alter Ritter erscheint auf den Stufen der Gartenlaube \"Mein Lehnsherr, ich werde euch all mein Wissen lehren um euch auf euren Reisen Beistand leisten zu k\u00F6nnen.\"",
	L"Auf Ihre Ann\u00E4herung hin \u00F6ffnet der Baum vergn\u00FCgt seine Augen: \"Aah, ein Abenteurer! Erlaube mir, Ihnen ein wenig von dem beizubringen, was ich \u00FCber die Jahre gelernt habe.\"",
	L"Als Sie sich n\u00E4hern, beginnt der Monolit zu leuchten. Sie entscheiden sich, die Symbole auf ihre Bedeutung hin zu erforschen.",
	L"Der Besitzer der M\u00FChle erkl\u00E4rt: \"Mein Lord, ich habe sehr hart gearbeitet um euch mit diesen Rohstoffen zu beliefern, n\u00E4chste Woche gibt es weitere Rohstoffe.\"",
	L"Sie kommen an einem kleinen Schrein vorbei, der von einer Gruppe Akolythen bewacht wird. Im Gegenzug f\u00FCr Ihre Schutz willigen sie ein, Ihnen einen einfachen Zauber beizubringen - ",
	L"Sie kommen an einem kunstvoll verzierten Schrein vorbei, der von wohlgen\u00E4hrten M\u00F6nchen bewacht wird. Im Gegenzug f\u00FCr Ihre Schutz willigen sie ein, Ihnen einen Zauber beizubringen - ",
	L"Sie kommen an einem verschwenderisch verzierten Schrein vorbei, der von einer Gruppe Hohepriestern bewacht wird. Im Gegenzug f\u00FCr Ihren Schutz willigen sie ein, Ihnen einen anspruchsvollen Zauber beizubringen - ",
	L"Als Sie in den Stallungen eintriffen, kommen Ihnen der Stallbursche mit einem edlen Schlachtross entgegen: \"Dieses Pferd wird Ihre Reisen beschleunigen. Leider wird seine Ausdauer nach langen Reisen sinken. Sie m\u00FCssen f\u00FCr ein frisches Reittier jede Woche zur\u00FCckkehren.\"",
	L"Sie haben ein uraltes, verwittertes G\u00F6tzenbild endtdeckt. Angeblich bringt ein Kuss des G\u00F6tzenbilds Gl\u00FCck - der Stein f\u00FChlt sich sehr kalt an.",
	L"Das ist alles, was ich die Woche \u00FCber gesammelt habe. Benutze das Gold gut \u00FCberlegt.",
	L"Ein Schluck des s\u00FC\u00DFen Wassers bringt Ihnen Gl\u00FCck f\u00FCr den n\u00E4chsten Kampf.",
	L"Ein Besuch und ein Gebet im Tempel erh\u00F6ht die Moral Ihrer Truppen.",
	L"Sie haben einige Stunden mit dem Versuch verbracht, das Schwert aus dem Stein zu ziehen - es hat sich noch keinen Zentimeter bewegt\u2026 Aber \u00E4rgeren such nicht - Ihre Armee hat sich w\u00E4hrenddessen ausgeruht und f\u00FCr Ihnen war es eine gute \u00DCbung!",
	L"Die Stunde, die Sie im Fort verbracht haben, zeigte Ihenn der Meister neue Verteidigungstechniken.",
	L"Sie erreichen eine Schmiede\u2026 Als Sie hineingehen, sehen Sie einen Waffenschmied bei der Arbeit. Er legt seinen Hammer zur Seite und sagt: \"Ich kann Ihre R\u00FCstung reparieren!\"",
	L"Sie haben eine Gruppe Druiden gefunden, die eines ihrer seltsamen steinernen Geb\u00E4ude verehren. Leise bringen Sie Ihnen neue Wege zu zaubern bei.",
	L"Sie haben eine Gruppe Heiden gefunden, die an einem fremden gl\u00FChenden Stein beten. Sie treten dem Ritual bei. Leise bringen Sie Ihnen neue Wege zu zaubern bei.",
	L"Sie ber\u00FChren die Statue des Propheten und sp\u00FCren wie Ihre Macht steigt.",
	L"Sie betreten die Arena und sehen sich einer Horde hungriger L\u00F6wen gegen\u00FCber. Unter lauten Jubelrufen der Menge besiegen Sie. Beeidruckt von Ihre Fertigkeiten, willigt der alte Gladiatoren ein, Sie in Angriff und Verteidigung zu trainieren.",
	L"Der W\u00E4rter l\u00E4sst Sie in die Bibliothek der Erleuchtung ein. Sie k\u00F6nnen viel lernen in der kurzen Zeit die Sie hier verbringen.",
	L"Sie erreichen einen Obelisken, der aus einer Steinart beschaffen ist, die Sie noch niemals zuvor gesehen haben. Als Sie den Obelisken genauer untersuchen, ver\u00E4ndert sich pl\u00F6tzlich die glatte Oberfl\u00E4che des Steins zu einer Inschrift. Die Inschrift ist Teil einer uralten Karte. Schnell zeichnen Sie die sonderbaren Muster ab und genauso schnell wie sie aufgetaucht ist, verschwindet die Inschrift auch wieder.",
	L"Ein Schluck aus der Quelle f\u00FCllt Ihre Adern mit Magie! Sie haben nun doppelt soviele Zauberpunkt als normal in Reserve.",
	L"Ein M\u00F6nch, der in der Mitte eines Gartens sitzt, l\u00E4dt Sie ein mit ihm zu meditieren. Sie willigen ein, und bereits nach kurzer Zeit f\u00FChlen Sie sich erleuchtet.",
	L"Der W\u00E4chter dieses Schl\u00FCsselmeisterzeltes scheint gl\u00FCcklich zu sein Sie zu sehen. \"Ah, endlich jemand W\u00FCrdiges\", sagt er. \"Ich werde sofort eine Nachricht an die Grenzwache losschicken, dass Sie passieren d\u00FCrfen.\"",
	L" ",
	L"Zweimal in einer Woche aus der Quelle zu trinken wird Ihnen nicht weiterhelfen.",
	L"Ein alter Ritter erscheint auf den Stufen der Gartenlaube \"Mein Lehnsherr, es tut mir leid, aber ich habe ihnen bereits alles beigebracht was ich wusste.\"",
	L"Der Baum oeffnet die Augen und sagt: \"Ich hoffe, mein Unterricht hat Ihnen geholfen\".",
	L"Auf Ihre Ann\u00E4herung hin ,erlischt das Licht des Monoliths.",
	L"Der M\u00FCller sagt euch: \"Mein Lord es tut mir Leid, leider habe ich zur Zeit keine Rohstoffe f\u00FCr euch. Kommt doch bitte n\u00E4chste Woche noch einmal vorbei.\"",
	L"Der Stallbursche taucht auf und sagt:\"Sie haben bereits ein frisches Pferd.\"",
	L"Sie haben ein uraltes, verwittertes G\u00F6tzenbild endtdeckt. Angeblich bringt ein Kuss des G\u00F6tzenbilds Gl\u00FCck - aber da die Sterne bereits auf Sie hinabscheinen, passiert nichts.\"",
	L"Ich habe kein weiteres Gold f\u00FCr Sie. Komm morgen wieder.",
	L"Sie trinken von der verzauberten Quelle, aber nichts passiert.",
	L"Es hilft nicht zweimal vor einem Kampf zu beten.",
	L"Dieses Schwert steckt im Stein fest! Keine Chance es herauszubekommen!",
	L"Ich habe Ihnen bereits alles beigebracht was ich kann. Ich will meine Zeit mit Ihnen nicht weiter verschwenden, also verschwinde!",
	L"Sie erreichen eine Schmiede. Als Sie hineingehen, sehen Sie einen Waffenschmied bei der Arbeit. Er untersucht ihr Schild und sagt: \"Das Schild muss nicht repariert werden. Ich habe bereits alles f\u00FCr Sie getan was ich konnte.\"",
	L"Sie haben eine Gruppe Druiden gefunden, die eines ihrer seltsamen steinernen Geb\u00E4ude verehren. Leise wenden sie sich von Ihnen ab, Ihnen zeigend, dass sie Ihnen nichts Neues beibringen k\u00F6nnen.",
	L"Sie haben eine Gruppe von Heiden gefunden, die an einem fremden gl\u00FChenden Stein beten. Leise wenden sie such von Ihnen ab, Ihnen zeigend, dass sie Ihnen nichts Neues beibringen k\u00F6nnen.",
	L"Sie ber\u00FChren die Statue, aber nichts passiert. Als Sie die Statue ein zweites Mal ber\u00FChren, f\u00E4ngt sie pl\u00F6tzlich zu sprechen an: \"Ich hab Ihnen meine magische Kraft verliehen und trotzdem gehst du mir weiter auf die Nerven!? Verschwinde!\"",
	L"Die Wachen der Arena halten Sie vom Eintreten ab: \"Sie haben bereits unsere Besten besiegt. Sie k\u00F6nnen gehen.\"",
	L"Sich an Sie erinnernd weigert sich der W\u00E4rter Sie einzulassen: \"Die Bibliothek der Erleuchtung\", sagt er, \"darf nur einmal besucht werden.\"",
	L"Sie haben diesen Obelisk bereits besucht.",
	L"Die magische Quelle regeneriert sich nur einmal jede Woche, und irgendjemand war bereits hier diese Woche.",
	L"Sie betreten den Garten, und der M\u00F6nch, sich an Sie erinnernd, sagt, \"Mein Kind, der Segen der Weisheit \u00FCberkommt einen nur einmal in seinem Leben.\"",
	L"Der W\u00E4chter dieses Zelts des Schl\u00FCsselmeisters erinnert sich an Sie als Sie n\u00E4her kommen. \"Ich habe bereits Nachricht geschickt, dass es Ihnen erlaubt ist zu passieren,\" sagt er.",
	L"Ungl\u00FCcklicherweise haben Sie noch nicht das Wissen den Spruch zu verstehen, weswegen Sie ihn auch noch nicht erlernen k\u00F6nnen.",
	L"In einer seltsamen H\u00FCtte hei\u00DFt Sie eine uralte Hexe willkommen - aus r\u00E4tselhaften Gr\u00FCnden bringst sie Ihnen %s bei.",
	L"Sie erreichen eine seltsame H\u00FCtte und beobachten wie innen eine Hexe ein Buch \u00FCber %s studiert. Als Sie sich n\u00E4hern, dreht sie sich um und sagt: \"Du wei\u00DFt bereits was ich Ihnen beibringen wollte. Ich kann Ihnen nicht weiterhelfen.\"",
	L"Sie erreichen eine seltsame H\u00FCtte und beobachten wie innen eine Hexe ein Buch \u00FCber %s studiert. Als Sie sich n\u00E4hern, dreht sie sich um, fixiert Sie mit ihren Glasauge und kreischt: \"Hah, ich werde nicht versuchen jemandem der so weise ist wie Du etwas beizubringen.\" Du verl\u00E4sst die H\u00FCtte, kannst aber das ungute Gef\u00FChl nicht absch\u00FCtteln.",
	L"M\u00F6chten Sie %s rekrutieren?",
	L"%d %s schlie\u00DFen sich Ihnen an.",
	L"Hier gibt es keine %s mehr zu rekrutieren.",
	L"Sie entdecken einen l\u00E4ngst verlassenen Ort: %s.",
	L"Nachdem Sie die Wachen besiegen, haben Sie entdecken: ",
	L"Teleport",
	L"Teleport",
	L"Teleport",
	L"Dieses Bauwerk ist offensichtlich eine Reisepforte, sie erscheint aber nicht l\u00E4nger funktionsf\u00E4hig zu sein.",
	L"Choose a creature to upgrade",
	L"Sorry, this creature can't be improved.",
	L"Sp\u00E4hturm",
	L"Beobachtungsturm",
	L"Von Ihrem Sp\u00E4hturm aus, k\u00F6nnen Sie weit entfernte L\u00E4nder sehen.",
	L"Von Ihrem Beobachtungsturm aus, k\u00F6nnen Sie weit entfernte L\u00E4nder sehen. Alle Ihre Helden erhalten eine +1 Bewegungsbonus.",
	L"Goldmine",
	L"Erzgrube",
	L"S\u00E4gem\u00FChle",
	L"Alchemielabor",
	L"Edelsteinmine",
	L"Kristallmine",
	L"Schwefelmine",
	L"Sie erhalten die Kontrolle \u00FCber eine Goldmine. Sie wird Sie mit 1000 Gold pro Tag versorgen.",
	L"Sie erhalten die Kontrolle \u00FCber eine Erzgrube. Sie wird Sie mit zwei Einheiten Erz pro Tag versorgen.",
	L"Sie erhalten die Kontrolle \u00FCber ein S\u00E4gewerk. Es wird Sie mit zwei Einheiten Holz pro Tag versorgen.",
	L"Sie erhalten die Kontrolle \u00FCber ein Alchemielabor. Es wird Sie mit einer Einheit Quecksilber pro Tag versorgen.",
	L"Sie erhalten die Kontrolle \u00FCber eine Edelsteinmine. Sie wird Sie mit einer Einheit Edelsteinen pro Tag versorgen.",
	L"Sie erhalten die Kontrolle \u00FCber eine Kristallmine. Sie wird Sie mit einer Einheit Kristallen pro Tag versorgen.",
	L"Sie erhalten die Kontrolle \u00FCber eine Schwefelmine. Sie wird Sie mit einer Einheit Schwefel pro Tag versorgen.",
	L"Stadtportal",
	L"Schiff",
	L"Bereits Besucht",
	L"Nicht besucht",
	L"Ritter",
	L"Barbar",
	L"Zauberer",
	L"Hexenmeister",
	L"Zauberin",
	L"Totenbeschw\u00F6rer",
	L"War\u00E4ger",
	L"Gerald",
	L"Fineous",
	L"Jacob",
	L"Schultz",
	L"Cantor",
	L"Bez",
	L"Earoon",
	L"Hedric",
	L"Tyrex",
	L"Grottekvarnen",
	L"Yog",
	L"Jaclyn",
	L"Krag",
	L"Baraka",
	L"Hapax",
	L"Krull",
	L"Cronus",
	L"Iona",
	L"Bernhard",
	L"Posid",
	L"Malcom",
	L"Morgana",
	L"Victor",
	L"Visarus",
	L"Gallatin",
	L"Altus",
	L"Odin",
	L"Kastore",
	L"Alamar",
	L"Eldor",
	L"Fondo",
	L"Marcus",
	L"Jack",
	L"Ferentona",
	L"Gem",
	L"Arven",
	L"Samira",
	L"Myrini",
	L"Rebecca",
	L"Dvergar",
	L"Rait",
	L"Urof",
	L"Tamika",
	L"Shra",
	L"Ruthven",
	L"Ranloo",
	L"Sandru",
	L"Ruprecth",
	L"Alexey",
	L"Dobrinya",
	L"Ilya",
	L"Lytobor",
	L"Miroslav",
	L"Oleg",
	L"Vladimir",
	L"Yaropolk",
	L"Zuf\u00E4llig",
	L"Zitadelle",
	L"Hochburg",
	L"Turm",
	L"Verlie\u00DF",
	L"Festung",
	L"Nekropolis",
	L"Kremlin",
	L"Klein",
	L"Mittel",
	L"Gro\u00DF",
	L"Mage Guild",
	L"Shipyard",
	L"Bauernh\u00FCtte",
	L"Bogensch\u00FCtzenturm",
	L"Wachhaus",
	L"Abtei",
	L"Turnierplatz",
	L"Kathedrale",
	L"Goblinbaracken",
	L"Orkturm",
	L"Wolfsbau",
	L"Ogerfort",
	L"Trollbr\u00FCcke",
	L"Zyklopenpyramide",
	L"Magische Schule",
	L"Wolfsh\u00F6hle",
	L"Fabrik",
	L"Magische Wolke",
	L"Magierturm",
	L"Wolkenschloss",
	L"Zentaurenh\u00F6hle",
	L"Gruft",
	L"Greifenturm",
	L"Labyrinth",
	L"Hydrateich",
	L"Drachenh\u00F6hle",
	L"Baumhaus",
	L"Zwergenh\u00E4uschen",
	L"Geh\u00F6ft",
	L"Druidenzirkel",
	L"Einhornlichtung",
	L"Roter Turm",
	L"Ausgrabungsst\u00E4tte",
	L"Friedhof",
	L"Grabmal",
	L"Haus der S\u00E4rge",
	L"Dunkles Grab",
	L"Verfluchter Turm",
	L"Jagdhaus",
	L"Schmiede",
	L"Kaserne",
	L"Waldhaus",
	L"Schrein",
	L"Residenz",
	L"Magiergilde 1",
	L"Magiergilde 2",
	L"Magiergilde 3",
	L"Magiergilde 4",
	L"Magiergilde 5",
	L"Magischer Knoten",
	L"Taverne",
	L"Marktplatz",
	L"Ratshaus",
	L"Stadthalle",
	L"Erzgrube",
	L"S\u00E4gewerk",
	L"Alchemielabor",
	L"Edelsteinmine",
	L"Kristallmine",
	L"Schwefelmine",
	L"Burggraben",
	L"Hauptgesch\u00FCtzturm",
	L"Linker Gesch\u00FCtzturm",
	L"Rechter Gesch\u00FCtzturm",
	L"Schie\u00DFplatz",
	L"Gerichtshalle",
	L"Eichenwald",
	L"Wasserfall",
	L"Bergmannsgilde",
	L"Offene Gr\u00E4ber",
	L"Wachturm",
	L"H\u00E4uschen",
	L"Laden",
	L"Aussichtsturm",
	L"Befestigungen",
	L"Halle der Vorfahren",
	L"Lehmstein",
	L"Wall der Weisheit",
	L"Bibliothek",
	L"Altar",
	L"Manawirbel",
	L"Schatzkammer",
	L"Mystischer Teich",
	L"Verst\u00E4rker der Totenbeschw\u00F6rer",
	L"Schleier der Dunkelheit",
	L"%s erlaubt Ihnen %s zu rekrutieren.",
	L"Das Betreten der Magiergilde l\u00E4sst einen anwesenden Helden die Spr\u00FCche der Gilde lernen.",
	L"Stellt pro Tag 1 Manapunkt f\u00FCr alle verb\u00FCndeten Helden wieder her.",
	L"Die Taverne erm\u00F6glicht es Helden anzuheuern und erh\u00F6ht die Moral der Truppen, die die Stadt verteidigen.",
	L"Auf dem Marktplatz k\u00F6nnen Sie Rohstoffe kaufen und verkaufen (Die Tarife verbessern sich je mehr Marktpl\u00E4tze Sie besitzen).",
	L"Das Rathaus verbessert das Einkommen Ihres Reiches um 500 Gold jeden Tag.",
	L"Die Stadthalle erh\u00F6ht das Einkommen Ihres Reiches um 1500 Gold pro Tag.",
	L"Die Erzgrube versorgt Sie mit einer zus\u00E4tzlichen Einheit Erz jeden Tag.",
	L"Das S\u00E4gewerk versorgt Sie mit einer zus\u00E4tzlichen Einheit Holz jeden Tag.",
	L"Das Alchemielabor versorgt Sie mit einer zus\u00E4tzlichen Einheit Quecksilber jeden Tag.",
	L"Die Edelsteinmine versorgt Sie mit einer zus\u00E4tzlichen Einheit Edelsteinen jeden Tag.",
	L"Die Kristallmine versorgt Sie mit einer zus\u00E4tzlichen Einheit Kristall jeden Tag.",
	L"Die Schwefelmine versorgt Sie mit einer zus\u00E4tzlichen Einheit Schwefel jeden Tag.",
	L"Der Burggraben verlangsamt angreifende Einheiten. Jede Einheit die den Burggraben betritt muss ihren Zug dort beenden und wird verwundbarer gegen\u00FCber Attacken.",
	L"Der Hauptgesch\u00FCtzturm liefert zus\u00E4tzliche Feuerkraft w\u00E4hrend einer Belagerung.",
	L"Der linke Gesch\u00FCtzturm liefert zus\u00E4tzliche Feuerkraft w\u00E4hrend einer Belagerung.",
	L"Der rechte Gesch\u00FCtzturm liefert zus\u00E4tzliche Feuerkraft w\u00E4hrend einer Belagerung.",
	L"%s erh\u00F6ht die Produktion von %s um %d pro Woche.",
	L"Das H\u00E4uschen gibt ein zus\u00E4tzlicher Trupp f\u00FCr den belagerten Held.",
	L"Die Laden verbessert die Marktplatz.",
	L"Der Aussichtsturm erh\u00F6ht die sichtbare Fl\u00E4che um Ihre Stadt, und alle Ihre Helden erhalten +5 Reisepunkte als Bonus.",
	L"Befestigungen verbessern die Haltbarkeit von Burgw\u00E4llen w\u00E4hrend einer Belagerung.",
	L"Die Halle der Vorfahren steigert die Angriff F\u00E4higkeit jedes Helden der sie besucht um 1.",
	L"Die Halle der Weisheit erh\u00F6ht die Weisheit jedes Helden der sie besucht um 1.",
	L"Die Bibliothek \u00E4ndert zuf\u00E4llig einige der Zauber in Ihrer Magiergilde am Anfang jedes Monats.",
	L"Der Altar erh\u00F6ht das Einkommen Ihres Reiches um 1000 Gold pro Tag.",
	L"Der Manawirbel verdoppelt vor\u00FCbergehend die Zauberpunkte eines Helden der ihn besucht.",
	L"Die Schatzkammer erh\u00F6ht das Einkommen Ihres Reiches um 1000 Gold pro Tag.",
	L"Der Mystische Teich produziert jede Woche eine geringe Menge Rohstoffe.",
	L"Der Verst\u00E4rker der Totenbeschw\u00F6rer erh\u00F6ht die Totenbeschw\u00F6rerf\u00E4higkeit aller Ihrer Helden (mit Totenbeschw\u00F6rerf\u00E4higkeit) um 10%.",
	L"Der Schleier der Dunkelheit verbirgt Ihre Stadt dauerhaft vor allen anderen Spielern.",
	L"Der Teich hat noch nichts produziert.",
	L"Der Teich hat diese Woche %s produziert.",
	L"The Hall of Valhalla has increased your Attack skill by +1.",
	L"The Mana Vortex has doubled your spell points.",
	L"The Wall of Knowledge has increased your Knowledge by +1.",
	L"After a short visit to Mage Guild you learned new spells.",
	L"Silberschwert",
	L"Bauernsichel",
	L"Brustplatte",
	L"Drachenschild",
	L"M\u00F6nchsring",
	L"Hexenbrosche der Magie",
	L"Unbedeutende Schriftrolle der Weisheit",
	L"Pergamentrolle",
	L"Anh\u00E4nger der Weisheit",
	L"Ehrenmedaille",
	L"Medaille",
	L"Gl\u00FCcksw\u00FCrfel",
	L"Gl\u00FCckskleeblatt",
	L"Silberner Gl\u00FCcksvogel",
	L"Langbogen",
	L"Ring der Untoten",
	L"Teleskop",
	L"Sch\u00FCtzende Luftrobe",
	L"Sch\u00FCtzende Erdrobe",
	L"Sch\u00FCtzende Feuerrobe",
	L"Sch\u00FCtzende Wasserrobe",
	L"Manakrug",
	L"M\u00E4chtige Axt",
	L"Kriegerhelm",
	L"Beschw\u00F6rerarmschienen",
	L"Schriftrolle der Erleuchtung",
	L"Stachelhelm",
	L"Der Ring des Weisen",
	L"Weisse Perlenkette",
	L"Goldener Gl\u00FCcksvogel",
	L"Unersch\u00F6pflicher Erzkarren",
	L"Unersch\u00F6pfliches Holzklafter",
	L"Ring des Lebens",
	L"Anh\u00E4nger des Lebens",
	L"Elfenbogen",
	L"Vampirkutte",
	L"Stiefel des Reisenden",
	L"Federkiel der Diplomatie",
	L"Robe des Widerstands",
	L"Robe der Gewandheit",
	L"Verzaubertes Schwert",
	L"M\u00E4chtige R\u00FCstung",
	L"Ring der Kraft",
	L"Buch der Erkenntnis",
	L"Antikes Breitschwert",
	L"Zwergenschild",
	L"Schild des Paladins",
	L"Stab der Hexerei",
	L"Bedeutende Schriftrolle der Erkenntnis",
	L"Buch der Weisheit",
	L"Finsternis",
	L"Schlangenarmreif",
	L"Schwarze Perlenkette",
	L"Anh\u00E4nger der Allwissenheit",
	L"Ring der Ewigkeit",
	L"Armbrust",
	L"Schwert der Untoten",
	L"Unersch\u00F6pfliche Goldb\u00F6rse",
	L"Unersch\u00F6pflicher Goldsack",
	L"Amulett des Reichtums",
	L"Unersch\u00F6pfliche Quecksilberphiole",
	L"Unersch\u00F6pflicher Edelsteinbeutel",
	L"Schwefelring",
	L"Kristallrose",
	L"Nomadenstiefel",
	L"Langschwert",
	L"Heldenschild",
	L"Helm der Vorboten",
	L"Zaubererhut",
	L"Schwertbrecher",
	L"Halsband des Hexenmeisters",
	L"Sph\u00E4re des Negation",
	L"Zauberstab",
	L"Fu\u00DFfesseln des Kriegers",
	L"Krone des Eroberers",
	L"Wurfaxt",
	L"Goblin Schild",
	L"Zauberanh\u00E4nger",
	L"Verfluchtes Schwert",
	L"Sph\u00E4re der Luft",
	L"Sph\u00E4re der Erde",
	L"Sph\u00E4re des Feuers",
	L"Sph\u00E4re des Wassers",
	L"Eiserne Schlagkugel",
	L"Goldene Schlagkugel",
	L"Goldenes Schwert",
	L"Goldenes Schild",
	L"Goldene R\u00FCstung",
	L"Goldener Sch\u00E4del",
	L"Eiserne Beinschienen",
	L"Kn\u00F6cherne Beinschienen",
	L"Schwert des Bastards",
	L"Luftdiadem",
	L"J\u00E4gershut",
	L"Lederr\u00FCstung",
	L"Goblinhut",
	L"Knochenkette",
	L"Zwergenhelm",
	L"Reiterhelm",
	L"Ogerschild",
	L"Pfeile",
	L"Sonnenstab",
	L"Zwergenhammer",
	L"Fl\u00FCgelhelm",
	L"Knochenmaske",
	L"Knochenr\u00FCstung",
	L"K\u00F6nigsschild",
	L"Blutstein-Kette",
	L"Schneller Bogen",
	L"Sumpfschuhe",
	L"Eisamulett",
	L"Steigert Ihren Angriff um 1.",
	L"Steigert Ihren Angriff um 1, erh\u00F6ht den Angriff der Bauern um 3.",
	L"Steigert Ihre Verteidigung um 1 und die der Kavallerie um 2.",
	L"Steigert Ihre Verteidigung um 1 und die Drachenverteidigung um 5.",
	L"Steigert Ihre Zauberkraft um 1 und die der M\u00F6nche um 3.",
	L"Steigert Ihre Zauberkraft um 1.",
	L"Steigert Ihr Wissen um 1.",
	L"Steigert Ihr Wissen um 1.",
	L"Steigert Ihr Wissen um 1.",
	L"Steigert Ihre Moral um 1.",
	L"Steigert Ihre Moral um 1.",
	L"Steigert Ihr Gl\u00FCck um 1.",
	L" Steigert Ihr Gl\u00FCck um 1.",
	L"Steigert Ihr Gl\u00FCck um 1.",
	L"Steigert Ihre Fernkampffertigkeit um 5%.",
	L"Steigert Ihre Totenbeschw\u00F6rerfertigkeit um 5%.",
	L"Erlaubt Ihrem Helden 1 Feld weiter zu sehen.",
	L"Luftmagiezauber verursachen 30% weniger Schaden.",
	L"Erdmagiezauber verursachen 30% weniger Schaden.",
	L"Feuermagiezauber verursachen 30% weniger Schaden.",
	L"Wassermagiezauber verursachen 30% weniger Schaden.",
	L"Stellt 2 zus\u00E4tzliche Zauberpunkte pro Tag wieder her.",
	L"Erh\u00F6ht Angriff und Verteidigung um 1.",
	L"Steigert Ihre Verteidigung um 2.",
	L"Steigert Ihre Zauberkraft um 2.",
	L"Steigert Ihr Wissen um 2.",
	L"Erh\u00F6ht Angriff und Verteidigung um 1.",
	L"Erh\u00F6ht Zauberkraft und Wissen um 1.",
	L"Erh\u00F6ht Zauberkraft und Wissen um 1.",
	L"Steigert Ihr Gl\u00FCck um 2.",
	L"Versorgt Sie mit einer zus\u00E4tzlichen Einheit Erz pro Tag.",
	L"Versorgt Sie mit einer zus\u00E4tzlichen Einheit Holz pro Tag.",
	L"Erh\u00F6ht die Gesundheit aller Ihrer Einheiten um 1.",
	L"Erh\u00F6ht die Gesundheit aller Ihrer Einheiten um 2.",
	L"Steigert Ihre Fernkampf Fertigkeit um 10% und den Angriff der Elfen um 3.",
	L"Steigert Ihre Totenbeschw\u00F6rerfertigkeit um 10% und die Verteidigung der Vampire um 1.",
	L"Erh\u00F6ht ihre Bewegungspunkte an Land um 20.",
	L"Senkt die Kosten einer Kapitulation um 20%.",
	L"Erh\u00F6ht Ihre Magische Resistenz um 10%.",
	L"Erh\u00F6ht die Kampfgeschwindigkeit aller Ihrer Einheiten um 1.",
	L"Steigert Ihren Angriff um 3.",
	L"Steigert Ihre Verteidigung um 3.",
	L"Steigert Ihre Zauberkraft um 3.",
	L"Steigert Ihr Wissen um 3.",
	L"Steigert Ihren Angriff um 4.",
	L"Steigert Ihre Verteidigung um 4.",
	L"Steigert Ihre Verteidigung um 4 und die der Paladine um 2.",
	L"Steigert Ihre Zauberkraft um 4.",
	L"Steigert Ihr Wissen um 4.",
	L"Steigert Ihr Wissen um 4.",
	L"Erh\u00F6ht Angriff und Verteidigung um 2.",
	L" Erh\u00F6ht Zauberkraft und Wissen um 2.",
	L"Erh\u00F6ht Zauberkraft und Wissen um 2.",
	L"Erh\u00F6ht Angriff, Verteidigung, Zauberkraft und Wissen jeweils um 1.",
	L"Erh\u00F6ht die Gesundheit aller Ihrer Einheiten um 3.",
	L"Steigert Ihre Fernkampf Fertigkeit um 15%.",
	L"Steigert Ihre Totenbeschw\u00F6rerfertigkeit um 15%.",
	L"Steigert Ihr Einkommen um 500 Gold pro Tag.",
	L"Steigert Ihr Einkommen um 750 Gold pro Tag.",
	L"Steigert Ihr Einkommen um 1000 Gold pro Tag.",
	L"Versorgt Sie t\u00E4glich mit einer zus\u00E4tzlichen Einheit Quecksilber.",
	L" Versorgt Sie t\u00E4glich mit einer zus\u00E4tzlichen Einheit Edelsteinen.",
	L"Versorgt Sie t\u00E4glich mit einer zus\u00E4tzlichen Einheit Schwefel.",
	L"Versorgt Sie t\u00E4glich mit einer zus\u00E4tzlichen Einheit Kristall.",
	L"Erh\u00F6ht Ihre Bewegungspunkte an Land um 30 und die Geschwindigkeit der Normaden um 3.",
	L"Steigert Ihren Angriff um 6.",
	L"Steigert Ihre Verteidigung um 6.",
	L"Steigert Ihre Zauberkraft um 6.",
	L"Steigert Ihr Wissen um 6.",
	L"Erh\u00F6ht Ihren Angriff und Ihr Verteidigung um 3.",
	L"Erh\u00F6ht Ihre Zauberkraft und Ihr Wissen um 3.",
	L"Erh\u00F6ht Ihren Angriff, Ihre Verteidigung, Ihre Zauberkraft und Ihr Wissen jeweils um 2.",
	L"Weder Sie noch Ihr Gegner d\u00FCrfen fliehen oder aufgeben.",
	L"Verhindert jegliches Aussprechen von Zaubern w\u00E4hrend des Kampfes.",
	L"Jede Heldenklasse erh\u00E4lt ihren Spezial Bonus &",
	L"Erh\u00F6ht Ihr Einkommen um 5000 Gold pro Tag. Steigert Angriff, Verteidigung, Zauberkraft und Wissen Ihrer Helden jeweils um 4. Erh\u00F6ht die Bewegungspunkte des Helden \u00FCber Land um 10%. Erh\u00F6ht die Kampfgeschwindkeit aller Einheiten um 2.",
	L"Erh\u00F6ht Ihr Einkommen um 5000 Gold pro Tag. Steigert Angriff, Verteidigung, Zauberkraft und Wissen Ihrer Helden jeweils um 4. Stattet die Truppen des Helden mit 50% magischer Resistenz aus und erlaubt es ihnen, ohne Abz\u00FCge f\u00FCr Reichweite oder Hindernisse zu schie\u00DFen.",
	L"Erh\u00F6ht Ihr Einkommen um 5000 Gold pro Tag. Steigert Angriff und Verteidigung Ihrer Helden um 4, Zauberkraft und Wissen um 6. Erh\u00F6ht die Effektivit\u00E4t von Beschw\u00F6rungs- und Wiederbelebungsspr\u00FCchen um 50%.",
	L"Erh\u00F6ht Ihr Einkommen um 5000 Gold pro Tag. Steigert Angriff und Verteidigung Ihrer Helden um 4, Zauberkraft und Wissen um 6. Regeneriert jeden Tag alle Zauberpunkte.",
	L"Erh\u00F6ht Ihr Einkommen um 5000 Gold pro Tag. Steigert Angriff und Verteidigung Ihrer Helden um 4, Zauberkraft und Wissen um 6. Erh\u00F6ht den Schaden aller zerst\u00F6rerischen Spr\u00FCche um 50%.",
	L"Erh\u00F6ht Ihr Einkommen um 5000 Gold pro Tag. Steigert Angriff, Verteidigung, Zauberkraft und Wissen Ihrer Helden jeweils um 4. Erh\u00F6ht Ihre Totenbeschw\u00F6rerfertigkeit um 15%. L\u00E4sst Tote als Vampire wiederauferstehen.",
	L"Erh\u00F6ht Ihr Einkommen um 5000 Gold pro Tag. Steigert Angriff, Verteidigung, Zauberkraft und Wissen Ihrer Helden jeweils um 4. Erh\u00F6ht die Bewegungspunkte des Helden \u00FCber Wasser um 40%. Erh\u00F6ht die Kampfgeschwindkeit aller Einheiten um 2.",
	L"Erh\u00F6ht Ihren Angriff um 2.",
	L"Erh\u00F6ht Ihre Verteidigung um 4 und die der Goblins um 3.",
	L"Erh\u00F6ht Ihre Zauberkraft um 2.",
	L"Versteckt Ihren Helden vor den anderen Spielern durch ein dauerhaftes Leichentuch.",
	L"Erh\u00F6ht Ihren Luftzauber um 50%.",
	L"Erh\u00F6ht Ihren Erdzauber um 50%.",
	L"Erh\u00F6ht Ihren Feuerzauber um 50%.",
	L"Erh\u00F6ht Ihren Wasserzauber um 50%.",
	L"Erh\u00F6ht Ihren Angriff um 1.",
	L"Erh\u00F6ht Ihr Einkommen um 250 Gold pro Tag. Erh\u00F6ht Ihren Angriff um 3.",
	L"Erh\u00F6ht Ihr Einkommen um 250 Gold pro Tag. Erh\u00F6ht Ihren Angriff um 3.",
	L"Erh\u00F6ht Ihr Einkommen um 250 Gold pro Tag. Erh\u00F6ht Ihre Verteidigung um 3.",
	L"Erh\u00F6ht Ihr Einkommen um 250 Gold pro Tag. Erh\u00F6ht Ihre Verteidigung um 3. Erh\u00F6ht Ihr Gl\u00FCck um 1.",
	L"Erh\u00F6ht Ihre Zauberkraft um 1.",
	L"Erh\u00F6ht Ihre Verteidigung um 2.",
	L"Erh\u00F6ht Ihre Verteidigung um 2.",
	L"Stellt t\u00E4glich 5 Zauberpunkte wieder her.",
	L"Erh\u00F6ht Ihren Angriff um 2.",
	L"Erh\u00F6ht Ihre Zauberkraft um 1.",
	L"Erh\u00F6ht Ihren Fernkampf um 15% und die Verteidigung Ihrer Sch\u00FCtzen um 3.",
	L"Erh\u00F6ht Ihre Verteidigung um 1.",
	L"Erh\u00F6ht Ihre Verteidigung und die der Goblins um 2.",
	L"Erh\u00F6ht Ihre Moral und Ihr Gl\u00FCck um 1.",
	L"Erh\u00F6ht Ihre Verteidigung um 2 und die der Zwerge um 4.",
	L"Erh\u00F6ht Ihre Verteidigung um 2.",
	L"Erh\u00F6ht Ihre Verteidigung um 2 und die der Oger um 4.",
	L"Unendliche Sch\u00FCsse f\u00FCr Fernk\u00E4mpfer.",
	L"Erh\u00F6ht Ihren und den Angriff der Zwerge um 3.",
	L"Erh\u00F6ht Ihre Verteidigung um 2 und Ihre Bewegungspunkte um 15%.",
	L"Erh\u00F6ht Ihre Verteidigung um 2 und verringert die gegnerische Moral um 2.",
	L"Erh\u00F6ht Ihre Verteidigung um 3 und verringert die gegnerische Moral um 1.",
	L"Erh\u00F6ht Ihre Verteidigung um 3 und verringert Ihre Moral um 1.",
	L"Erh\u00F6ht Ihre Zauberkraft um 1 und Ihren Schaden um 15%.",
	L"Der Fernkampfschaden wird nicht verringert.",
	L"Erh\u00F6ht Ihre Bewegungspunkte auf Land um 25 Punkte.",
	L"Verringert die Geschwindigkeit der gegnerischen Einheiten im Kampf um 2.",
	L"Wenige",
	L"Mehrere",
	L"Meute",
	L"Viele",
	L"Horde",
	L"Pulk",
	L"Schwarm",
	L"Legion",
	L"nur wenige",
	L"Mehrere",
	L"eine Meute",
	L"Viele",
	L"eine Horde",
	L"ein Pulk",
	L"ein Schwarm",
	L"eine Legion",
	L"Bauer",
	L"Bauern",
	L"Bauern",
	L"Bogesch\u00FCtze",
	L"Bogesch\u00FCtzen",
	L"Bogesch\u00FCtzen",
	L"Pikenier",
	L"Pikeniere",
	L"Pikeniere",
	L"M\u00F6nch",
	L"M\u00F6nche",
	L"M\u00F6nche",
	L"Kavallerist",
	L"Kavalleristen",
	L"Kavalleristen",
	L"Paladin",
	L"Paladine",
	L"Paladine",
	L"Goblin",
	L"Goblins",
	L"Goblins",
	L"Ork",
	L"Orks",
	L"Orks",
	L"Wolfsreiter",
	L"Wolfsreiter",
	L"Wolfsreiter",
	L"Oger",
	L"Oger",
	L"Oger",
	L"Troll",
	L"Trolle",
	L"Trolle",
	L"Zyklop",
	L"Zyklopen",
	L"Zyklopen",
	L"Junger Magier",
	L"Junge Magier",
	L"Junge Magier",
	L"Weisser Wolf",
	L"Weissen W\u00F6lfe",
	L"Weissen W\u00F6lfe",
	L"R\u00FCstung",
	L"R\u00FCstungen",
	L"R\u00FCstungen",
	L"Pegasus",
	L"Pegasi",
	L"Pegasi",
	L"Magier",
	L"Magier",
	L"Magier",
	L"Thor",
	L"Thore",
	L"Thore",
	L"Zentaurus",
	L"Zentauren",
	L"Zentauren",
	L"Wasserspeier",
	L"Wasserspeier",
	L"Wasserspeier",
	L"Greif",
	L"Greifen",
	L"Greifen",
	L"Minotaurus",
	L"Minotauren",
	L"Minotauren",
	L"Hydra",
	L"Hydren",
	L"Hydren",
	L"Roter Drache",
	L"Rote Drachen",
	L"Rote Drachen",
	L"Fee",
	L"Feen",
	L"Feen",
	L"Zwerg",
	L"Zwerge",
	L"Zwerge",
	L"Elf",
	L"Elfen",
	L"Elfen",
	L"Druide",
	L"Druiden",
	L"Druiden",
	L"Einhorn",
	L"Einh\u00F6rner",
	L"Einh\u00F6rner",
	L"Phoenix",
	L"Phoenixe",
	L"Phoenixe",
	L"Skelett",
	L"Skelette",
	L"Skelette",
	L"Zombie",
	L"Zombies",
	L"Zombies",
	L"Lich",
	L"Liche",
	L"Liche",
	L"Vampir",
	L"Vampire",
	L"Vampire",
	L"Schwarzer Ritter",
	L"Schwarze Ritter",
	L"Schwarze Ritter",
	L"Plage",
	L"Plagen",
	L"Plagen",
	L"Hunter",
	L"Hunters",
	L"Hunters",
	L"Blacksmith",
	L"Blacksmiths",
	L"Blacksmiths",
	L"Mercenary",
	L"Mercenaries",
	L"Mercenaries",
	L"Witch",
	L"Witches",
	L"Witches",
	L"Magus",
	L"Magi",
	L"Magi",
	L"Vityaz",
	L"Vityazes",
	L"Vityazes",
	L"Militia",
	L"Militia",
	L"Militia",
	L"Citizen",
	L"Citizens",
	L"Citizens",
	L"Crossbowman",
	L"Crossbowmen",
	L"Crossbowmen",
	L"Sharpshooter",
	L"Sharpshooters",
	L"Sharpshooters",
	L"Heavy Pikeman",
	L"Heavy Pikemen",
	L"Heavy Pikemen",
	L"Halberdier",
	L"Halberdiers",
	L"Halberdiers",
	L"Exorcist",
	L"Exorcists",
	L"Exorcists",
	L"Bishop",
	L"Bishops",
	L"Bishops",
	L"Heavy Cavalry",
	L"Heavy Cavalries",
	L"Heavy Cavalries",
	L"Knight",
	L"Knights",
	L"Knights",
	L"Crusader",
	L"Crusaders",
	L"Crusaders",
	L"Holy Warrior",
	L"Holy Warriors",
	L"Holy Warriors",
	L"Contagious Goblin",
	L"Contagious Goblins",
	L"Contagious Goblins",
	L"Goblin Warrior",
	L"Goblin Warriors",
	L"Goblin Warriors",
	L"Orc Chief",
	L"Orc Chiefs",
	L"Orc Chiefs",
	L"Orc Warrior",
	L"Orc Warriors",
	L"Orc Warriors",
	L"Wild Warg",
	L"Wild Wargs",
	L"Wild Wargs",
	L"Warg Warrior",
	L"Warg Warriors",
	L"Warg Warriors",
	L"Ogre Chief",
	L"Ogre Chiefs",
	L"Ogre Chiefs",
	L"Ogre Shaman",
	L"Ogre Shamans",
	L"Ogre Shamans",
	L"Ballista Troll",
	L"Ballista Trolls",
	L"Ballista Trolls",
	L"Troll Shaman",
	L"Troll Shamans",
	L"Troll Shamans",
	L"Ancient Cyclops",
	L"Ancient Cyclopes",
	L"Ancient Cyclopes",
	L"Dire Cyclops",
	L"Dire Cyclopes",
	L"Dire Cyclopes",
	L"Neophyte",
	L"Neophytes",
	L"Neophytes",
	L"Mage Apprentice",
	L"Mage Apprentices",
	L"Mage Apprentices",
	L"Red Wolf",
	L"Red Wolves",
	L"Red Wolves",
	L"Two-Headed Wolf",
	L"Two-Headed Wolves",
	L"Two-Headed Wolves",
	L"Steel Guard",
	L"Steel Guards",
	L"Steel Guards",
	L"War Machine",
	L"War Machines",
	L"War Machines",
	L"Royal Pegasus",
	L"Royal Pegasi",
	L"Royal Pegasi",
	L"Blinding Pegasus",
	L"Blinding Pegasi",
	L"Blinding Pegasi",
	L"Air Mage",
	L"Air Mages",
	L"Air Mages",
	L"Prophet",
	L"Prophets",
	L"Prophets",
	L"Legend",
	L"Legends",
	L"Legends",
	L"Demigod",
	L"Demigods",
	L"Demigods",
	L"Centaur Ranger",
	L"Centaur Rangers",
	L"Centaur Rangers",
	L"Centaur Lord",
	L"Centaur Lords",
	L"Centaur Lords",
	L"Obsidian Gargoyle",
	L"Obsidian Gargoyles",
	L"Obsidian Gargoyles",
	L"Stone Gargoyle",
	L"Stone Gargoyles",
	L"Stone Gargoyles",
	L"Snake Griffin",
	L"Snake Griffins",
	L"Snake Griffins",
	L"Royal Griffin",
	L"Royal Griffins",
	L"Royal Griffins",
	L"Minotaur Reaper",
	L"Minotaur Reapers",
	L"Minotaur Reapers",
	L"Dire Minotaur",
	L"Dire Minotaurs",
	L"Dire Minotaurs",
	L"Poisonous Hydra",
	L"Poisonous Hydras",
	L"Poisonous Hydras",
	L"Ancient Hydra",
	L"Ancient Hydras",
	L"Ancient Hydras",
	L"Fire Dragon",
	L"Fire Dragons",
	L"Fire Dragons",
	L"Black Dragon",
	L"Black Dragons",
	L"Black Dragons",
	L"Elusive Sprite",
	L"Elusive Sprites",
	L"Elusive Sprites",
	L"Poisonous Sprite",
	L"Poisonous Sprites",
	L"Poisonous Sprites",
	L"Axe Hurlers",
	L"Axe Hurlers",
	L"Axe Hurlers",
	L"Berzerker",
	L"Berzerkers",
	L"Berzerkers",
	L"Elf Ranger",
	L"Elf Rangers",
	L"Elf Rangers",
	L"Elf Hunter",
	L"Elf Hunters",
	L"Elf Hunters",
	L"Grand Druid",
	L"Grand Druids",
	L"Grand Druids",
	L"Outcast",
	L"Outcasts",
	L"Outcasts",
	L"Royal Unicorn",
	L"Royal Unicorns",
	L"Royal Unicorns",
	L"Ghost Unicorn",
	L"Ghost Unicorns",
	L"Ghost Unicorns",
	L"Phoenix",
	L"Phoenixes",
	L"Phoenixes",
	L"Magic Firebird",
	L"Magic Firebirds",
	L"Magic Firebirds",
	L"Skeleton Archer",
	L"Skeleton Archers",
	L"Skeleton Archers",
	L"Skeleton Warrior",
	L"Skeleton Warriors",
	L"Skeleton Warriors",
	L"Contagious Zombie",
	L"Contagious Zombies",
	L"Contagious Zombies",
	L"Tough Zombie",
	L"Tough Zombies",
	L"Tough Zombies",
	L"Archlich",
	L"Archliches",
	L"Archliches",
	L"Powerful Lich",
	L"Powerful Liches",
	L"Powerful Liches",
	L"Nosferatu",
	L"Nosferatus",
	L"Nosferatus",
	L"Vampire Lord",
	L"Vampire Lords",
	L"Vampire Lords",
	L"Death Knight",
	L"Death Knights",
	L"Death Knights",
	L"Black Grail Knight",
	L"Black Grail Knights",
	L"Black Grail Knights",
	L"Death",
	L"Deaths",
	L"Deaths",
	L"Fear",
	L"Fears",
	L"Fears",
	L"Old Hunter",
	L"Old Hunters",
	L"Old Hunters",
	L"Mature Hunter",
	L"Mature Hunters",
	L"Mature Hunters",
	L"Noble Blacksmith",
	L"Noble Blacksmiths",
	L"Noble Blacksmiths",
	L"Werewolf",
	L"Werewolves",
	L"Werewolves",
	L"Boyarin",
	L"Boyarins",
	L"Boyarins",
	L"Royal Guard",
	L"Royal Guards",
	L"Royal Guards",
	L"Enchanter",
	L"Enchanters",
	L"Enchanters",
	L"Yaga",
	L"Yagas",
	L"Yagas",
	L"Leshiy",
	L"Leshiys",
	L"Leshiys",
	L"Great Magus",
	L"Great Magi",
	L"Great Magi",
	L"Bogatyr",
	L"Bogatyrs",
	L"Bogatyrs",
	L"Volot",
	L"Volots",
	L"Volots",
	L"Dieb",
	L"Diebe",
	L"Diebe",
	L"Nomade",
	L"Nomaden",
	L"Nomaden",
	L"Geist",
	L"Geister",
	L"Geister",
	L"Dschin",
	L"Dschinis",
	L"Dschinis",
	L"Medusa",
	L"Medusen",
	L"Medusen",
	L"Erdelement",
	L"Erdelemente",
	L"Erdelemente",
	L"Luftelement",
	L"Luftelemente",
	L"Luftelemente",
	L"Feuerlement",
	L"Feuerlemente",
	L"Feuerelemente",
	L"Wasserelement",
	L"Wasserelemente",
	L"Wasserelemente",
	L"Tatar Archer",
	L"Tatar Archers",
	L"Tatar Archers",
	L"Gorynych",
	L"Gorynyches",
	L"Gorynyches",
	L"Matsch",
	L"Mauer",
	L"Turm",
	L"Br\u00FCcke",
	L"Katapult",
	L"Feuert zwei Sch\u00FCsse in jedem Fernkampfangriff",
	L"Teilt zwei Schl\u00E4ge pro Angriff aus",
	L"Erleidet keinen Nachteil im Nahkampf",
	L"Keine feindliche Vergeltung",
	L"Counterstrikes everyone",
	L"Zwei Hex-Feld Angriffe",
	L"Greift alle angrenzenden feindlichen Truppen an",
	L"Attacks non-undead creatures near target",
	L"Untote Kreatur",
	L"Leblose Kreatur",
	L"Regeneriert Lebenspunkte in jeder Kampfrunde",
	L"+5% damage per hex traveled to target",
	L"Immun gegen Luftmagiezauber",
	L"Immun gegen Erdmagiezauber",
	L"Immun gegen Feuermagiezauber",
	L"Immun gegen Wassermagiezauber",
	L"40%, \u017Ee jednotka odol\u00E1 nepriatelsk\u00E9mu k\u00FAzlu",
	L"Nimmt nur 25% Schaden von Zauberangriffen",
	L"Get\u00F6tete Einheiten werden zu Geistern",
	L"10% chance of destroying half of the target",
	L"Resurrects itself by draining health from the enemy",
	L"Decreases enemy morale by 1",
	L"Poison damage for 3 turns",
	L"+100% against any undeads",
	L"When quantity falls below 50%, bloodlust is cast.",
	L"Curses any enemy",
	L"20% chance to blind the enemy.",
	L"Generates +1 gold/day",
	L"Returns after attack",
	L"Castellatus",
	L"Starkmauer",
	L"Kanan",
	L"Linderhoff",
	L"Whitemoon",
	L"Yaroslavl",
	L"Middleheim",
	L"Brettonia",
	L"Alexandretta",
	L"Whitestone",
	L"Claxton",
	L"Armitage",
	L"Shinnon",
	L"Gateway",
	L"Dunwall",
	L"Kildare",
	L"Kragg",
	L"Jimstadt",
	L"Hartgrim",
	L"Sandflash",
	L"Morganheim",
	L"Cragmoor",
	L"Dragonspire",
	L"Battlement",
	L"Bocc",
	L"Stropkov",
	L"Tormina",
	L"Dolere",
	L"Rockwarren",
	L"Strongglen",
	L"Kruber",
	L"Rovener",
	L"Tutanberg",
	L"Stronggale",
	L"Corona",
	L"Silverwing",
	L"Facture",
	L"Cloudfire",
	L"Cloudspire",
	L"Equinox",
	L"Athenaeum",
	L"Valtara",
	L"Tirith",
	L"Fallen Star",
	L"Mystos",
	L"Ayer",
	L"Silverspire",
	L"Manufactury",
	L"Veks",
	L"Sorrow Crown",
	L"Chillwater",
	L"Deepshadow",
	L"Darkhold",
	L"Blindroot",
	L"Shadowden",
	L"Scar",
	L"Malev",
	L"Castigare",
	L"Dukered",
	L"Shade",
	L"Evernight",
	L"Darkburrow",
	L"Lost Hold",
	L"Coldshadow",
	L"Starmino",
	L"Grigorov",
	L"Sigman",
	L"Still Water",
	L"Elfwind",
	L"Sebian",
	L"Ceiliedgh",
	L"Gladeroot",
	L"Avalon",
	L"Rainhaven",
	L"Strongglen",
	L"Marishen",
	L"Bath'iere",
	L"",
	L"Emerald Moor",
	L"Wild Willow",
	L"Haunt's Wind",
	L"Cessacioun",
	L"Agony",
	L"Victorash",
	L"Terminus",
	L"Lun\u00EDk IX",
	L"Sandro",
	L"Grave Raven",
	L"Dark Cloud",
	L"Coldsoul",
	L"Letanovce",
	L"Dark Eternal",
	L"Ghostwind",
	L"Blight",
	L"Shady Sands",
	L"Wolfengrott",
	L"Hedinsey",
	L"Saxon",
	L"Knan-kun",
	L"Babylon",
	L"Blackmoon",
	L"Trag",
	L"Trondheim",
	L"Krondor",
	L"Al-qaar",
	L"Blackstone",
	L"Onyx",
	L"Hermit",
	L"Stargate",
	L"Tiger Eye",
	L"Cotulla",
	L"Dalgebra",
	L"Magischer Pfeil",
	L"Schutz vor Erde",
	L"Eile",
	L"Schild",
	L"St\u00F6rstrahl",
	L"Blitz",
	L"Pr\u00E4zision",
	L"Luftschild",
	L"Heiliges Wort",
	L"Gegenschlag",
	L"Auferstehung",
	L"Luftelementarwesen",
	L"Schutz vor Luft",
	L"Verlangsamung",
	L"Steinhaut",
	L"Visionen",
	L"Erdbeben",
	L"Verzweiflung",
	L"Meteorschauer",
	L"Stadttor",
	L"Implosion",
	L"Erdelementarwesen",
	L"Blutdurst",
	L"Schutz vor Wasser",
	L"Fluch",
	L"Blenden",
	L"Schw\u00E4che",
	L"Todeswelle",
	L"Feuerball",
	L"Ungl\u00FCck",
	L"Tote beleben",
	L"Feuersto\u00DF",
	L"Armageddon",
	L"Feuerelementarwesen",
	L"Segen",
	L"Schutz vor Feuer",
	L"Aufheben",
	L"Heilung",
	L"K\u00E4ltestrahl",
	L"Gl\u00FCckspilz",
	L"Frohsinn",
	L"Eisring",
	L"Anti-Magie",
	L"Gebet",
	L"Wasserelementarwesen",
	L"Feen beschw\u00F6ren",
	L"Poisoned",
	L"Erzeugt einen magischen Pfeil, der die gew\u00E4hlte Einheit attackiert (St\u00E4rke*10).",
	L"Erzeugt einen magischen Pfeil, der die gew\u00E4hlte Einheit attackiert (St\u00E4rke*10).",
	L"Erzeugt einen magischen Pfeil, der die gew\u00E4hlte Einheit attackiert (St\u00E4rke*12).",
	L"Erzeugt einen magischen Pfeil, der die gew\u00E4hlte Einheit attackiert (St\u00E4rke*15).",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der verursachte  Schaden von Erdzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der verursachte  Schaden von Erdzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der verursachte  Schaden von Erdzaubern um 50% reduziert wird.",
	L"Sch\u00FCtzt alle befreundeten Einheiten, indem der Schaden des Erdzaubers um 50% reduziert wird.",
	L"Steigert die Geschwindigkeit der gew\u00E4hlten Einheit um 3.",
	L"Steigert die Geschwindigkeit der gew\u00E4hlten Einheit um 3.",
	L"Steigert die Geschwindigkeit der gew\u00E4hlten Einheit um 5.",
	L"Steigert die Geschwindigkeit aller eigenen Einheiten um 5.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Nahkampf-Angriffen um 15% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Nahkampf-Angriffen um 15% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Nahkampf-Angriffen um 30% reduziert wird.",
	L"Sch\u00FCtzt alle eigenen Einheiten, indem der Schaden von Nahkampf-Angriffen um 30% reduziert wird.",
	L"Verringert die Verteidigung der gew\u00E4hlten feindlichen Einheit um 3. Eine einzelne Einheit kann mehrfach Ziel des Zaubers sein.",
	L"Verringert die Verteidigung der gew\u00E4hlten feindlichen Einheit um 3. Eine einzelne Einheit kann mehrfach Ziel des Zaubers sein.",
	L"Verringert die Verteidigung der gew\u00E4hlten feindlichen Einheit um 4. Eine einzelne Einheit kann mehrfach Ziel des Zaubers sein.",
	L"Verringert die Verteidigung der gew\u00E4hlten feindlichen Einheit um 5. Eine einzelne Einheit kann mehrfach Ziel des Zaubers sein.",
	L"Erzeugt einen Blitz, der die gew\u00E4hlte Einheit angreift (St\u00E4rke*25).",
	L"Erzeugt einen Blitz, der die gew\u00E4hlte Einheit angreift (St\u00E4rke*25).",
	L"Erzeugt einen Blitz, der die gew\u00E4hlte Einheit angreift (St\u00E4rke*27).",
	L"Erzeugt einen Blitz, der die gew\u00E4hlte Einheit angreift (St\u00E4rke*30).",
	L"Steigert den Fernkampfschaden, den eine gew\u00E4hlte Einheit verursacht, um 3.",
	L"Steigert den Fernkampfschaden, den eine gew\u00E4hlte Einheit verursacht, um 3.",
	L"Steigert den Fernkampfschaden, den eine gew\u00E4hlte Einheit verursacht, um 5.",
	L"Steigert den Fernkampfschaden aller befreundeten Einheiten um 5.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Fernkampf-Angriffen um 25% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Fernkampf-Angriffen um 25% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Fernkampf-Angriffen um 50% reduziert wird.",
	L"Sch\u00FCtzt alle befreundeten Einheiten, indem der Schaden von Fernkampf-Angriffen um 50% reduziert wird.",
	L"Versucht alle untoten Kreaturen auf dem Schlachtfeld zu vernichten (St\u00E4rke*10).",
	L"Versucht alle untoten Kreaturen auf dem Schlachtfeld zu vernichten (St\u00E4rke*10).",
	L"Versucht alle untoten Kreaturen auf dem Schlachtfeld zu vernichten (St\u00E4rke*12).",
	L"Versucht alle untoten Kreaturen auf dem Schlachtfeld zu vernichten (St\u00E4rke*15).",
	L"Die ausgew\u00E4hlte Einheit revangiert sich gegen einen zus\u00E4tzlichen Angriff jede Runde",
	L"Die ausgew\u00E4hlte Einheit revangiert sich gegen einen zus\u00E4tzlichen Angriff jede Runde",
	L"Die ausgew\u00E4hlte Einheit revangiert sich gegen zwei zus\u00E4tzliche Angriffe jede Runde",
	L"Die ausgew\u00E4hlte Einheit revangiert sich gegen drei zus\u00E4tzliche Angriffe jede Runde",
	L"Belebt eine Einheite in der gew\u00E4hlten Gruppe wieder, durch die permanente R\u00FCckgabe einer bestimmten Anzahl an Trefferpunkten (St\u00E4rke*40).",
	L"Belebt eine Einheite in der gew\u00E4hlten Gruppe wieder, durch die permanente R\u00FCckgabe einer bestimmten Anzahl an Trefferpunkten (St\u00E4rke*40).",
	L"Belebt eine Einheite in der gew\u00E4hlten Gruppe wieder, durch die permanente R\u00FCckgabe einer bestimmten Anzahl an Trefferpunkten (St\u00E4rke*45).",
	L"Belebt eine Einheite in der gew\u00E4hlten Gruppe wieder, durch die permanente R\u00FCckgabe einer bestimmten Anzahl an Trefferpunkten (St\u00E4rke*50).",
	L"Erlaubt es Ihnen, ein Luftelementarwesen herbei zu rufen (St\u00E4rke*3). Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Luftelementarwesen herbei zu rufen (St\u00E4rke*3). Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Luftelementarwesen herbei zu rufen (St\u00E4rke*4). Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Luftelementarwesen herbei zu rufen (St\u00E4rke*5). Einmal gesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Luftzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Luftzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Luftzaubern um 50% reduziert wird.",
	L"Sch\u00FCtzt alle eigenen Einheiten, indem der Schaden von Luftzaubern um 50% reduziert wird.",
	L"Verringert die Geschwindigkeit der gew\u00E4hlten feindlichen Einheit um 3.",
	L"Verringert die Geschwindigkeit der gew\u00E4hlten feindlichen Einheit um 3.",
	L"Verringert die Geschwindigkeit der gew\u00E4hlten feindlichen Einheit um 6.",
	L"Verringert die Geschwindigkeit aller feindlichen Einheiten um 6.",
	L"Steigert die Verteidigungsst\u00E4rke der gew\u00E4hlten Einheit um 3.",
	L"Steigert die Verteidigungsst\u00E4rke der gew\u00E4hlten Einheit um 3.",
	L"Steigert die Verteidigungsst\u00E4rke der gew\u00E4hlten Einheit um 6.",
	L"Erh\u00F6ht die Verteidigungsst\u00E4rke aller befreundeten Einheiten um 6.",
	L"Gibt Ihnen eine genaue Anzahl der umherwandernden Monster und sagt Ihnen, ob Sie Ihrem Helden folgen m\u00F6chten. Erlaubt Ihnen die Prim\u00E4ren Fertigkeitsstatistiken und Anzahl eines nahen feindlichen Helden, Kreaturentyp einzusehen als wenn es Ihr eigener Held w\u00E4re, sowie die Statistiken einer nahegelegene Stadt einzusehen.",
	L"Gibt Ihnen eine genaue Anzahl der umherwandernden Monster und sagt Ihnen, ob Sie Ihrem Helden folgen m\u00F6chten. Erlaubt Ihnen die Prim\u00E4ren Fertigkeitsstatistiken und Anzahl eines nahen feindlichen Helden, Kreaturentyp einzusehen als wenn es Ihr eigener Held w\u00E4re, sowie die Statistiken einer nahegelegene Stadt einzusehen.",
	L"Gibt Ihnen eine genaue Anzahl der umherwandernden Monster und sagt Ihnen, ob Sie Ihrem Helden folgen m\u00F6chten. Erlaubt Ihnen die Prim\u00E4ren Fertigkeitsstatistiken und Anzahl eines nahen feindlichen Helden, Kreaturentyp einzusehen als wenn es Ihr eigener Held w\u00E4re, sowie die Statistiken einer nahegelegene Stadt einzusehen.",
	L"Gibt Ihnen eine genaue Anzahl der umherwandernden Monster und sagt Ihnen, ob Sie Ihrem Helden folgen m\u00F6chten. Erlaubt Ihnen die Prim\u00E4ren Fertigkeitsstatistiken und Anzahleines nahen feindlichen Helden, Kreaturentyp einzusehen als wenn es Ihr eigener Held w\u00E4re, sowie die Statistiken einer nahegelegene Stadt einzusehen.",
	L"Besch\u00E4digt im Kampf wahllos zwei Abschnitte der Burgmauer",
	L"Besch\u00E4digt im Kampf wahllos zwei Abschnitte der Burgmauer",
	L", {Besch\u00E4digt im Kampf wahllos drei Abschnitte der Burgmauer",
	L"Besch\u00E4digt im Kampf wahllos vier Abschnitte der Burgmauer",
	L"Veringert die Moral der gew\u00E4hlten feindlichen Einheit um 1.",
	L"Veringert die Moral der gew\u00E4hlten feindlichen Einheit um 1.",
	L"Veringert die Moral der gew\u00E4hlten feindlichen Einheit um 2.",
	L"Veringert die Moral aller feindlichen Einheiten um 2.",
	L"Verursacht einen Meteorschauer auf das gew\u00E4hlte Ziel und jede angrenzende Einheit (St\u00E4rke*25).",
	L"Verursacht einen Meteorschauer auf das gew\u00E4hlte Ziel und jede angrenzende Einheit (St\u00E4rke*25).",
	L"Verursacht einen Meteorschauer auf das gew\u00E4hlte Ziel und jede angrenzende Einheit (St\u00E4rke*27).",
	L"Verursacht einen Meteorschauer auf das gew\u00E4hlte Ziel und jede angrenzende Einheit (St\u00E4rke*30).",
	L"Teleportiert Ihren Helden in die n\u00E4chste eigene Stadt. Die Stadt darf nicht besetzt sein.",
	L"Teleportiert Ihren Helden in die n\u00E4chste eigene Stadt. Die Stadt darf nicht besetzt sein.",
	L"Teleportiert Ihren Helden in jede eigene Stadt. Die Stadt darf nicht besetzt sein.",
	L"Teleportiert Ihren Helden in jede eigene Stadt. Die Stadt darf nicht besetzt sein.",
	L"F\u00FCgt einer gew\u00E4hlten feindlichen Einheit massiven Schaden zu (St\u00E4rke*70).",
	L"F\u00FCgt einer gew\u00E4hlten feindlichen Einheit massiven Schaden zu (St\u00E4rke*70).",
	L"F\u00FCgt einer gew\u00E4hlten feindlichen Einheit massiven Schaden zu (St\u00E4rke*75).",
	L"F\u00FCgt einer gew\u00E4hlten feindlichen Einheit massiven Schaden zu (St\u00E4rke*80).",
	L"Erlaubt es Ihnen, ein Erdelementarwesen herbeizurufen (St\u00E4rke*3). Einmal ausgesprochen kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Erdelementarwesen herbeizurufen (St\u00E4rke*3). Einmal ausgesprochen kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Erdelementarwesen herbeizurufen (St\u00E4rke*4). Einmal ausgesprochen kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Erdelementarwesen herbeizurufen (St\u00E4rke*5). Einmal ausgesprochen kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Steigert den Nahkampfschaden, der durch die gew\u00E4hlte Einheit verursacht wird um 3.",
	L"Steigert den Nahkampfschaden, der durch die gew\u00E4hlte Einheit verursacht wird um 3.",
	L"Steigert den Nahkampfschaden, der durch die gew\u00E4hlte Einheit verursacht wird um 6.",
	L"Steigert den Nahkampfschaden, der durch alle feundlichen Einheiten verursacht wird um 6.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Wasser Zaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Wasser Zaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Wasser Zaubern um 50% reduziert wird.",
	L"Sch\u00FCtzt alle freundlichen Einheiten, indem der Schaden von Wasser Zaubern um 50% reduziert wird.",
	L"Bewirkt, dass die gew\u00E4hlte feindliche Einheit im Kampf nur geringen Schaden verursacht.",
	L"Bewirkt, dass die gew\u00E4hlte feindliche Einheit im Kampf nur geringen Schaden verursacht.",
	L"Bewirkt, dass die gew\u00E4hlte feindliche Einheit im Kampf nur geringen Schaden verursacht.",
	L"Bewirkt, dass alle feindlichen Einheiten im Kampf nur geringen Schaden verursachen.",
	L"Blendet eine Kreatur so, dass sie sich nicht mehr bewegen kann und einen Gegenschlag nur mit der H\u00E4lfte der normalen Angriffsst\u00E4rke ausf\u00FChren kann. Blindheit dauert an bis die Einheit angegriffen oder beseitigt wurde.",
	L"Blendet eine Kreatur so, dass sie sich nicht mehr bewegen kann und einen Gegenschlag nur mit der H\u00E4lfte der normalen Angriffsst\u00E4rke ausf\u00FChren kann. Blindheit dauert an bis die Einheit angegriffen oder beseitigt wurde.",
	L"Blendet eine Kreatur so, dass sie sich nicht mehr bewegen kann und einen Gegenschlag nur mit einem Viertel der normalen Angriffsst\u00E4rke ausf\u00FChren kann. Blindheit dauert an bis die Einheit angegriffen oder beseitigt wurde.",
	L"Blendet eine Kreatur so, dass sie sich nicht mehr bewegen und keinen Gegenschlag mehr ausf\u00FChren kann. Blindheit dauert an bis die Einheit angegriffen oder beseitigt wurde.",
	L"Veringert die Angriffs-St\u00E4rke der gew\u00E4hlten feindlichen Einheit um 3.",
	L"Veringert die Angriffs-St\u00E4rke der gew\u00E4hlten feindlichen Einheit um 3.",
	L"Veringert die Angriffs-St\u00E4rke der gew\u00E4hlten feindlichen Einheit um 6.",
	L"Veringert die Angriffs-St\u00E4rke aller feindlichen Einheiten um 6.",
	L"Sendet eine Welle des Todes \u00FCber das Schlachtfeld, die allen lebendigen Einheiten Schaden zuf\u00FCgt (St\u00E4rke*5).",
	L"Sendet eine Welle des Todes \u00FCber das Schlachtfeld, die allen lebendigen Einheiten Schaden zuf\u00FCgt (St\u00E4rke*5).",
	L"Sendet eine Welle des Todes \u00FCber das Schlachtfeld, die allen nicht untoten Einheiten Schaden zuf\u00FCgt (St\u00E4rke*7).",
	L"Sendet eine Welle des Todes \u00FCber das Schlachtfeld, die allen lebendigen Einheiten Schaden zuf\u00FCgt (St\u00E4rke*10).",
	L"Bewirkt, dass das gew\u00E4hlte Ziel in Flammen aufgeht und Feuerschaden am Ziel und jeder angrenzenden Einheit verursacht (St\u00E4rke*15).",
	L"Bewirkt, dass das gew\u00E4hlte Ziel in Flammen aufgeht und Feuerschaden am Ziel und jeder angrenzenden Einheit verursacht (St\u00E4rke*15).",
	L"Bewirkt, dass das gew\u00E4hlte Ziel in Flammen aufgeht und Feuerschaden am Ziel und jeder angrenzenden Einheit verursacht (St\u00E4rke*17).",
	L"Bewirkt, dass das gew\u00E4hlte Ziel in Flammen aufgeht und Feuerschaden am Ziel und jeder angrenzenden Einheit verursacht (St\u00E4rke*20).",
	L"Veringert das Gl\u00FCck der gew\u00E4hlten feindlichen Einheit um 1.",
	L"Veringert das Gl\u00FCck der gew\u00E4hlten feindlichen Einheit um 1.",
	L"Veringert das Gl\u00FCck der gew\u00E4hlten feindlichen Einheit um 2.",
	L"Veringert das Gl\u00FCck aller feindlichen Einheiten um 2.",
	L"Reanimiert jeden Untoten, indem der gew\u00E4hlten Gruppe permanent eine bestimmte Anzahl an Trefferpunkten zur\u00FCck gegeben wird (St\u00E4rke*40).",
	L"Reanimiert jeden Untoten, indem der gew\u00E4hlten Gruppe permanent eine bestimmte Anzahl an Trefferpunkten zur\u00FCck gegeben wird (St\u00E4rke*40).",
	L"Reanimiert jeden Untoten, indem der gew\u00E4hlten Gruppe permanent eine bestimmte Anzahl an Trefferpunkten zur\u00FCck gegeben wird (St\u00E4rke*45).",
	L"Reanimiert jeden Untoten, indem der gew\u00E4hlten Gruppe permanent eine bestimmte Anzahl an Trefferpunkten zur\u00FCck gegeben wird (St\u00E4rke*50).",
	L"Bewirkt einen gewaltigen Feuersto\u00DF, der das gew\u00E4hlte Ziel angreift (St\u00E4rke*15). Sei nicht in der N\u00E4he wenn es losgeht!",
	L"Bewirkt einen gewaltigen Feuersto\u00DF, der das gew\u00E4hlte Ziel angreift (St\u00E4rke*15). Sei nicht in der N\u00E4he wenn es losgeht!",
	L"Bewirkt einen gewaltigen Feuersto\u00DF, der das gew\u00E4hlte Ziel angreift (St\u00E4rke*17). Sei nicht in der N\u00E4he wenn es losgeht!",
	L"Bewirkt einen gewaltigen Feuersto\u00DF, der das gew\u00E4hlte Ziel angreift (St\u00E4rke*20). Sei nicht in der N\u00E4he wenn es losgeht!",
	L"Feuer regnet auf das Schlachtfeld. Alle Einheiten werden verwundet (St\u00E4rke*40).",
	L"Feuer regnet auf das Schlachtfeld. Alle Einheiten werden verwundet (St\u00E4rke*40).",
	L"Feuer regnet  auf das Schlachtfeld. Alle Einheiten werden verwundet (St\u00E4rke*45).",
	L"Feuer regnet auf das Schlachtfeld. Alle Einheiten werden verwundet (St\u00E4rke*50).",
	L"Erlaubt es Ihnen, ein Feuerelementarwesen herbei zu rufen (St\u00E4rke*3), {Einmal gesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Feuerelementarwesen herbei zu rufen (St\u00E4rke*3), {Einmal gesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Feuerelementarwesen herbei zu rufen (St\u00E4rke*4), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Feuerelementarwesen herbei zu rufen (St\u00E4rke*5), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Bewirkt, dass die gew\u00E4hlte Einheit auf dem Schlachtfeld maximalen Schaden verursacht.",
	L"Bewirkt, dass die gew\u00E4hlte Einheit auf dem Schlachtfeld maximalen Schaden verursacht.",
	L"Bewirkt, dass die gew\u00E4hlte Einheit auf dem Schlachtfeld maximalen Schaden verursacht.",
	L"Bewirkt, dass alle eigenen Einheiten auf dem Schlachtfeld maximalen Schaden verursachen.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden des Feuerzaubers um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Feuerzaubern um 30% reduziert wird.",
	L"Sch\u00FCtzt die gew\u00E4hlte Einheit, indem der Schaden von Feuerzaubern um 50% reduziert wird.",
	L"Sch\u00FCtzt alle eigenen Einheiten, indem der Schaden von Feuerzaubern um 50% reduziert wird.",
	L"Entfernt alle Zauber Auswirkungen von der gew\u00E4hlten eigenen Einheit.",
	L"Entfernt alle Zauber Auswirkungen von der gew\u00E4hlten eigenen Einheit.",
	L"Entfernt alle Zauber Auswirkungen von der gew\u00E4hlten eigenen oder feindlichen Einheit.",
	L"Entfernt alle Zauber Auswirkungen von allen Einheiten auf dem Schlachtfeld.",
	L"Entfernt alle negativen Zauberauswirkungen und heilt eine kleine Menge an Trefferpunkten der gew\u00E4hlten Einheit (St\u00E4rke*5).",
	L"Entfernt alle negativen Zauberauswirkungen und heilt eine kleine Menge an Trefferpunkten der gew\u00E4hlten Einheit (St\u00E4rke*5).",
	L"Entfernt alle negativen Zauberauswirkungen und heilt eine kleine Menge an Trefferpunkten der gew\u00E4hlten Einheit (St\u00E4rke*7).",
	L"Entfernt alle negativen Zauber Auswirkungen und heilt eine kleine Menge an Trefferpunkten aller befreundeten Einheiten (St\u00E4rke*7).",
	L"Verzehrt die K\u00F6rperw\u00E4rme der gew\u00E4hlten feindlichen Einheit (St\u00E4rke*20)",
	L"Verzehrt die K\u00F6rperw\u00E4rme der gew\u00E4hlten feindlichen Einheit (St\u00E4rke*20)",
	L"Verzehrt die K\u00F6rperw\u00E4rme der gew\u00E4hlten feindlichen Einheit (St\u00E4rke*22)",
	L"Verzehrt die K\u00F6rperw\u00E4rme der gew\u00E4hlten feindlichen Einheit (St\u00E4rke*25)",
	L"Steigert das Gl\u00FCck der gew\u00E4hlten Einheit um 1.",
	L"Steigert das Gl\u00FCck der gew\u00E4hlten Einheit um 1.",
	L"Steigert das Gl\u00FCck der gew\u00E4hlten Einheit um 2.",
	L"Steigert das Gl\u00FCck aller eigenen Einheiten um 2.",
	L"Steigert die Moral der gew\u00E4hlten Einheit um 1.",
	L"Steigert die Moral der gew\u00E4hlten Einheit um 1.",
	L"Steigert die Moral der gew\u00E4hlten Einheit um 2.",
	L"Steigert die Moral aller freundlichen Einheiten um 2.",
	L"Verzehrt die K\u00F6rperw\u00E4rme jeder Einheit die am Zielort angrenzt, ohne Schaden am Ziel zu verursachen (St\u00E4rke*10)",
	L"Verzehrt die K\u00F6rperw\u00E4rme jeder Einheit die am Zielort angrenzt, ohne Schaden am Ziel zu verursachen (St\u00E4rke*10)",
	L"Verzehrt die K\u00F6rperw\u00E4rme jeder Einheit die am Zielort angrenzt, ohne Schaden am Ziel zu verursachen (St\u00E4rke*12)",
	L"Verzehrt die K\u00F6rperw\u00E4rme jeder Einheit die am Zielort angrenzt, ohne Schaden am Ziel zu verursachen (St\u00E4rke*15)",
	L"Sch\u00FCzt die gew\u00E4hlte Einheit vor allen Zaubern der Stufe 1-3.",
	L"Sch\u00FCzt die gew\u00E4hlte Einheit vor allen Zaubern der Stufe 1-3.",
	L"Sch\u00FCzt die gew\u00E4hlte Einheit vor allen Zaubern der Stufe 1-3.",
	L"Sch\u00FCzt die gew\u00E4hlte Einheit vor allen Zaubern.",
	L"Sie erhalten auf die gew\u00E4hlte Einheite einen Bonus auf Angriffsst\u00E4rke, Verteidigungsst\u00E4rke und Geschwindigkeit von 2.",
	L"Sie erhalten auf die gew\u00E4hlte Einheite einen Bonus auf Angriffsst\u00E4rke, Verteidigungsst\u00E4rke und Geschwindigkeit von 2.",
	L"Sie erhalten auf die gew\u00E4hlte Einheite einen Bonus auf Angriffsst\u00E4rke, Verteidigungsst\u00E4rke und Geschwindigkeit von 4.",
	L"Gibt Ihnen auf alle eigenen Einheitenein einen Bonus auf Angriffsst\u00E4rke, Verteidigungsst\u00E4rke und Geschwindigkeit von 4.",
	L"Erlaubt es Ihnen, ein Wasser Elementarwesen herbei zu rufen (St\u00E4rke*3), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Wasser Elementarwesen herbei zu rufen (St\u00E4rke*3), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Wasser Elementarwesen herbei zu rufen (St\u00E4rke*4), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, ein Wasser Elementarwesen herbei zu rufen (St\u00E4rke*5), {Einmal ausgesprochen, kann kein anderes Elementarwesen herbei gerufen werden.",
	L"Erlaubt es Ihnen, Feen zu beschw\u00F6ren (Power*5).",
	L"Erlaubt es Ihnen, Feen zu beschw\u00F6ren (Power*5).",
	L"Erlaubt es Ihnen, Feen zu beschw\u00F6ren (Power*7).",
	L"Erlaubt es Ihnen, Feen zu beschw\u00F6ren (Power*10).",
	L"Nach einem gro\u00DFz\u00FCgigen Trinkgeld fl\u00FCstert der Wirt zu Ihnen:",
	L"Ein weiser Mann hat einst gesagt: \"Teile Ihre Weisheit mit niemanden.\"",
	L"Speicher Ihr Spiel bevor Sie die Hexenh\u00FCtte besuchen.",
	L"Teile Ihre Fernk\u00E4mpfer wenn Sie gegen selbige kampfen.",
	L"Finde den Gral. Er ist m\u00E4chtiger als du Ihnen vorstellen kannst.",
	L"Sch\u00FCtze im Kampf immer Ihre Fernkampfeinheiten.",
	L"Manchmal ist der beste Weg eine Niederlage zu vermeiden den Kampf zu umgehen.",
	L"Greife da an, wo Ihr Gegner schwach ist.",
	L"Es ist besser die schweren K\u00E4mpfe mit Ihrem besten Helden zu bestreiten.",
	L"Versuche die gegnerischen Bewegungen vorherzusehen.",
	L"Beim Reisen durch die W\u00FCste halte nach Oasen ausschau. Sie werden Ihre Reise beschleunigen.",
	L"Es gibt Sicherheit in den Zahlen, besonders wenn jene Zahlen in den Tausenden sind!",
	L"Wenn du Elfen hast und Ihr Gegner stark aber langsam ist, lauf herum.",
	L"Bek\u00E4mpfe Feuer mit Schutz vor Feuer",
	L"Trolle mit Steinhaut sind eine der st\u00E4rksten Kreaturen.",
	L"Beschw\u00F6re Pr\u00E4zision und Segnen auf Ihre Fernk\u00E4mpfer.",
	L"Verwende Steinhaut wenn Ihre Kreaturen von T\u00FCrmen angeriffen werden.",
	L"Schwarze Drachen sind die m\u00E4chtigsten Kreaturen der Gew\u00F6lbe.",
	L"Die Phoenixe sind die st\u00E4rksten Kreaturen des Waldes.",
	L"Kreaturen der unteren Stufen verlangsamen Sie.",
	L"Hey, mir sind die Ger\u00FCchte ausgegangen, weil Leute wie DU nicht oft genug vorbei kommen, um sie mit mir zu teilen!",
	L"Lass Ihre Kavalerie durch die feindlichen Truppen reiten. Du wirst das Resultat m\u00F6gen. Es ist bedeutend besser.",
	L"Ich habe einmal einen Zwerg gesehen, der gegen Zauber immun war.",
	L"Die Truppe, die auf dem Schlachtfeld den ersten Schlag ausf\u00FChrt, gewinnt meistens.",
	L"Auf dem Schlachtfeld ist Geschwindigkeit Leben und Leben Geschwindigkeit.",
	L"Ich habe sterbende Vampire gesehen, die in dem Blut gefallender Feinde wiedergeboren wurden.",
	L"Es ist unm\u00F6glich Vergeltung auszu\u00FCben, angesichts des furchterregenden Angriffs eines Vampires.",
	L"Der Angriff eines Lichs zerrei\u00DFt die Lebenden, w\u00E4hrend er die Toten unber\u00FChrt l\u00E4\u00DFt.",
	L"Auf dem Schlachtfeld erzeugen Knochen-Drachen Furcht in den Herzen ihrer Feinde.",
	L"Golems haben keinen eigenen Verstand.",
	L"Golems werden durch die magischen Mittel belebt, die den meisten Leuten unbekannt sind.",
	L"Die Kombination aus Drachen und dem Zauberspruch Armageddon ist sehr t\u00F6dlich.",
	L"Titanen werden Schwarze Drachen mit mehr Grausamkeit angreifen als jeder andere.",
	L"Viele f\u00FCrchten den versteinernden Angriff der Medusa. Du solltest mehr ihre goldenen Pfeile f\u00FCrchten.",
	L"Sogar gegen \u00FCberw\u00E4ltigende \u00DCbermacht, feiert der Minotaure im Blutdurst des Kampfes.",
	L"Die F\u00E4higkeiten Logistik und Wegfindung sind wichtig.",
	L"Versuche nicht nutzlose Armeen zu kaufen.",
	L"Es ist unm\u00F6glich einen Angriff gegen die vielk\u00F6pfige Hydra zu vergelten.",
	L"Einige glauben, dass jede Necropolis einen \"Nekromantie Verst\u00E4rker\" baut, der ihren Helden hilft die Toten auferstehen zu lassen.",
	L"Helden, die die \"Halle der Vorfahren\" in einer Festung besuchen, werden bessere Krieger.",
	L"Beitreten.",
	L"Erstellen",
	L"Start!",
	L"Bereit",
	L"Profil...",
	L"Fehler",
	L"Verbindung fehlgeschlagen. Bitte versuchen Sie es sp\u00E4ter noch einmal",
	L"Spieler entfernt",
	L"%s wurde entfernt und ersetzt durch Computerspieler.",
	L"Spiel abgebrochen",
	L"Host hat beschlossen das Spiel abzubrechen.",
	L"Anmelden nicht m\u00F6glich",
	L"User ID ung\u00FCltig.",
	L"Sie nehmen an einem Spiel teil",
	L"M\u00F6chten Sie fortfahren?",
	L"Spiel existiert nicht mehr.",
	L"Spiel voll.",
	L"Beitreten nicht m\u00F6glich",
	L"Erstellen nicht m\u00F6glich",
	L"Das Spiel, an dem Sie teilgenommen haben, ist beendet.",
	L"Speicherstand hochladen...",
	L"Speicherstand runterladen..",
	L"Verbinden zum Server...",
	L"Netz nicht verf\u00FCgbar",
	L"Spieler inm Lobby",
	L"Neuer Mensch im Spiel!",
	L"Bitte, warten f\u00FCr andere Spieler um beizutreten!",
	L"%s Spieler (AI) ist mit %s (Mensch) ersetzt.",
	L"Checking for updates...",
	L"Update available",
	L"Would you like to update now?",
	L"Updating...",
	L"The game will now restart to complete update process",
	L"You are defeated!",
	L"Do you wish to stay in the game as an observer?",
	L"Are you sure you want to permanently kick %s?",
	L"You have been kicked by host.",
	L"Schnell laden",
	L"Schnell speichern",
	L"Zug beenden (E)",
	L"Den Weg best\u00E4tigen (Space)",
	L"N\u00E4chster Charakter (Tab)",
	L"Zum Spielmen\u00FC (Esc)",
	L"Zur Kleinansicht (M)",
	L"Den gew\u00E4hlten Charakter zeigen (Enter)",
	L"Das gew\u00E4hlte Schloss zeigen (Enter)",
	L"Raus (Esc)",
	L"Zauberspruch anwenden(C)",
	L"Markt",
	L"Magie",
	L"Taverne",
	L"Bauen",
	L"Rekrutieren",
	L"Entlassen",
	L"Graben",
	L"R\u00E4tsel",
	L"Zaubern",
	L"Nicht mehr zeigen",
	L"Mit dem Finger k\u00F6nnen Sie die Karte bewegen und den Weg f\u00FCr den ausgew\u00E4hlten Charakter bestimmen. Gleich ausprobieren!",
	L"Der Weg liegt in einer unerreichbaren Gegend. Vielleicht ist ein Hindernis im Weg. Versuchen Sie ein anderes Ziel.",
	L"Sie haben einen Gegenstand von der Karte geholt. Daraufhin verschwinden die Gegenst\u00E4nde.",
	L"Sie haben ein besuchbares Geb\u00E4ude betreten. Viele davon geben dem Charakter unterschiedliche Bonuspunkte.",
	L"Sie bestizen ein Geb\u00E4ude. Schauen Sie - dar\u00FCber weht jetzt Ihre Flagge. Viele von solchen Geb\u00E4uden sichern Ihnen t\u00E4gliche Ertr\u00E4ge.",
	L"Sie sind auf dem Schlo\u00DFbildschirm. Hier k\u00F6nnen Sie bauen, Charaktere und magische Wesen rekrutieren und die magischen Fertigkeiten ihrer Charaktere ausbauen. Gleiten Sie mit dem Cursor nach rechts oder nach links, um zwischen den Bildschirmen zu wechseln. Gleiten Sie nach oben, um den Bildschirm zu verlassen.",
	L"Auf dem Baubildschirm k\u00F6nnen Sie Geb\u00E4ude errichten. Ber\u00FChren Sie ein Geb\u00E4ude, um den Bau zu starten. An roten Geb\u00E4uden kann im Moment nicht gebaut werden - vielleicht brauchen Sie zus\u00E4tzliche Ressourcen. Sie k\u00F6nnen in jedem Schlo\u00DF nur einmal pro Tag bauen.",
	L"Auf dem Rekrutierungsbildschirm k\u00F6nnen Sie Wesen f\u00FCr Ihre Armeen rekrutieren. W\u00E4hlen Sie oben den Wesenstyp, dann die n\u00F6tige Zahl davon und dr\u00FCcken Sie die Rekrutierungstaste. Unten finden Sie die Schlo\u00DFbesatzung - da m\u00FCssen zur Abwehr auch einige Wesen untergebracht werden.",
	L"Auf dem Tavernenbildschirm k\u00F6nnen Sie einmal pro Woche einen neuen Charakter rekrutieren oder ein Schiff kaufen, wenn Ihr Schlo\u00DF am Wasser liegt.",
	L"Auf dem Bildschirm der Magiergilde sehen sie die Zauberspr\u00FCche, die in allen Magiergilden des Schlo\u00DFes erh\u00E4ltlich sind. Jedes Schlo\u00DF hat eine einzigartige Reihe von Zauberspr\u00FCchen auf den Levels von 1 bis 5. Sie k\u00F6nnen weitere Zauberspr\u00FCche erwerben, indem Sie an der Magiergilde weiterbauen.",
	L"Auf dem Marktbildschirm k\u00F6nnen Sie Ressourcen tauschen. W\u00E4hlen Sie die zu tauschende Ressource links und die gew\u00FCnscht Ressource rechts. Der Tauschkurs wird desto g\u00FCnstiger, je mehr M\u00E4rkte Sie besitzen.",
	L"",
	L"Auf dem Eigenschaftenbildschirm k\u00F6nnen Sie Erfahrung, Kraft, Gl\u00FCck und andere Eigenschaften Ihres Charakters nachschauen. Ber\u00FChren Sie das Zeichen, um mehr davon zu erfahren.",
	L"Auf diesem Bildschirm k\u00F6nnen Sie die Items des Charakters verwalten - Sie anziehen oder in die Tasche stecken. Nur die angezogenen Items geben dem Charakter Bonuspunkte.",
	L"Im Buch der Zauberspr\u00FCche k\u00F6nnen Sie sich \u00FCber die Zauberspr\u00FCche des ausgew\u00E4hlten Chrakters informieren. Ber\u00FChren Sie das Bild von einem Zauberspruch, um dar\u00FCber mehr zu erfahren.",
	L"Zwei Charaktere sind einander begegnet! Sie k\u00F6nnen die beiden ihre Armeen und Items austauschen lassen. Durch eine Gleibewegung nach oben verlassen Sie diesen Bildschirm.",
	L"Auf dem Armeentauschbildschirm k\u00F6nnen Sie die Streitkr\u00E4fte zwischen zwei Charakteren verteilen.",
	L"Auf dem Itemtauschbildschirm k\u00F6nnen Sie einige Items aus der Tasche eines Charakters in die des anderen schicken.",
	L"Ein Kampf hat angefangen! Der Kampf verl\u00E4uft in Z\u00FCgen, jede Truppe bewegt sich und greift der Reihe nach an. Ber\u00FChren Sie das Kampffeld, um die gew\u00E4hlte Truppe zu bewegen. Ber\u00FChren Sie den Feind, um anzugreifen. Viele Wesen haben besondere Fertigkeiten, wie Bogenschie\u00DFen oder Fliegen. Greifen Sie zum Buch der Zauberspr\u00FCche und die Informationstase (I), um mehr \u00FCber Ihre Wesen zu erfahren.",
	L"Ihre Z\u00FCge f\u00FCr heute sind verbraucht. Dr\u00FCcken Sie die blinkende Endtaste, um einen Zug auszulassen.",
	L"Mit der Taste links k\u00F6nnen Sie schnell zu einem weiteren Charakter oder Schlo\u00DF wechseln.",
	L"Links unten finden Sie die Kleinansichttaste, mit der Sie sich schnell auf der ganzen Karte bewegen k\u00F6nnen.",
	L"Unter der Taste zur Auswahl von Charakteren und Schl\u00F6ssern befindet sich die Informationstaste. Dr\u00FCcken Sie die und ber\u00FChren Sie die Karte, um mehr \u00FCber einzelne Gegenst\u00E4nde und Wesen zu erfahren. Dr\u00FCcken Sie die erneut, um den Informationsmodus zu verlassen.",
	L"Ber\u00FChren Sie das Ziel erneut, um die Bewegung aufzunehmen.",
	L"Sie haben noch einen Charakter rekrutiert! Sie k\u00F6nnen frei zwischen ihnen wechseln mit der Taste links zur Auswahl von Charakteren und Schl\u00F6ssern. Erkunden Sie die Welt mit dem neuen Charakter!",
	L"Ber\u00FChren Sie das Schlo\u00DF zweimal, um es zu betreten. Ber\u00FChren Sie den Charakter zweimal, um mehr \u00FCber seine Fertigkeiten zu erfahren.",
	L"Die Taste mit dem Pferd rechts erm\u00F6glicht schnelle Bewegung in gew\u00E4hlte Richtung oder platziert den Charakter mittig auf dem Bildschirm.",
	L"Sie haben ein Schlo\u00DF gew\u00E4hlt. Um es zu betreten, dr\u00FCcken Sie das Schlo\u00DF-Icon oben links. Zur\u00FCck zum Charakter gelangen Sie, indem Sie die Taste links zur Auswahl von Charakteren und Schl\u00F6ssern dr\u00FCcken.",
	L"Dieser Charakter ist zu m\u00FCde zum Weitergehen. Der restliche Teil von seinem Weg wird rot - das hei\u00DFt, am n\u00E4chsten Tag geht es weiter. Um den Zug auszulassen, dr\u00FCcken Sie die Taste unten rechts.",
	L"Erforschen Sie die Karte mit dem Charakter, k\u00E4mpfen Sie gegen neutrale Wesen und die Charaktere Ihres Gegners. In Ihren Schl\u00F6ssern k\u00F6nnen Sie weitere Wesen oder Charaktere rekrutieren oder Angriffe und Abwehr planen. Sie k\u00F6nnen weitere Schl\u00F6sser erobern und noch mehr Charaktere rekrutieren. Mit der Zeit gewinnen Ihre Charaktere an Erfahrung und Kraft.",
	L"Dr\u00FCcken Sie die Informationstaste (I) und ber\u00FChren Sie ein Wesen auf dem Kampffeld, um seine Eigenschaften zu sehen. dr\u00FCcken Sie die Taste reneut, um den Informationsmodus zu verlassen.",
	L"Die Verteidigungstaste l\u00E4sst f\u00FCr die gew\u00E4hlte Truppe einen Zug aus, verleiht der Truppe aber zeitweilig einen Bonuspunkt an Abwehr.",
	L"Die Wartetaste l\u00E4sst die gew\u00E4hlte Truppe beim Zug als letzte dran sein.",
	L"W\u00E4hlen Sie einen Zauberspruch, dann w\u00E4hlen Sie das Ziel und best\u00E4tigen Sie es. Die angreifbaren Ziele sind mit Gr\u00FCn markiert.",
	L"Nicht mehr zeigen.",
	L"",
	L"Der Weg liegt in einer unerreichbaren Gegend. Vielleicht ist ein Hindernis im Weg. Versuchen Sie ein anderes Ziel.",
	L"Sie haben einen Gegenstand von der Karte geholt. Daraufhin verschwinden die Gegenst\u00E4nde.",
	L"Sie haben ein besuchbares Geb\u00E4ude betreten. Viele davon geben dem Charakter unterschiedliche Bonuspunkte.",
	L"Sie bestizen ein Geb\u00E4ude. Schauen Sie - dar\u00FCber weht jetzt Ihre Flagge. Viele von solchen Geb\u00E4uden sichern Ihnen t\u00E4gliche Ertr\u00E4ge.",
	L"Sie sind auf dem Schlo\u00DFbildschirm. Hier k\u00F6nnen Sie bauen, Charaktere und magische Wesen rekrutieren und die magischen Fertigkeiten ihrer Charaktere ausbauen (B, T, R, M, S).",
	L"Auf dem Baubildschirm k\u00F6nnen Sie Geb\u00E4ude errichten. Ber\u00FChren Sie ein Geb\u00E4ude, um den Bau zu starten. An roten Geb\u00E4uden kann im Moment nicht gebaut werden - vielleicht brauchen Sie zus\u00E4tzliche Ressourcen. Sie k\u00F6nnen in jedem Schlo\u00DF nur einmal pro Tag bauen.",
	L"Auf dem Rekrutierungsbildschirm k\u00F6nnen Sie Wesen f\u00FCr Ihre Armeen rekrutieren. W\u00E4hlen Sie oben den Wesenstyp, dann die n\u00F6tige Zahl davon und dr\u00FCcken Sie die Rekrutierungstaste. Unten finden Sie die Schlo\u00DFbesatzung - da m\u00FCssen zur Abwehr auch einige Wesen untergebracht werden.",
	L"Auf dem Tavernenbildschirm k\u00F6nnen Sie einmal pro Woche einen neuen Charakter rekrutieren oder ein Schiff kaufen, wenn Ihr Schlo\u00DF am Wasser liegt.",
	L"Auf dem Bildschirm der Magiergilde sehen sie die Zauberspr\u00FCche, die in allen Magiergilden des Schlo\u00DFes erh\u00E4ltlich sind. Jedes Schlo\u00DF hat eine einzigartige Reihe von Zauberspr\u00FCchen auf den Levels von 1 bis 5. Sie k\u00F6nnen weitere Zauberspr\u00FCche erwerben, indem Sie an der Magiergilde weiterbauen.",
	L"Auf dem Marktbildschirm k\u00F6nnen Sie Ressourcen tauschen. W\u00E4hlen Sie die zu tauschende Ressource links und die gew\u00FCnscht Ressource rechts. Der Tauschkurs wird desto g\u00FCnstiger, je mehr M\u00E4rkte Sie besitzen.",
	L"Sie sind auf dem Charakterbildschirm. Hier k\u00F6nnen Sie den Wachstum Ihres Charakters in unterschiedlichen Bereichen beobachten, Moral und Gl\u00FCck Ihrer Armee, magische Gegenst\u00E4nde f\u00FCr Anwendung aussuchen und das Zauberspr\u00FCchenbuch durchschauen.",
	L"Im Buch der Zauberspr\u00FCche k\u00F6nnen Sie sich \u00FCber die Zauberspr\u00FCche des ausgew\u00E4hlten Chrakters informieren. Ber\u00FChren Sie das Bild von einem Zauberspruch, um dar\u00FCber mehr zu erfahre.",
	L"Zwei Charaktere sind einander begegnet! Sie k\u00F6nnen die beiden ihre Armeen und Items austauschen lassen.",
	L"Ein Kampf hat angefangen! Der Kampf verl\u00E4uft in Z\u00FCgen, jede Truppe bewegt sich und greift der Reihe nach an. Ber\u00FChren Sie das Kampffeld, um die gew\u00E4hlte Truppe zu bewegen. Ber\u00FChren Sie den Feind, um anzugreifen. Viele Wesen haben besondere Fertigkeiten, wie Bogenschie\u00DFen oder Fliegen. Greifen Sie zum Buch der Zauberspr\u00FCche und die rechte Maustaste, um mehr \u00FCber Ihre Wesen zu erfahren.",
	L"Ihre Z\u00FCge f\u00FCr heute sind verbraucht. Dr\u00FCcken Sie die blinkende Endtaste, um einen Zug auszulassen.",
	L"Mit der Taste rechts k\u00F6nnen Sie schnell zu einem weiteren Charakter oder Schlo\u00DF wechseln.",
	L"Dr\u00FCcken Sie die recite Maustaste und ber\u00FChren Sie die Karte, um mehr \u00FCber einzelne Gegenst\u00E4nde und Wesen zu erfahren.",
	L"Ber\u00FChren Sie das Ziel erneut, um die Bewegung aufzunehmen.",
	L"Sie haben noch einen Charakter rekrutiert! Sie k\u00F6nnen frei zwischen ihnen wechseln mit der Taste links zur Auswahl von Charakteren und Schl\u00F6ssern. Erkunden Sie die Welt mit dem neuen Charakter!",
	L"Ber\u00FChren Sie das Schlo\u00DF zweimal, um es zu betreten. Ber\u00FChren Sie den Charakter zweimal, um mehr \u00FCber seine Fertigkeiten zu erfahre.",
	L"Die Taste mit dem Pferd rechts erm\u00F6glicht schnelle Bewegung in gew\u00E4hlte Richtung oder platziert den Charakter mittig auf dem Bildschirm. Auch m\u00F6glich mit SPACE Taste.",
	L"Sie haben ein Schlo\u00DF gew\u00E4hlt. Um es zu betreten, dr\u00FCcken Sie das Schlo\u00DF-Icon unten. Zur\u00FCck zum Charakter gelangen Sie, indem Sie die Taste links zur Auswahl von Charakteren und Schl\u00F6ssern dr\u00FCcken (auch mit TAB Taste).",
	L"Dieser Charakter ist zu m\u00FCde zum Weitergehen. Der restliche Teil von seinem Weg wird rot - das hei\u00DFt, am n\u00E4chsten Tag geht es weiter. Um den Zug auszulassen, dr\u00FCcken Sie die Taste unten rechts (oder mit der Taste E).",
	L"Erforschen Sie die Karte mit dem Charakter, k\u00E4mpfen Sie gegen neutrale Wesen und die Charaktere Ihres Gegners. In Ihren Schl\u00F6ssern k\u00F6nnen Sie weitere Wesen oder Charaktere rekrutieren oder Angriffe und Abwehr planen. Sie k\u00F6nnen weitere Schl\u00F6sser erobern und noch mehr Charaktere rekrutieren. Mit der Zeit gewinnen Ihre Charaktere an Erfahrung und Kraft.",
	L"Dr\u00FCcken Sie die rechte Maustaste und ber\u00FChren Sie ein Wesen auf dem Kampffeld, um seine Eigenschaften zu sehen.",
	L"Die Verteidigungstaste (D) l\u00E4sst f\u00FCr die gew\u00E4hlte Truppe einen Zug aus, verleiht der Truppe aber zeitweilig einen Bonuspunkt an Abwehr.",
	L"Die Wartetaste (W) l\u00E4sst die gew\u00E4hlte Truppe beim Zug als letzte dran sein..",
	L"W\u00E4hlen Sie einen Zauberspruch, dann w\u00E4hlen Sie das Ziel und best\u00E4tigen Sie es. Die angreifbaren Ziele sind mit Gr\u00FCn markiert."};
