#ifdef MULTIPLAYER

#include "StdAfx.h"

iCharA binary_cmds[BINARY_CMDS] = {
	MPC_UPDATE_OWNCNST,
	MPC_UPDATE_VISCNST,
	MPC_UPDATE_MAPGUARD,	
	MPC_UPDATE_MAPITEM,
	MPC_UPDATE_CASTLE,
	MPC_UPDATE_HERO,
	MPC_UPDATE_MINERALS
};


#endif //MULTIPLAYER