#ifndef COMPLIB_XXC_XXC_WBOX_H_
#define COMPLIB_XXC_XXC_WBOX_H_
//
// WBoxing (simple Feistel cipher with whitened key schedule)
//

#include "xxc.defs.h"

namespace xxc {

// autogenerated by 'wwbox':
// w-box functions (whiteboxed s-boxes)
unsigned char wbox001( const unsigned char );
unsigned char wbox002( const unsigned char );

// constants decryptor function
// NB:: should be strictly inlined??
uint32 wbox_dec( uint32 in );

// constants file
// 
extern const uint32 e_eccX[7];
extern const uint32 e_eccY[7];
extern const uint32 e_hashBoot[16];
extern const uint32 e_cipherKey[4];
extern const uint32 e_bloomMix[7];
extern const uint32 e_puk[4];

} //xxc


#endif //COMPLIB_XXC_XXC_WBOX_H_
