#ifndef PHEROES_GAME_VIEWDEFS_H_
#define PHEROES_GAME_VIEWDEFS_H_

/*
 *	
 */
const uint32 VPUID_ENG				= 65536;

const uint32 VPUID_BASE				= VPUID_ENG + 1;
const uint32 VPUID_MAINVIEW			= VPUID_ENG + 10;
const uint32 VPUID_MINIMAPVIEW		= VPUID_ENG + 11;
const uint32 VPUID_CASTLEVIEW		= VPUID_ENG + 12;
const uint32 VPUID_HEROVIEW			= VPUID_ENG + 13;
const uint32 VPUID_MAINTOOLBARVIEW	= VPUID_ENG + 20;
const uint32 VPUID_MMAPTOOLBARVIEW	= VPUID_ENG + 21;
const uint32 VPUID_INFOBARVIEW		= VPUID_ENG + 30;
const uint32 VPUID_CTLVIEWTOOLBAR	= VPUID_ENG + 40;
const uint32 VPUID_CTLVIEWTITLELBAR	= VPUID_ENG + 41;
const uint32 VPUID_HEROVIEWTOOLBAR	= VPUID_ENG + 50;
const uint32 VPUID_HEROVIEWTITLELBAR= VPUID_ENG + 51;
const uint32 VPUID_HCSELECT			= VPUID_ENG + 52;
const uint32 VPUID_OVERLAND_TOOLBAR = VPUID_ENG + 53;
const uint32 VPUID_RESOURCEBAR = VPUID_ENG + 54;

const uint32 VPUID_MODE_SWITCH		= VPUID_ENG + 100;
const uint32 VPUID_BTN_MINIMAP		= VPUID_ENG + 101;
const uint32 VPUID_BTN_STATE		= VPUID_ENG + 102;
const uint32 VPUID_BTN_NTURN		= VPUID_ENG + 103;
const uint32 VPUID_BTN_MENU	     	= VPUID_ENG + 104;
const uint32 VPUID_BTN_INFO			= VPUID_ENG + 105;
const uint32 VPUID_BTN_NHERO		= VPUID_ENG + 106;
const uint32 VPUID_BTN_HERO			= VPUID_ENG + 107;
const uint32 VPUID_BTN_CASTLE		= VPUID_ENG + 108;
const uint32 VPUID_BTN_HORSE		= VPUID_ENG + 109;
const uint32 VPUID_BTN_CAST			= VPUID_ENG + 110;
const uint32 VPUID_BTN_HORSE2		= VPUID_ENG + 111;
const uint32 VPUID_BTN_QSAVE		= VPUID_ENG + 112;
const uint32 VPUID_BTN_QLOAD		= VPUID_ENG + 113;


const uint32 VPUID_BTN_OBJICN		= VPUID_ENG + 200;
const uint32 VPUID_PRG_OBJACT		= VPUID_ENG + 201;
const uint32 VPUID_BTN_OBJPROPS		= VPUID_ENG + 203;
const uint32 VPUID_BTN_HMOVE		= VPUID_ENG + 204;
const uint32 VPUID_BTN_LIST			= VPUID_ENG + 205;
const uint32 VPUID_BTN_OPENCITY		= VPUID_ENG + 206;

const uint32 VPUID_BTN_ZOOMIN		= VPUID_ENG + 301;
const uint32 VPUID_BTN_ZOOMOUT		= VPUID_ENG + 302;
const uint32 VPUID_BTN_CLOSEMMAP	= VPUID_ENG + 303;
const uint32 VPUID_BTN_ENDBATTLE	= VPUID_ENG + 304;
const uint32 VPUID_BTN_CLOSECITY	= VPUID_ENG + 305;
const uint32 VPUID_BTN_CLOSEHERO	= VPUID_ENG + 306;



#endif //PHEROES_GAME_VIEWDEFS_H_
